### ISSUE TITLE
Crash on startup if Google Play Services requires updating

### ISSUE THREAD

**Issue by osadchuk** [invertase/react-native-firebase#102]
When initializing Firebase on a device where Google Play Services needs to be updated, the app will crash:

```
05-09 15:34:51.815 2294-2428/com.momentussoftware.specsonline E/unknown:React: Exception in native call
   java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
  at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source)
  at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(Unknown Source)
  at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(Unknown Source)
  at io.invertase.firebase.RNFirebaseModule.promptPlayServices(RNFirebaseModule.java:37)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
  at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:136)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
  at android.os.Looper.loop(Looper.java:155)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
  at java.lang.Thread.run(Thread.java:818)
```

When `promptPlayServices()` is getting called, `getCurrentActivity()` returns `null`, which is causing the crash.

This could be fixed by null-checking `getCurrentActivity()`, but I was wondering if there's a recommended point in the app startup flow where we should be calling `RNFirebase.initializeApp()`, so that we can show the error dialog to affected users?

Thanks!
Darren

**Comment by Ehesp** [comment]
I believe @chrisbianca implemented this, will ping him!

**Comment by chrisbianca** [comment]
@osadchuk at what point are you currently initialising Firebase in your app?

I'm surprised that the current activity is null.  I know this is a valid scenario, but it only tends to be when switching between apps, not when the application first starts.

**Comment by osadchuk** [comment]
@chrisbianca I think I found the problem, or at least part of it. As background, we're using [react-native-navigation](https://github.com/wix/react-native-navigation). At start-up, we create a single-screen app to check if the user is logged in and, if not, onboard them. Once they're logged in, the app switches to a tab-based app. If they're already logged in from a previous session, then the single-screen app switches automatically to the tab-based app.

If I add in the null check, then when the app starts up and Firebase is initialized during onboarding, I can see the 'update Google Play Services' alert flash briefly, but it disappears when the tab-based app starts up. I think that react-native-navigation creates new activities for single-screen, tab-based, etc. apps, so my guess is that Firebase was getting initialized at some point during the switch from single-screen to tab-based app, when the activity is (briefly) null. This is just a guess, though.

I've moved Firebase initialization over to the initial screen shown in the tab-based app. The alert appears and persists, and all is well.

Thanks!
Darren

**Comment by chrisbianca** [comment]
Wow, that's a good find, and kind of makes sense, though it's an interesting approach from react-native-navigation to use different activities between the different types of app.

Glad you've managed to resolve the problem, though I'll leave this issue open until I've added in a null check to stop it from crashing should something similar arise elsewhere.

**Comment by Ehesp** [comment]
@osadchuk I've used the navigator in another project and didn't actually see this issue with RNFirebase and new activities - interesting one though!

**Comment by chrisbianca** [comment]
Just pushed a fix to null check and only prompt if there is a current activity
