### ISSUE TITLE
[Android] [Auth] [Crash] - Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()'

### ISSUE THREAD

**Issue by paintedbicycle** [invertase/react-native-firebase#1068]
### Environment
Android only

My app has been working fine, but having an error pop up recently. I believe it's leading to crashes and has to do with auth. I can tell from my app and logs that the anonymous auth goes fine and that a user is successfully returned and the app page renders. But investigating a crash that I thought was unrelated to firebase, I also see this highlighted in red in logs.

```
Failed to turn object into JSON
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
```

Any thoughts to point me in the right direction?

Full details below:

```
05-10 14:24:32.184 6618-6642/ D/FA: Setting user property (FE): _id, PZvDi4aPdedBCd9LwL3kuSiq22i1
05-10 14:24:32.189 6618-6720/ I/zygote: The ClassLoaderContext is a special shared library.
05-10 14:24:32.192 6618-6651/ I/DynamiteModule: Considering local module com.google.android.gms.flags:2 and remote module com.google.android.gms.flags:0
05-10 14:24:32.194 6618-6651/ I/DynamiteModule: Selected local version of com.google.android.gms.flags
05-10 14:24:32.266 6618-6720/ I/zygote: The ClassLoaderContext is a special shared library.
05-10 14:24:32.341 6618-6720/ I/zygote: The ClassLoaderContext is a special shared library.
05-10 14:24:32.376 6618-6720/ W/common.FileUtils: Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
05-10 14:24:32.377 6618-6720/ W/common.FileUtils: Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
05-10 14:24:32.390 6618-6651/ W/zygote: Unsupported class loader
05-10 14:24:32.399 6618-6720/ W/common.FileUtils: Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
05-10 14:24:32.400 6618-6720/ W/common.FileUtils: Failed to set dir world executable: java.io.FileNotFoundException: /data/user_de/0/com.google.android.gms/files/gmscore_global_dirs.txt: open failed: EACCES (Permission denied)
05-10 14:24:32.410 6618-6720/ W/linker: "/data/user_de/0/com.google.android.gms/app_extracted_libs/x86/libconscrypt_gmscore_jni.so" unused DT entry: type 0xf arg 0x91
05-10 14:24:32.416 6618-6720/ V/NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 279 native methods...
05-10 14:24:32.426 6618-6651/ W/zygote: Skipping duplicate class check due to unsupported classloader
05-10 14:24:32.427 6618-6651/ W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
05-10 14:24:32.428 6618-6651/ W/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@a65b73c
05-10 14:24:32.428 6618-6668/ W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
05-10 14:24:32.430 6618-6668/ I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
    [FirebaseAuth:] Preparing to create service connection to gms implementation
05-10 14:24:32.466 6618-6720/ I/ProviderInstaller: Installed default security provider GmsCore_OpenSSL
05-10 14:24:32.645 6618-6630/ I/zygote: Background concurrent copying GC freed 25448(1807KB) AllocSpace objects, 4(80KB) LOS objects, 49% free, 3MB/6MB, paused 9.999ms total 65.756ms
05-10 14:24:32.745 6618-6720/ W/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzal@a65b73c
05-10 14:24:32.850 6618-6632/ E/StorageHelpers: Failed to turn object into JSON
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
        at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:116)
        at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3)
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:92)
        at com.google.firebase.auth.zzm.zza(Unknown Source:3)
        at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source:27)
        at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source:41)
        at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:139)
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.execTransact(Binder.java:697)
05-10 14:24:32.860 6618-6632/ W/Binder: Caught a RuntimeException from the binder stub implementation.
    com.google.android.gms.internal.firebase_auth.zzv: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
        at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:140)
        at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3)
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:92)
        at com.google.firebase.auth.zzm.zza(Unknown Source:3)
        at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source:27)
        at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source:41)
        at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:139)
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.execTransact(Binder.java:697)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
        at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:116)
        at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3) 
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:92) 
        at com.google.firebase.auth.zzm.zza(Unknown Source:3) 
        at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source:27) 
        at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0) 
        at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0) 
        at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source:41) 
        at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:139) 
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22) 
        at android.os.Binder.execTransact(Binder.java:697) 
05-10 14:24:33.115 6618-6632/ E/StorageHelpers: Failed to turn object into JSON
    java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
        at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:116)
        at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3)
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:92)
        at com.google.firebase.auth.zzm.zza(Unknown Source:3)
        at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source:27)
        at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source:41)
        at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:139)
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.execTransact(Binder.java:697)
05-10 14:24:33.122 6618-6632/ W/Binder: Caught a RuntimeException from the binder stub implementation.
    com.google.android.gms.internal.firebase_auth.zzv: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
        at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:140)
        at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3)
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:92)
        at com.google.firebase.auth.zzm.zza(Unknown Source:3)
        at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source:27)
        at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0)
        at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source:41)
        at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:139)
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.execTransact(Binder.java:697)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
        at com.google.firebase.auth.internal.zzz.zzi(Unknown Source:116)
        at com.google.firebase.auth.internal.zzz.zzg(Unknown Source:3) 
        at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:92) 
        at com.google.firebase.auth.zzm.zza(Unknown Source:3) 
        at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source:27) 
        at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source:0) 
        at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source:0) 
        at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source:41) 
        at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source:139) 
        at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source:22) 
        at android.os.Binder.execTransact(Binder.java:697) 

```

**Comment by chrisbianca** [comment]
@paintedbicycle these are all internal Firebase SDK errors so shouldn't be anything RNFirebase related.  Google have changed how the android libs work with each other recently - it's worth taking a look at the release notes here for 4.1.0 which explain some changes that need to be made to better support the new libs: https://github.com/invertase/react-native-firebase/releases/tag/v4.1.0

Annoyingly, even when specifying a particular version that did used to work, gradle will still try and download a new version that might not work.

**Comment by paintedbicycle** [comment]
Hmm, ok I guess I'll close this. I had already followed your update docs and moved to the latest everything, so shouldn't be that.

**Comment by geekymsk** [comment]
Getting the same issue mentioned by @paintedbicycle even after upgrading all firebase-firestore dependancies as mentioned in `https://github.com/invertase/react-native-firebase/releases/tag/v4.1.0`

**Comment by shekharskamble** [comment]
getting the same error

**Comment by paintedbicycle** [comment]
Likely not helpful, but I can say that this message wasn't the source of any crashing and was just showing up in my logs. I don't think it has anything to do with the RNFirebase repository. I think it's more to do with Firebase and RNFirebase.

I upgraded all my firebase config and functions to match the newest API and while the issue didn't go away, nothing seems to be wrong with my app.

**Comment by dbyilmaz** [comment]
@chrisbianca 

```
06-05 10:38:25.280 12617 12629 W Binder  : Binder call failed.
06-05 10:38:25.280 12617 12629 W Binder  : com.google.android.gms.internal.firebase_auth.zzv: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.internal.zzz.zzi(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.internal.zzz.zzg(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.zzm.zza(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.api.internal.zzaw.zzaa(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.api.internal.zzcy.zzal(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.api.internal.zzcy.zza(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.api.internal.zzdb.zzb(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.firebase.auth.api.internal.zzci.dispatchTransaction(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at com.google.android.gms.internal.firebase_auth.zzb.onTransact(Unknown Source)
06-05 10:38:25.280 12617 12629 W Binder  : 	at android.os.Binder.execTransact(Binder.java:573)
06-05 10:38:25.280 12617 12629 W Binder  : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.google.firebase.auth.internal.zzm.zzbf()' on a null object reference


```

**Comment by paintedbicycle** [comment]
@dbyilmaz "catch" is spelt wrong in your code. This may be why it doesn't catch.

**Comment by dbyilmaz** [comment]
@paintedbicycle I wrote here the wrong keyword.
