### ISSUE TITLE
The development server returned response error code : 500

### ISSUE THREAD

**Issue by Sharathnasa** [invertase/react-native-firebase#1168]
```
### Issue
Hi,

I tired to run the app which is inside the **tests folder** under the **react-native-firebase** root folder, by running the pod file(i mean installed the all dependencies). But i got the below mentioned error.

```
error: bundling failed: Error: Unable to resolve module `./../firebase` from `/Users/setup/react-native-firebase/tests/src/bgMessaging.js`: The module `./../firebase` could not be found from `/Users/setup/react-native-firebase/tests/src/bgMessaging.js`. Indeed, none of these files exist:

  * `/Users/setup/react-native-firebase/tests/firebase(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/Users/setup/react-native-firebase/tests/firebase/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/setup/react-native-firebase/tests/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)
    at ResolutionRequest.resolveDependency (/Users/setup/react-native-firebase/tests/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/Users/setup/react-native-firebase/tests/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/Users/setup/react-native-firebase/tests/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/setup/react-native-firebase/tests/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /Users/setup/react-native-firebase/tests/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/Users/setup/react-native-firebase/tests/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /Users/setup/react-native-firebase/tests/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.
```
In the code import is not able to find the firebase module like **import RNfirebase from './../firebase'**
I manually checked this in the respective path, it's not available. Could you please help with this?

### Environment

Environment
Application Target Platform: Android

Development Operating System: macOs 10.13.4

Build Tools: 0.55.1

React Native version: 0.55.1

RNFirebase Version: 4.2.0

Firebase Module: Notifications
```

**Comment by chrisbianca** [comment]
@Sharathnasa The tests app is a legacy app - our latest tests are in the `bridge` folder.  It is still possible to run the tests app. You'll need a few console windows open though and from the root `react-native-firebase` directory, you'll need to do the following:

*Setup*
1) `npm run tests-npm-install`
2) `npm run tests-pod-install` (for iOS)

*Leave these open*
3) `npm run tests-watch-start`
4) `npm run tests-packager`

Then you'll be able to use the standard `run-ios` and `run-android` tasks from within the tests package

**Comment by ahmadmrj** [comment]
Same Issue!!!
