### ISSUE TITLE
ANDROID: firestore transaction causing app crash 

### ISSUE THREAD

**Issue by Afsarunnisa** [invertase/react-native-firebase#1178]
### Environment
Android 

1. Application Target Platform:

macOS Sierra (10.12.6)

2. Development Operating System:

 Android Studio version 3.1.2

3. Build Tools:

4. React Native version:

0.55.4

5. RNFirebase Version:

4.0.4

6. Firebase Module:

we are using firebase firestore database for our app, while using transactions we are getting crash. 

our code is like this 

```
await firebase.firestore().runTransaction(async transaction => {
              const doc = await transaction.get(sfDocRef);
              // if it does not exist
              if (!doc.exists) {
                return Promise.reject("Doc doesnot exist");
              } else {
                const shouldLookoutTriggerTrans = this.checkIfLookoutShouldTrigger(doc._data);
                if(shouldLookoutTriggerTrans){
                  const isUserPresent = doc._data.selectedContacts.filter(
                    contact => contact.id == phoneNumber
                  );
                  if (isUserPresent.length > 0) {
                    const updatedContacts = doc._data.selectedContacts.map(
                      contact => {
                        if (contact.id === phoneNumber) {
                          contact.timeStamp = timeStamp;
                        }
                        return contact;
                      }
                    );
                    transaction.update(
                      sfDocRef,
                      "selectedContacts",
                      updatedContacts
                    );
                  }
                }else{
                  return Promise.reject("Lookout already triggered");
                }
              }
              return true;
            });
```

here is the crash report 

```
Fatal Exception: java.lang.IllegalMonitorStateException
       at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:123)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1235)
       at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:429)
       at io.invertase.firebase.firestore.RNFirebaseFirestoreTransactionHandler.safeUnlock(RNFirebaseFirestoreTransactionHandler.java:160)
       at io.invertase.firebase.firestore.RNFirebaseFirestoreTransactionHandler.abort(RNFirebaseFirestoreTransactionHandler.java:50)
       at io.invertase.firebase.firestore.RNFirebaseFirestore.transactionDispose(RNFirebaseFirestore.java:281)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by puf** [comment]
Also posted on: https://stackoverflow.com/questions/50699181/getting-crash-in-react-native-app-for-android

**Comment by thejasreem** [comment]
The actual crash is at
RNFirebaseFirestoreTransactionHandler.java line 160
io.invertase.firebase.firestore.RNFirebaseFirestoreTransactionHandler.safeUnlock

**Comment by Salakar** [comment]
@Afsarunnisa @thejasreem thanks both for the stack traces.

@thejasreem could you provide us with a code usage sample as well for comparison to @Afsarunnisa's issue.

Weirdly all our tests for transactions [here](https://github.com/invertase/react-native-firebase/blob/master/bridge/e2e/firestore/transactions.e2e.js) pass fine so initially not something we can reproduce as this may be an edge case - potentially a thread synchronisation issue.

A couple of questions:

- Are you using Wix navigator or just standard RNN one?
- What are the steps to reproduce - does it error immediately or are you doing something like backgrounding your app then whilst opening it up again it crashes?
- Whats your Java version?

@puf thanks for the heads-up.


---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Vietvantue** [comment]
Face the same issue.

**Comment by HyeonjuPark** [comment]
I have faced same issue too. This crash happens twice out of 100 on average but hard to test.
