### ISSUE TITLE
[Android] jumboMode

### ISSUE THREAD

**Issue by mesbahsabur** [invertase/react-native-firebase#129]
Hi guys,

Just wanted to mention that I couldn't get past this error (note that it is very similar to issue #48 but it's not the same):

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexIndexOverflowException: Cannot merge new index 65730 into a non-jumbo instruction!
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexIndexOverflowException: Cannot merge new index 65730 into a non-jumbo instruction!
        at com.android.dx.merge.InstructionTransformer.jumboCheck(InstructionTransformer.java:109)
        at com.android.dx.merge.InstructionTransformer.access$800(InstructionTransformer.java:26)
        at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(InstructionTransformer.java:72)
        at com.android.dx.io.CodeReader.callVisit(CodeReader.java:114)
        at com.android.dx.io.CodeReader.visitAll(CodeReader.java:89)
        at com.android.dx.merge.InstructionTransformer.transform(InstructionTransformer.java:49)
        at com.android.dx.merge.DexMerger.transformCode(DexMerger.java:842)
        at com.android.dx.merge.DexMerger.transformMethods(DexMerger.java:813)
        at com.android.dx.merge.DexMerger.transformClassData(DexMerger.java:786)
        at com.android.dx.merge.DexMerger.transformClassDef(DexMerger.java:682)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:542)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED
```

I finally managed to fix it by adding the following code into `app/build.gradle`

```
android {
    // 
    dexOptions {
        jumboMode = true
    }
```

As jumboMode is not mentioned anywhere here, it seems a curious fix to me... However, everything works fine now :)

**Comment by Ehesp** [comment]
Hey I believe this usually happens when your build gets over a certain size and some files become bigger than a certain amount, which triggers this error. This is more of an Android thing than related to this lib :)

**Comment by mesbahsabur** [comment]
I see. Great, thanks!

**Comment by rgoldiez** [comment]
This was helpful.  Thank you.

**Comment by perrosnk** [comment]
I am getting the same error after installing react-native-firebase and Firebase SDK.
Running on RN 0.49.3

**Comment by chrisbianca** [comment]
@perrosnk This is most likely caused by the Firestore dependency - see this discussion: https://github.com/invertase/react-native-firebase/issues/475
