### ISSUE TITLE
storage downloadFile doesn't work

### ISSUE THREAD

**Issue by Evgen74** [invertase/react-native-firebase#1327]
### Environment

1. Application Target Platform: Android
2. Development Operating System: macOS Sierra
3. Build Tools: Android Studio 3.1.3
4. `React Native` version: 0.55.4
5. `React Native Firebase` Version:  4.3.7
6. `Firebase` Module: storage
7. Are you using `typescript`: no
---
I have a file on the cloud storage and I'm trying to upload it to the phone this way:

```
firebase
  .storage()
  .ref( '/image.png' )
  .downloadFile( `${ RNFS.ExternalStorageDirectoryPath }/image.png` )
  .then( r => {
    console.log(r);
  })
  .catch( e => {
    console.log(e);
  });
```
in the end I get an error. here is the log
```
07-22 19:26:25.779 4550-4550/com.racurs D/RNFirebaseAuth: signInAnonymously:onComplete:success
07-22 19:26:25.780 4550-9850/com.racurs D/RNFirebaseStorage: downloadFile path: /image.png
07-22 19:26:25.781 4550-4550/com.racurs D/RNFirebaseStorage: downloadFile progress com.google.firebase.storage.StreamDownloadTask$TaskSnapshot@a2f08ff
07-22 19:26:25.784 4550-4550/com.racurs D/RNFirebaseStorage: downloadFile progress com.google.firebase.storage.StreamDownloadTask$TaskSnapshot@efeb6cc
07-22 19:26:28.332 4550-9859/com.racurs D/StreamDownloadTask: Initial opening of Stream failed
    java.io.IOException: Could not open resulting stream.
        at com.google.firebase.storage.StreamDownloadTask.zzn(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask.zza(Unknown Source)
        at com.google.firebase.storage.zzab.call(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask$zza.zzp(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask$zza.zza(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask.run(Unknown Source)
        at com.google.firebase.storage.StorageTask.zzl(Unknown Source)
        at com.google.firebase.storage.zzx.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
07-22 19:26:28.332 4550-9859/com.racurs E/StorageException: StorageException has occurred.
    An unknown error occurred, please check the HTTP result code and inner exception for server response.
     Code: -13000 HttpResult: 400
07-22 19:26:28.333 4550-9859/com.racurs E/StorageException: Could not open resulting stream.
    java.io.IOException: Could not open resulting stream.
        at com.google.firebase.storage.StreamDownloadTask.zzn(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask.zza(Unknown Source)
        at com.google.firebase.storage.zzab.call(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask$zza.zzp(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask$zza.zza(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask.run(Unknown Source)
        at com.google.firebase.storage.StorageTask.zzl(Unknown Source)
        at com.google.firebase.storage.zzx.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
    StorageException has occurred.
    An unknown error occurred, please check the HTTP result code and inner exception for server response.
     Code: -13000 HttpResult: 400
    Could not open resulting stream.
    java.io.IOException: Could not open resulting stream.
        at com.google.firebase.storage.StreamDownloadTask.zzn(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask.zza(Unknown Source)
        at com.google.firebase.storage.zzab.call(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask$zza.zzp(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask$zza.zza(Unknown Source)
        at com.google.firebase.storage.StreamDownloadTask.run(Unknown Source)
        at com.google.firebase.storage.StorageTask.zzl(Unknown Source)
        at com.google.firebase.storage.zzx.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
07-22 19:26:28.494 4550-4550/com.racurs E/RNFirebaseStorage: downloadFile failure An unknown error occurred, please check the HTTP result code and inner exception for server response.
```

**Comment by Evgen74** [comment]
I just had the wrong payment settings
