### ISSUE TITLE
W/FirebaseMessaging: Error while parsing timestamp in GCM event

### ISSUE THREAD

**Issue by fedeamura** [invertase/react-native-firebase#1340]
When the app is on foreground no notification is shown...
The logcat shows me this:

```
 W/FirebaseMessaging: Error while parsing timestamp in GCM event
    java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:570)
        at java.lang.Integer.parseInt(Integer.java:643)
        at com.google.firebase.messaging.zzb.zzc(Unknown Source:81)
        at com.google.firebase.messaging.zzb.zze(Unknown Source:2)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:280)
        at com.google.firebase.iid.zzc.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
```

On background works well...
This is and example of the notification send:

```json
{
	"to":"token",
	"notification" : {
		"title":"Su requerimiento numero WSXQWE/2018 esta siento atendido",
		"body" : "Nuestras areas operativas estan trabajando en su requerimiento"
	},
 	"data":{
		"accion":"detalle_requerimiento",
		"data":17
	},
	"priority": "high"
}
```

**Comment by alacret** [comment]
+1

**Comment by nezaidu** [comment]
+1

**Comment by Lasherbr** [comment]
+1

**Comment by aaalive** [comment]
+1

**Comment by auchaphon** [comment]
+1

**Comment by auchaphon** [comment]
+1

**Comment by Salakar** [comment]
Unfortunately, this is an issue with Firebase and not this library specifically, even the Flutter SDK's are having the same issues: https://github.com/flutter/flutter/issues/19004

The suggested fix seems to be making sure the messaging SDK on Android is version `17.3.0` and above.

If that doesn't help I'd suggest raising an issue with Firebase directly or creating an issue on the Firebase Android SDK repo: https://github.com/firebase/firebase-android-sdk

Sorry 🙈

(please report back here with any updates)
