### ISSUE TITLE
java.lang.NoSuchMethodError: No static method getScreenWidthDp

### ISSUE THREAD

**Issue by km147** [invertase/react-native-firebase#1425]
### Issue

After implementing React Native Firebase I get the following error at runtime:

> java.lang.NoSuchMethodError: No static method getScreenWidthDp(Landroid/content/res/Resources;)I in class Landroid/support/v4/content/res/ConfigurationHelper; or its super classes (declaration of 'android.support.v4.content.res.ConfigurationHelper' appears in /data/app/app.gourmet-2/base.apk)
	at android.support.v7.view.ActionBarPolicy.getMaxActionButtons(ActionBarPolicy.java:57)
	at android.support.v7.widget.ActionMenuPresenter.initForMenu(ActionMenuPresenter.java:108)
	at android.support.v7.view.menu.MenuBuilder.addMenuPresenter(MenuBuilder.java:264)
	at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:655)
	at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:1037)
	at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:1008)
	at com.reactnativenavigation.views.TitleBar.setRightButtons(TitleBar.java:48)
	at com.reactnativenavigation.views.TopBar.addButtons(TopBar.java:93)
	at com.reactnativenavigation.views.TopBar.addTitleBarAndSetButtons(TopBar.java:75)
	at com.reactnativenavigation.screens.Screen.addTitleBarButtons(Screen.java:150)
	at com.reactnativenavigation.screens.Screen.createTitleBar(Screen.java:136)
	at com.reactnativenavigation.screens.Screen.createViews(Screen.java:123)
	at com.reactnativenavigation.screens.Screen.<init>(Screen.java:62)
	at com.reactnativenavigation.screens.SingleScreen.<init>(SingleScreen.java:16)
	at com.reactnativenavigation.screens.ScreenFactory.create(ScreenFactory.java:23)
	at com.reactnativenavigation.screens.ScreenStack.pushInitialScreen(ScreenStack.java:96)
	at com.reactnativenavigation.layouts.SingleScreenLayout.pushInitialScreen(SingleScreenLayout.java:92)
	at com.reactnativenavigation.layouts.SingleScreenLayout.createStack(SingleScreenLayout.java:87)
	at com.reactnativenavigation.layouts.SingleScreenLayout.createLayout(SingleScreenLayout.java:64)
	at com.reactnativenavigation.layouts.SingleScreenLayout.<init>(SingleScreenLayout.java:56)
	at com.reactnativenavigation.layouts.LayoutFactory.createSingleScreenLayout(LayoutFactory.java:20)
	at com.reactnativenavigation.layouts.LayoutFactory.create(LayoutFactory.java:15)
	at com.reactnativenavigation.controllers.NavigationActivity.createLayout(NavigationActivity.java:100)
	at com.reactnativenavigation.controllers.NavigationActivity.onCreate(NavigationActivity.java:81)
	at android.app.Activity.performCreate(Activity.java:6861)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2816)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6383)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)'

Doesn't seem to be specific to Firebase but only occurs when I add this library.

Not sure if its related or not but was originally I received this error compiling:

> The library com.google.firebase:firebase-iid is being requested by various other libraries at [[17.0.0,17.0.0]], but resolves to 16.2.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

But managed to hide this by adding the following to my android/app/build.gradle 
`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true` 

My build.gradle file is as follows:

```
buildscript {
    repositories {
        google()
        jcenter()        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

```
My app/build.gradle:

```
`apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]
apply from: "../../node_modules/react-native/react.gradle"

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialIcons.ttf', 'FontAwesome.ttf', 'Ionicons.ttf' ] 
]
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 26
     buildToolsVersion "26.0.1"

    defaultConfig {
        applicationId "app.example"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 4
        versionName "1.0.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('APP_RELEASE_STORE_FILE')) {
                storeFile file(APP_RELEASE_STORE_FILE)
                storePassword APP_RELEASE_STORE_PASSWORD
                keyAlias APP_RELEASE_KEY_ALIAS
                keyPassword APP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation  project(':react-native-firebase')
    implementation  fileTree(dir: "libs", include: ["*.jar"])
    implementation  "com.google.android.gms:play-services-wallet:+"
    implementation  'com.android.support:support-v4:24.1.1'
    implementation  'com.android.support:appcompat-v7:24.1.1'
    implementation  ("com.facebook.react:react-native:0.55.4") { force = true }  // From node_modules
    implementation  fileTree(dir: "libs", include: ["*.jar"])
    implementation  project(':react-native-navigation')
    implementation  project(':react-native-geocoder')
    implementation  project(':react-native-payments')
    implementation  project(':RNMail')
    implementation  project(':react-native-device-info')
    implementation(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:16.0.1"
    
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

```
### Environment

1. Application Target Platform:

Android

2. Development Operating System:

Windows 10

3. Build Tools:

Android Studio 3.1.3,
Android SDK 26

4. `React Native` version:

0.55.4

5. `React Native Firebase` Version:

4.3.0

6. `Firebase` Module:

Core

7. Are you using `typescript`?

No

**Comment by Ehesp** [comment]
There seem to be issues with `react-native-navigation` and how it modifies how RN 'works'. Related https://github.com/invertase/react-native-firebase/issues/1392

**Comment by Ehesp** [comment]
Please refer to https://github.com/invertase/react-native-firebase/issues/1484#issuecomment-420744669
