### ISSUE TITLE
removeAllDeliveredNotifications() throws SecurityException

### ISSUE THREAD

**Issue by phips28** [invertase/react-native-firebase#1495]
### Issue

I am receiving crash reports in crashlytics for Android:

```
Fatal Exception: java.lang.SecurityException: Package android does not belong to 10165
       at android.os.Parcel.readException(Parcel.java:1683)
       at android.os.Parcel.readException(Parcel.java:1636)
       at android.app.INotificationManager$Stub$Proxy.cancelAllNotifications(INotificationManager.java:794)
       at android.app.NotificationManager.cancelAll(NotificationManager.java:374)
       at io.invertase.firebase.notifications.RNFirebaseNotificationManager.removeAllDeliveredNotifications(RNFirebaseNotificationManager.java:190)
       at io.invertase.firebase.notifications.RNFirebaseNotifications.removeAllDeliveredNotifications(RNFirebaseNotifications.java:110)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:203)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:761)
```

### Environment

1. Application Target Platform:

*Android*
e.g.:
*Device*
Brand: AlcatelOneTouch
Model: 5049W
Orientation: Portrait
RAM free: 327.9 MB
Disk free: 3.89 GB
*Operating System*
Version: 7.0

2. Development Operating System:

MacOS High Sierra

3. Build Tools:

Android Studio 3.1.4
Build #AI-173.4907809, built on July 23, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.6
com.android.tools.build:gradle:3.1.4

4. `React Native` version:

"react-native": "^0.56.0",

5. `React Native Firebase` Version:

"react-native-firebase": "^4.3.8",

6. `Firebase` Module:

```
implementation "com.google.firebase:firebase-core:16.0.3"
implementation "com.google.android.gms:play-services-base:15.0.1"
// RNFirebase optional dependencies
implementation "com.google.firebase:firebase-analytics:16.0.3"
implementation "com.google.firebase:firebase-config:16.0.0"
implementation "com.google.firebase:firebase-messaging:17.3.1"
implementation "com.google.firebase:firebase-perf:16.1.0"
```

7. Are you using `typescript`?

no

**Comment by sunnyqin** [comment]
same issue

**Comment by LuisAlvarez12** [comment]
Any update to this?
