### ISSUE TITLE
java.lang.IllegalArgumentException: Given String is empty or null

### ISSUE THREAD

**Issue by oakis** [invertase/react-native-firebase#1597]
### Issue

I got a report from Fabric Crashlytics that one of my users got a crash. Sadly I do not know where my user was at the time or any connection to my JavaScript code.

Stacktrace from Crashlytics:
```
Fatal Exception: java.lang.IllegalArgumentException: Given String is empty or null
       at com.google.android.gms.common.internal.zzbq.zzgv(Unknown Source)
       at com.google.firebase.auth.EmailAuthProvider.getCredential(Unknown Source)
       at io.invertase.firebase.auth.RNFirebaseAuth.getCredentialForProvider(RNFirebaseAuth.java:1134)
       at io.invertase.firebase.auth.RNFirebaseAuth.link(RNFirebaseAuth.java:1000)
       at io.invertase.firebase.auth.RNFirebaseAuth.linkAndRetrieveDataWithCredential(RNFirebaseAuth.java:993)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:761)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:156)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:776)
```

### Environment

1. Application Target Platform:

    Android

2. Development Operating System:

    Windows 10

3. Build Tools:

    compileSdkVersion 27
    buildToolsVersion "27.0.3"

4. `React Native` version:

    0.55.3

5. `React Native Firebase` Version:

    4.0.5

6. `Firebase` Module:

    RNFirebaseAuth (from what I can see in the stacktrace)

7. Are you using `typescript`?

    No

**Comment by Salakar** [comment]
Hey @oakis, going by the stack trace I'd imagine this is around linking with an email & password credential via calling `firebase.auth().currentUser. linkAndRetrieveDataWithCredential(....)` in JS.

Could you show where you're using this method in your JS code, specifically around emails? My guess would be though that the email or password input from your user is blank/empty which is causing the crash - do you have any validations on this?

**Comment by oakis** [comment]
@Salakar: You were correct, I just tried registering with my app and it crashed. I'll add some validation.
Thank you! :)

**Comment by jimmy123A** [comment]
Is this issue fixed?

**Comment by mikehardy** [comment]
should be. if not please open new issue following template, ideally with self-contained App.js that reproduces if dropped in clean reproduction demonstration
https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
https://stackoverflow.com/help/minimal-reproducible-example

**Comment by kevinsiregar22** [comment]
Given String is empty or null can also when we register with createUserWithEmailAndPassword, we do not send the data that is in onchangetext, and the result will be Given String is empty or null. that's what I experienced when creatingUserWithEmailAndPassword with firebase. thank you hope it helps

**Comment by pulkit-singhall** [comment]
How did you solve this problem with createUserWithEmailAndPassword? I am facing the same problem.

**Comment by oakis** [comment]
> How did you solve this problem with createUserWithEmailAndPassword? I am facing the same problem.

Don´t run the function if email or password is empty. Add validation as stated above.

**Comment by YuriLima23** [comment]
Hello i have the "same problem" but is a function 
![image](https://github.com/invertase/react-native-firebase/assets/22965145/003306a3-cdc1-468d-9261-080862cd63f1)

the error bellow 
![image](https://github.com/invertase/react-native-firebase/assets/22965145/4cd2decb-e7f7-49b3-9009-a0e7df4fa8d8)


i checked the variable firebaseToken where is generate in Backend using firebase admin, end the data is comming but when try use this error above ocorrers

![image](https://github.com/invertase/react-native-firebase/assets/22965145/ad94f708-5adc-45d3-904e-d8a7817518b1)

intersting when installed app the the application close with error but after start application again and start is nomal withou error the error fired when installed app and try use this function
