### ISSUE TITLE
Can't run Android prject

### ISSUE THREAD

**Issue by orelzion** [invertase/react-native-firebase#184]
This is what I get
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;
    	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    	at com.android.dx.command.dexer.Main.run(Main.java:277)
    	at com.android.dx.command.dexer.Main.main(Main.java:245)
    	at com.android.dx.command.Main.main(Main.java:106)

**Comment by Salakar** [comment]
See the FAQs: http://invertase.io/react-native-firebase/#/faqs?id=android-duplicate-dex-files-error-build-time-error
