### ISSUE TITLE
Android crash on `  firebase.config().enableDeveloperMode();`

### ISSUE THREAD

**Issue by coulix** [invertase/react-native-firebase#1995]
## Issue

Android crash on `  firebase.config().enableDeveloperMode();`

```
2019-03-21 15:43:33.477 3629-3670/mobile.chefclub.App E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: mobile.chefclub.App, PID: 3629
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzfhm;
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(Unknown Source:0)
        at io.invertase.firebase.config.RNFirebaseRemoteConfig.enableDeveloperMode(RNFirebaseRemoteConfig.java:58)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzfhm" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/base.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_dependencies_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_resources_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_0_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_1_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_2_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_3_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_4_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_5_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_6_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_7_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_8_apk.apk", zip file "/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/lib/arm, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/base.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2019-03-21 15:43:33.480 3629-3670/mobile.chefclub.App E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 12 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/mobile.chefclub.App-VAbcxIemdF549LUwexpkaA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5761)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1653)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy

```
dependencies {
  implementation project(':react-native-firebase')
  implementation "com.google.firebase:firebase-core:16.+"
  implementation "com.google.firebase:firebase-messaging:17.3.4"
  implementation "com.google.firebase:firebase-auth:17.3.4"
  implementation "com.google.firebase:firebase-config:17.3.4"
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
...
  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        // new MainReactPackage(),
        new RNFirebasePackage(),
        new RNFirebaseMessagingPackage(),
        new RNFirebaseNotificationsPackage(),
        new RNFirebaseRemoteConfigPackage()
    );
  }
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - `ADD_SOMETHING_HERE` e.g. iOS 10 or Android API 28
- **Operating System:**
  - [ ] MacOS, version: `N/A`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - `ADD_SOMETHING_HERE` e.g. Xcode 10, Android Studio 3.2
- **`React Native` version:**
  - `ADD_SOMETHING_HERE`
- **`React Native Firebase` library version:**
  - `ADD_SOMETHING_HERE`
- **`Firebase` module(s) you're using that has the issue:**
  - [x] **N/A**
  - [ ] Authentication
  - [ ] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [x] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [ ] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [] No
  - [ ] Yes, I've _not_ ejected
  - [X] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by akiramouto** [comment]
i get error "could not invoke RNFirebaseRemoteConfig.enableDeveloperMode"
it is same problem here?

**Comment by mikehardy** [comment]
@akiramouto there is no such method any longer and has not been since react-native-firebase v9.x.x, v10 released breaking changes to align ourselves with the underlying native SDK APIs https://github.com/invertase/react-native-firebase/blob/master/packages/remote-config/CHANGELOG.md#1000-2020-11-10
