### ISSUE TITLE
Crashing with Remote JS Debugging Open

### ISSUE THREAD

**Issue by csumrell** [invertase/react-native-firebase#210]
Every time I try to use the chrome debugger the app will crash and then keep restarting and crashing. Disabling the debugger stops the crashes. The error log I found was:

FATAL EXCEPTION: mqt_js
                                                                            Process: com,  PID: 24401
                                                                            java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
                                                                                at com.learnium.RNDeviceInfo.RNDeviceModule.getConstants(RNDeviceModule.java:112)
                                                                                at com.facebook.react.cxxbridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:107)
                                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                                                at java.lang.Thread.run(Thread.java:761)
                                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.prestigeworldwide.keto-1/base.apk"],nativeLibraryDirectories=[/data/app/com.prestigeworldwide.keto-1/lib/arm, /system/fake-libs, /data/app/com.prestigeworldwide.keto-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                at com.learnium.RNDeviceInfo.RNDeviceModule.getConstants(RNDeviceModule.java:112) 
                                                                                at com.facebook.react.cxxbridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:107) 
                                                                                at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                at android.os.Handler.handleCallback(Handler.java:751) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208) 
                                                                                at java.lang.Thread.run(Thread.java:761)

**Comment by csumrell** [comment]
Adding

compile ("com.google.android.gms:play-services-gcm:11.0.0") {
        force = true;
    }

to my app/build dependencies seemed to fix this

**Comment by simonhintersonnleitner** [comment]
@csumrell Thanks, that works for me too.

**Comment by DavitVosk** [comment]
@csumrell Thanks a lot. You saved my day
