### ISSUE TITLE
"Failed to send notification" on Android only

### ISSUE THREAD

**Issue by chlec** [invertase/react-native-firebase#2159]
## Issue

Hello, I have an issue by sending notification on Android. For iOS everything works well, but I'm facing some issue on android.

When I send a notification, I check logs and I see that:
```
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: Failed to send notification
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at io.invertase.firebase.notifications.DisplayNotificationTask.getMainActivityClass(DisplayNotificationTask.java:578)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at io.invertase.firebase.notifications.DisplayNotificationTask.doInBackground(DisplayNotificationTask.java:67)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at io.invertase.firebase.notifications.DisplayNotificationTask.doInBackground(DisplayNotificationTask.java:33)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-23 14:39:14.742 30247 31082 E DisplayNotificationTask: 	at java.lang.Thread.run(Thread.java:764)

05-23 14:39:14.748 30247 30303 I ReactNativeJS: 'Notification Error', { [Error: Could not send notification]
05-23 14:39:14.748 30247 30303 I ReactNativeJS:   framesToPop: 1,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:   nativeStackAndroid:
05-23 14:39:14.748 30247 30303 I ReactNativeJS:    [ { methodName: 'getMainActivityClass',
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        lineNumber: 578,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        file: 'DisplayNotificationTask.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'doInBackground',
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        lineNumber: 67,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        file: 'DisplayNotificationTask.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'doInBackground',
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        lineNumber: 33,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        file: 'DisplayNotificationTask.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'call', lineNumber: 333, file: 'AsyncTask.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'run', lineNumber: 266, file: 'FutureTask.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'run', lineNumber: 245, file: 'AsyncTask.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'runWorker',
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        lineNumber: 1167,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        file: 'ThreadPoolExecutor.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'run',
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        lineNumber: 641,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:        file: 'ThreadPoolExecutor.java' },
05-23 14:39:14.748 30247 30303 I ReactNativeJS:      { methodName: 'run', lineNumber: 764, file: 'Thread.java' } ],
05-23 14:39:14.748 30247 30303 I ReactNativeJS:   userInfo: null,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:   code: 'notification/display_notification_error',
05-23 14:39:14.748 30247 30303 I ReactNativeJS:   line: 2106,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:   column: 26,
05-23 14:39:14.748 30247 30303 I ReactNativeJS:   sourceURL: 'http://localhost:8081/index.delta?platform=android&dev=true&minify=false' }
```

I don't know why... I followed many guides to set up notifications and I read many issues but nothing similar... Do you ever faced this problem?

I tried to add channel ID through AndroidManifest.xml file but nothing changed...

I send the notification like this:

```javascript
this.notificationListener = firebase.notifications().onNotification((notification) => {

	notification
		.android.setChannelId('my_channel')
		.android.setSmallIcon('ic_launcher')
		.android.setPriority(firebase.notifications.Android.Priority.Max)
		.setSound('default')

	firebase.notifications().displayNotification(notification).catch(err  =>  console.error('Notification Error', err));
})
```

Thank for your help. You can see my config below.

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 25
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
		google()
        jcenter()
    }
    dependencies {
		classpath 'com.android.tools.build:gradle:3.3.2'
		classpath 'com.google.gms:google-services:4.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            name "jitpack"
            url "https://jitpack.io"
        }
    }
    configurations {
    	all {
    		resolutionStrategy {
                force "android.arch.lifecycle:runtime:1.1.1"
                force "com.android.support:support-core-ui:28.0.0"
                force "com.android.support:appcompat-v7:28.0.0"
                force "com.google.code.findbugs:jsr305:1.3.9"
            }
    	}
    }
}

com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId 'com.my_project'
        minSdkVersion 25
        targetSdkVersion 28
        versionCode 3
        versionName "1.0.0"
        multiDexEnabled true
        renderscriptSupportModeEnabled true
        vectorDrawables.useSupportLibrary = true
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        }
        vectorDrawables {
            useSupportLibrary true
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    subprojects {
        project.configurations.all {
            afterEvaluate {project ->
                if (project.hasProperty("android")) {
                    android {
                        compileSdkVersion 28
                        buildToolsVersion '28.0.3'
                    }
                }
            }
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    productFlavors {
    }
}

dependencies {
    implementation project(':react-native-fast-image')
    implementation project(':react-native-video')
    implementation 'com.android.support:multidex:1.0.0'
    implementation project(':react-native-image-crop-picker')
    implementation project(':react-native-webview')
    implementation project(':react-native-languages')
    implementation project(':react-native-svg')
    implementation project(':react-native-firebase')
    implementation project(':react-native-image-resizer')
    implementation project(':react-native-vector-icons')
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:23.0.1'
    implementation 'com.facebook.react:react-native:+'
    // From node_modules
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.google.firebase:firebase-core:16.0.3'
    implementation 'com.google.firebase:firebase-messaging:17.5.0'
    implementation 'com.google.android.gms:play-services-base:15.0.0'
    implementation 'com.google.firebase:firebase-dynamic-links:16.1.7'
    implementation 'com.google.firebase:firebase-analytics'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'

com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'My Project'
include ':react-native-fast-image'
project(':react-native-fast-image').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fast-image/android')
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
include ':react-native-blur'
project(':react-native-blur').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-blur/android')
include ':react-native-image-crop-picker'
project(':react-native-image-crop-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-crop-picker/android')
include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
include ':react-native-languages'
project(':react-native-languages').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-languages/android')
include ':react-native-svg'
project(':react-native-svg').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-svg/android')
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
include ':react-native-image-resizer'
project(':react-native-image-resizer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-resizer/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')

include ':app'
```

#### `MainApplication.java`:

```java
package com.my_project;  
  
import android.app.Application;  
  
import com.facebook.react.ReactApplication;  
import com.dylanvann.fastimage.FastImageViewPackage;  
import com.brentvatne.react.ReactVideoPackage;  
import com.reactnative.ivpusic.imagepicker.PickerPackage;  
import com.reactnativecommunity.webview.RNCWebViewPackage;  
import com.reactcommunity.rnlanguages.RNLanguagesPackage;  
import com.horcrux.svg.SvgPackage;  
import io.invertase.firebase.RNFirebasePackage;  
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;  
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;  
import io.invertase.firebase.links.RNFirebaseLinksPackage;  
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;  
import fr.bamlab.rnimageresizer.ImageResizerPackage;  
import com.oblador.vectoricons.VectorIconsPackage;  
import com.facebook.react.ReactNativeHost;  
import com.facebook.react.ReactPackage;  
import com.facebook.react.shell.MainReactPackage;  
import com.facebook.soloader.SoLoader;  
  
import java.util.Arrays;  
import java.util.List;  
  
public class MainApplication extends Application implements ReactApplication {  
  
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {  
    @Override  
  public boolean getUseDeveloperSupport() {  
      return BuildConfig.DEBUG;  
  }  
  
    @Override  
  protected List<ReactPackage> getPackages() {  
      return Arrays.<ReactPackage>asList(  
         new MainReactPackage(),  
		 new FastImageViewPackage(),  
		 new ReactVideoPackage(),  
		 new PickerPackage(),  
		 new RNCWebViewPackage(),  
		 new RNLanguagesPackage(),  
		 new SvgPackage(),  
		 new RNFirebasePackage(),  
		 new RNFirebaseMessagingPackage(),  
		 new RNFirebaseNotificationsPackage(),  
		 new RNFirebaseLinksPackage(),  
		 new RNFirebaseAnalyticsPackage(),  
		 new ImageResizerPackage(),  
		 new VectorIconsPackage()  
      );  
  }  
  
    @Override  
  protected String getJSMainModuleName() {  
      return "index";  
  }  
  };  
  
  @Override  
  public ReactNativeHost getReactNativeHost() {  
    return mReactNativeHost;  
  }  
  
  @Override  
  public void onCreate() {  
    super.onCreate();  
  SoLoader.init(this, /* native exopackage */ false);  
  }  
}
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.my_project">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
    <uses-permission android:name="android.permission.READ_PROFILE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:usesCleartextTraffic="true">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:windowSoftInputMode="adjustPan"
          android:screenOrientation="portrait"
          android:launchMode="singleTop"
          >
        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.MAIN" />
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
        <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
        <receiver android:enabled="true" android:exported="true"  android:name="io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </receiver>
    </application>
</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 93.91 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.9.4 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.5 => 16.8.5
      react-native: ~0.59.4 => 0.59.5
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `Firebase Messaging`
- **Are you using `TypeScript`?**
  - `No`
  
</p>
</details>

**Comment by mikehardy** [comment]
Why did you omit your gradle files? I have no idea what version you are on

**Comment by mikehardy** [comment]
A neat trick though, open Android Studio, go to "Analyze" menu, and select "Analyze Stack Trace", then paste that in.

You will be directed to this chunk of code:
```java

  private Class getMainActivityClass(Context context) {
    String packageName = context.getPackageName();
    Intent launchIntent = context
      .getPackageManager()
      .getLaunchIntentForPackage(packageName);

    try {
      return Class.forName(launchIntent.getComponent().getClassName());
    } catch (ClassNotFoundException e) {
      Log.e(TAG, "Failed to get main activity class", e);
      return null;
    }
```

And since launchIntent is apparently null, I looked at the [`PackageManager.getLaunchIntentForPackage`](https://developer.android.com/reference/android/content/pm/PackageManager.html#getLaunchIntentForPackage(java.lang.String)) and it said:

```
Returns a "good" intent to launch a front-door activity in a package. This is used, 
for example, to implement an "open" button when browsing through packages. The 
current implementation looks first for a main activity in the category 
Intent#CATEGORY_INFO, and next for a main activity in the category 
Intent#CATEGORY_LAUNCHER. Returns null if neither are found.
```

So, check your AndroidManifest. You are missing something like this
https://github.com/invertase/react-native-firebase/blob/master/packages/template/project/android/app/src/main/AndroidManifest.xml#L20

**Comment by chlec** [comment]
Thanks for your answer.

I suspected the issue come from this piece of code, but I already have this line in my code:
```xml
<intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.MAIN" />
            <action android:name="android.intent.action.VIEW"/>
            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
```

I thought it was useless to set my gradle files, but I just updated the issue with them.

**Comment by mikehardy** [comment]
Very strange. All I can think of then is the app / package names or something. But it seems right. You might try taking what you're doing and putting it into the starter app to reproduce.

**Comment by chlec** [comment]
I still have this issue. But I forgot to tell that I'm only facing this issue in foreground. I get notification perfectly in background.

**Comment by chlec** [comment]
I managed to fix my issue.

I just had to set these two lines inside an isolated intent-filter:
```xml
<intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
```
