### ISSUE TITLE
Error when link react-native-firebase package

### ISSUE THREAD

**Issue by benhartouz** [invertase/react-native-firebase#2263]
## Issue

I want to link the package after the installation

```
react-native link react-native-firebase
```

---

**`react-native info` output:**

react-native info does not work either :(

```
/Users/macbook-pro/Documents/IZISYSTEM/izicheck/node_modules/@babel/traverse/node_modules/debug/src/debug.js:1
(function (exports, require, module, __filename, __dirname) { �
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/Users/macbook-pro/Documents/IZISYSTEM/izicheck/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/macbook-pro/Documents/IZISYSTEM/izicheck/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

**Comment by benhartouz** [comment]
its worked now, i installed the package using yarn instead of npm.

**Comment by DevelopSmith** [comment]
@benhartouz  Indeed, yarn worked for me. It throw an error in the terminal but it worked.
Thanks for the suggestion.
