### ISSUE TITLE
linking library not working

### ISSUE THREAD

**Issue by Dellybro** [invertase/react-native-firebase#2288]
## Issue

Describe your issue here

When running react-native link react-native-firebase errors are printed to terminal

```
react-native link react-native-firebase --verbose
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
error No package found. Are you sure this is a React Native project?
error Unexpected close tag
Line: 22
Column: 24
Char: >
debug Error: Unexpected close tag
Line: 22
Column: 24
Char: >
    at error (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/xmldoc/node_modules/sax/lib/sax.js:666:10)
    at strictFail (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/xmldoc/node_modules/sax/lib/sax.js:692:7)
    at closeTag (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/xmldoc/node_modules/sax/lib/sax.js:885:9)
    at SAXParser.write (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/xmldoc/node_modules/sax/lib/sax.js:1447:13)
    at new XmlDocument (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/xmldoc/lib/xmldoc.js:199:15)
    at readManifest (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/@react-native-community/cli/build/tools/android/readManifest.js:44:10)
    at Object.projectConfig (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/@react-native-community/cli/build/tools/android/index.js:66:46)
    at Object.keys.forEach.platform (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/@react-native-community/cli/build/commands/link/getProjectConfig.js:25:62)
    at Array.forEach (<anonymous>)
    at getProjectConfig (/Users/Dellybro/Desktop/Project/MyReactNativeApp/node_modules/@react-native-community/cli/build/commands/link/getProjectConfig.js:22:35)
```

**Comment by mikehardy** [comment]
“Please provide as much detail as possible to help us with a bug or issue. Issues are likely to be closed and locked if they do not follow the template.”
