### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by niteenach** [invertase/react-native-firebase#2384]
We are facing crashes in our app after sending push notification..It start occurring after sending notification with images using firebase console. Log in firebase for this issue says "notification_received"

Firebase SDK version : firebase-core:16.0.6 , firebase-messaging:17.6.0, react-native-firebase": "5.2.3

==============================================================
`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write + 1182(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read + 1221(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read + 65(RealBufferedSource.java:65)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read + 592(Http1xStream.java:592)
       at com.android.okhttp.internal.Util.skipAll + 170(Util.java:170)
       at com.android.okhttp.internal.Util.discard + 152(Util.java:152)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close + 609(Http1xStream.java:609)
       at com.android.okhttp.okio.RealBufferedSource.close + 421(RealBufferedSource.java:421)
       at com.android.okhttp.okio.RealBufferedSource$1.close + 409(RealBufferedSource.java:409)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(zzk.java:2)
       at com.google.firebase.messaging.zze.close(zze.java:2)
       at com.google.firebase.messaging.zzb.zzas(zzb.java:171)
       at com.google.firebase.messaging.FirebaseMessagingService.zzd(FirebaseMessagingService.java:387)
       at com.google.firebase.iid.zzb.run(zzb.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:7)
       at java.lang.Thread.run + 764(Thread.java:764)`

**Comment by mikehardy** [comment]
The template can't be ignored - it contains so much information necessary to help solve things

**Comment by niteenach** [comment]
@mikehardy Please let me know  about template that I need to include here

**Comment by mikehardy** [comment]
Sure thing - create a fresh issue, and in the textbox for the issue you will see a great deal of text asking for very specific information about your environment, your app, your code etc. You should treat it as an irritating but vital application for some sort of government services and fill out all the requested information ;-). I'm joking but seriously, that information is necessary to have a chance to figure out the problem.

**Comment by abhikulshrestha22** [comment]
@niteenach Hey man, did you find any solution for this?
