### ISSUE TITLE
How to avoid setup in ios when Testing React Native App?

### ISSUE THREAD

**Issue by anastely** [invertase/react-native-firebase#2441]
I have some issue with react-native-firebase, I have a **Windows environment** and I want to do a **Test** using Jest, So when I run an npm test I got Test suite **failed**

because react-native-firebase should be integration in ios , I just rename the File Android and unlink react-native-firebase to avoid these but it's not working for me! So how I Handle this if I don't have a **macOS**

---
### Test Code

```
import "react-native";
import React from "react";
import App from "../App";
import SignIn from "../src/screens/SignIn";

import renderer from "react-test-renderer";

it("renders correctly", () => {
  renderer.create(<App />);
});

test("renders correctly", () => {
  const tree = renderer.create(<SignIn />).toJSON();
  expect(tree).toMatchSnapshot();
});

```
 
### Test Result

```
 FAIL  __tests__/App.js
  ● Test suite failed to run

    RNFirebase core module was not found natively on iOS, ensure you have correctly included the RNFirebase pod in your projects `Podfile` and have run `pod install`.

     See http://invertase.link/ios for the ios setup guide.

      at new Firebase (node_modules/react-native-firebase/dist/modules/core/firebase.js:28:13)
      at Object.<anonymous> (node_modules/react-native-firebase/dist/modules/core/firebase.js:97:21)
      at Object.<anonymous> (node_modules/react-native-firebase/dist/index.js:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.52s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

## Environment
```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
      Memory: 2.77 GB / 7.88 GB
    Binaries:
      Yarn: 1.10.1 - C:\Users\{UserName}\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338```


- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both

- **`react-native-firebase :5.3.1`

**Comment by hmajid2301** [comment]
I have this issue running on Linux but also with Android.

**Comment by mikehardy** [comment]
You did not follow the full template so I am not sure what version you are using but I run jest on Linux all the time. I mock the native code out though

**Comment by anastely** [comment]
@mikehardy  version of what?

**Comment by mikehardy** [comment]
@anastely - sorry I was unclear, doing my best in airports etc on mobile. I was not sure what version of react-native-firebase was being used - @hmajid2301 edited his comment to add versions, so that’s good but I see yours is v5.3.x - I will confess I haven’t done anything with a version that old in a long time

I can say that in general native stuff is not going to work in a jest environment. You’ve got to mock things.

This is my jest.config.js:

```javascript
module.exports = {
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  transformIgnorePatterns: ['node_modules/(?!react-native|react-pose-core|animated-pose)'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  preset: 'react-native',
  testEnvironment: 'jsdom',
  collectCoverage: true,
  setupFilesAfterEnv: ['./__mocks__/mockFirebase.ts'],
};
```

and `__mocks__/mockFirebase.ts` looks like:
```javascript
/* eslint-disable no-undef */
jest.mock('react-native-firebase', () => ({
  messaging: jest.fn(() => ({
    hasPermission: jest.fn(() => Promise.resolve(true)),
    subscribeToTopic: jest.fn(),
    unsubscribeFromTopic: jest.fn(),
    requestPermission: jest.fn(() => Promise.resolve(true)),
    getToken: jest.fn(() => Promise.resolve('myMockToken')),
  })),
  notifications: jest.fn(() => ({
    onNotification: jest.fn(),
    onNotificationDisplayed: jest.fn(),
  })),
  analytics: jest.fn(() => ({
    logEvent: jest.fn(),
    setUserProperties: jest.fn(),
    setUserId: jest.fn(),
    setCurrentScreen: jest.fn(),
  })),
}));
```

I will say this was not easy for me to figure out, and I hope it helps you, but I don’t think this is a react-native-firebase issue at all - it should probably be closed…

**Comment by hmajid2301** [comment]
Thanks for the help Mike :).
