### ISSUE TITLE
[v6][jest +@ react-native-firebase/app] Native Module Can not be null

### ISSUE THREAD

**Issue by LBroy** [invertase/react-native-firebase#2475]
## Issue

Describe your issue here

I am trying to use jest + enzyme to test a component using firebase auth.
The result is below:
<img width="839" alt="Screen Shot 2019-08-10 at 11 10 18 PM" src="https://user-images.githubusercontent.com/12499472/62836079-a4721180-bc2d-11e9-9a17-09fbcef02baa.png">

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth/ios'
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 5.26 GB / 32.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 27, 28
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.2 AI-181.5540.7.32.5056338
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `@react-native-firebase/app 0.1.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/auth 0.1.2`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
So, jest and enzyme aren't running on an emulator right? How would native code work?

I mock out native stuff for jest

**Comment by LBroy** [comment]
> So, jest and enzyme aren't running on an emulator right? How would native code work?
> 
> I mock out native stuff for jest

So the problem here is that I should mock the native module. But I don't know how I should mock it. Should I mock the '@react-native-firebase/app'? If yes, can you give me a direction of how should I mock it?

**Comment by mikehardy** [comment]
not sure on v6, I'm still working on v5 until notifications is done on v6

for v5 I use a setup file from `setupFilesAfterEnv` array in jest.config.js that looks like this:

`more __mocks__/mockFirebase.ts`
```typescript
/* eslint-disable no-undef */
jest.mock('react-native-firebase', () => ({
  messaging: jest.fn(() => ({
    hasPermission: jest.fn(() => Promise.resolve(true)),
    subscribeToTopic: jest.fn(),
    unsubscribeFromTopic: jest.fn(),
    requestPermission: jest.fn(() => Promise.resolve(true)),
    getToken: jest.fn(() => Promise.resolve('myMockToken')),
  })),
  notifications: jest.fn(() => ({
    onNotification: jest.fn(),
    onNotificationDisplayed: jest.fn(),
  })),
  analytics: jest.fn(() => ({
    logEvent: jest.fn(),
    setUserProperties: jest.fn(),
    setUserId: jest.fn(),
    setCurrentScreen: jest.fn(),
  })),
}));
```

I haven't mocked auth, but it should be sort of like that, you'd specify the module, and inside of it mock things out?

**Comment by LBroy** [comment]
@mikehardy 

Thanks for the info. It is really helpful. Do you know where I can get help for the v6?

**Comment by mikehardy** [comment]
for mocking, I do not - but it should be the same style

**Comment by SiM07** [comment]
I use : 

```js
import analytics from "@react-native-firebase/analytics";

analytics().logEvent("add_to_cart", params);
```

And in mockFirebase.js

```js
jest.mock('@react-native-firebase/analytics', () => {
  analytics: jest.fn(() => ({
    logEvent: jest.fn(),
    setUserProperties: jest.fn(),
    setUserId: jest.fn(),
    setCurrentScreen: jest.fn(),
  }))
});
```

**Comment by jvandenaardweg** [comment]
@SiM07 one didn't work for me, as I was still getting `analytics_1.default is not a function`

This is what did it for me:

```javascript
jest.mock('@react-native-firebase/analytics', () => {
  return () => ({
    logEvent: jest.fn(),
    setUserProperties: jest.fn(),
    setUserId: jest.fn(),
    setCurrentScreen: jest.fn(),
  })
});
```

Hope it is useful for others!

**Comment by aliustaoglu** [comment]
I had to add this line into one of my setupFiles in jest. I couldn't get rid of `Native Module cannot be null` message without it.

```js
import { NativeModules } from 'react-native'
....
NativeModules.RNFBAppModule = {}
```

and after that since v6 all modules are separate, you have to mock all functions for each module separately.

```js
jest.mock('@react-native-firebase/analytics', () => {
  return () => ({
    logEvent: jest.fn(),
    setUserProperties: jest.fn(),
    setUserId: jest.fn(),
    setCurrentScreen: jest.fn()
  })
})

jest.mock('@react-native-firebase/crashlytics', () => {
  return () => ({
    recordError: jest.fn()
  })
})

// USE BELOW TEMPLATE TO MOCK OTHER MODULES
jest.mock('@react-native-firebase/ADD_OTHER_MODULES_YOU_USE', () => {
  return () => ({
    MOCK_EACH_FUNCTION: jest.fn()
  })
})
```

**Comment by nicolashemonic** [comment]
In my project with `"@react-native-firebase/analytics": "^6.1.0"` and `"jest": "^24.8.0"` I mock Analytics in `__mocks__/@react-native-firebase/analytics.js`.

```
export default {
    analytics: jest.fn(() => ({
        setUserId: jest.fn(),
        setUserProperties: jest.fn(),
        setCurrentScreen: jest.fn(),
        logEvent: jest.fn(),
    }))
};
```

There is no need of any extra configuration. https://jestjs.io/docs/en/manual-mocks#mocking-node-modules

I hope that help!

**Comment by ccanalesb** [comment]
Im still facing the issue 
Have in my `package.json`
```
    "@react-native-firebase/app": "^6.7.1",
    "@react-native-firebase/crashlytics": "^6.7.1",
    "@react-native-firebase/database": "^6.7.1",
    "@react-native-firebase/messaging": "^6.7.1",
```

in my setup-jest.js

```
jest.mock('@react-native-firebase/app');

jest.mock('react-native-notifications');

jest.mock('@react-native-firebase/database');

jest.mock('@react-native-firebase/crashlytics', () => () => ({
  recordError: jest.fn(),
  logEvent: jest.fn(),
  setUserProperties: jest.fn(),
  setUserId: jest.fn(),
  setCurrentScreen: jest.fn(),
}));


jest.mock('@react-native-firebase/messaging', () => () => ({
  hasPermission: jest.fn(() => Promise.resolve(true)),
  subscribeToTopic: jest.fn(),
  unsubscribeFromTopic: jest.fn(),
  requestPermission: jest.fn(() => Promise.resolve(true)),
  getToken: jest.fn(() => Promise.resolve('myMockToken')),
  onTokenRefresh: jest.fn((callback) => callback(Promise.resolve('Example'))),
}));
```

But im still getting 
```
  ● Test suite failed to run

    Invariant Violation: Native module cannot be null.

      at invariant (node_modules/invariant/invariant.js:40:15)
      at RNFBNativeEventEmitter.invariant (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:36:7)
      at new RNFBNativeEventEmitter (node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:24:5)
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/RNFBNativeEventEmitter.js:48:16)
      at Object.<anonymous> (node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js:21:1)
```

Idk what more mock

**Comment by diwgan32** [comment]
Also facing the same issue as @ccanalesb -- any guidance on how to mock `@react-native-firebase/app` on v6 would be appreciated!

**Comment by mikehardy** [comment]
I have this file listed as a setup file in jest config

`cat __mocks__/reactNativeFirebase.ts`:

```typescript
/* eslint-disable no-undef */
jest.mock('@react-native-firebase/app', () => ({
  messaging: jest.fn(() => ({
    hasPermission: jest.fn(() => Promise.resolve(true)),
    subscribeToTopic: jest.fn(),
    unsubscribeFromTopic: jest.fn(),
    requestPermission: jest.fn(() => Promise.resolve(true)),
    getToken: jest.fn(() => Promise.resolve('myMockToken')),
  })),
  notifications: jest.fn(() => ({
    onNotification: jest.fn(),
    onNotificationDisplayed: jest.fn(),
  })),
  analytics: jest.fn(() => ({
    logEvent: jest.fn(),
    setUserProperties: jest.fn(),
    setUserId: jest.fn(),
    setCurrentScreen: jest.fn(),
  })),
}));

// web mock
jest.mock('firebase/app', () => ({
  analytics: jest.fn(() => ({
    logEvent: jest.fn(),
  })),
}));
```

**Comment by soywod** [comment]
Mocking the Native Event Emitter did the trick for me:

```javascript
jest.mock("react-native/Libraries/EventEmitter/NativeEventEmitter");
```

**Comment by ulises-castro** [comment]
Hi there, in my case the solution was 

Mocking React's **NativeModules** inside of __ mock __/react-native.js file
```js
export const NativeModules = {
  RNFBAppModule: {}
} 
```

here my mocked file ( __ mock __/react-native.js)

```js
import * as ReactNative from "react-native";
export const alert = jest.fn();
export const Alert = { alert };

export const dimensionWidth = 100;
export const Dimensions = {
  get: jest.fn().mockReturnValue({ width: dimensionWidth, height: 100 })
};

export const Image = "Image";

export const keyboardDismiss = jest.fn();
export const Keyboard = {
  dismiss: keyboardDismiss
};

export const Platform = {
  ...ReactNative.Platform,
  OS: "ios",
  Version: 123,
  isTesting: true,
  select: objs => objs["ios"]
};

export const NativeModules = {
  RNFBAppModule: {}
}

export default Object.setPrototypeOf(
  {
    Alert,
    Dimensions,
    Image,
    NativeModules,
    Keyboard,
    Platform
  },
  ReactNative
)
```

**Comment by mikehardy** [comment]
@ulises-castro that's just one that you will need, here's our mock we use internally for jest teting: https://github.com/invertase/react-native-firebase/blob/master/jest.setup.ts

**Comment by pke** [comment]
Using this `__mock__/@react-native-firebase/messaging.ts`

```ts
export default jest.fn(() => ({
  hasPermission: jest.fn(() => Promise.resolve(true)),
  subscribeToTopic: jest.fn(),
  unsubscribeFromTopic: jest.fn(),
  requestPermission: jest.fn(() => Promise.resolve(true)),
  getToken: jest.fn(() => Promise.resolve("DEADBEADD00DE")),
}))
``` 

I can't properly override `getToken` from tests with a different implementation.

```ts
import messaging from "@react-native-firebase/messaging"

jest.spyOn(messaging(), "getToken").mockImplementation(() => {
  throw new Error("FIS_AUTH_ERROR")
})
```

I think thats because the implementation I want to test uses such code:

```ts
import messaging from "@react-native-firebase/messaging"

export function getDeviceToken() {
  return messaging()
    .requestPermission()
    .then(
      (enabled) => {
        logger.info("authState", enabled)
        return messaging().getToken()
      },
      (error) => {
        console.error(error)
        return undefined
      }
    )
}
```

So its calling `messaging()` too and this does seem to return the non-spied version of `getToken`.
