### ISSUE TITLE
Crash when running project

### ISSUE THREAD

**Issue by pbassut** [invertase/react-native-firebase#250]
When I try to run the project I get an immediate crash on startup.
### build.gradle file
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"]
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'
    defaultConfig {
        applicationId 'br.com.beebo'
        minSdkVersion 16
        targetSdkVersion 24
        versionCode versionMajor * 10000 + versionMinor * 100 + versionPatch
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            storeFile file(BEEBO_RELEASE_STORE_FILE)
            storePassword BEEBO_RELEASE_KEY_PASSWORD
            keyAlias BEEBO_RELEASE_KEY_ALIAS
            keyPassword BEEBO_RELEASE_KEY_PASSWORD
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    productFlavors {
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }
}

repositories {
    mavenCentral()
}

dependencies {

    compile project(':react-native-google-analytics-bridge')
    compile project(':react-native-firebase')
    compile project(':react-native-fbsdk')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
    compile 'com.facebook.android:facebook-android-sdk:[4,5)'

    compile "com.google.android.gms:play-services-base:11.0.1"
    compile 'com.google.android.gms:play-services-location:11.0.1'
    compile 'com.google.android.gms:play-services-maps:11.0.1'
    compile "com.google.firebase:firebase-core:11.0.1"
    compile "com.google.firebase:firebase-config:11.0.1"
    compile "com.google.firebase:firebase-auth:11.0.1"
    compile "com.google.firebase:firebase-analytics:11.0.1"
    compile "com.google.firebase:firebase-messaging:11.0.1"
    compile "com.google.firebase:firebase-crash:11.0.1"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

### Environment

1. Target Platform (e.g. iOS, Android): Android
2. Development Operating System (e.g. macOS Sierra, Windows 10): macOS Sierra
3. Build tools (Xcode or Android Studio version, iOS or Android SDK version, if relevant):
4. React Native version (e.g. 0.45.1): 0.44.1 
5. RNFirebase Version (e.g. 2.0.2): 2.0.2

### Stacktrace
```
07-13 23:17:55.666 16800 16800 E AndroidRuntime: FATAL EXCEPTION: main
07-13 23:17:55.666 16800 16800 E AndroidRuntime: Process: br.com.beebo, PID: 16800
07-13 23:17:55.666 16800 16800 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbr; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbr' appears in /data/app/br.com.beebo-x_r0PAnn-uTBkZhXPIVSuA==/split_lib_dependencies_apk.apk:classes26.dex)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at com.google.firebase.perf.provider.FirebasePerfProvider.attachInfo(Unknown Source:3)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6284)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5850)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5771)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6540)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-13 23:17:55.666 16800 16800 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-13 23:17:55.678  1486  1497 W ActivityManager:   Force finishing activity br.com.beebo/.MainActivity
```

**Comment by Salakar** [comment]
Could you try changing:

```gradle
compile project(':react-native-firebase')
```

#### To:
```gradle
 compile(project(':react-native-firebase')) {
    transitive = false
 }
```

And see if that builds now?

**Comment by pbassut** [comment]
Yes! Thanks @Salakar

**Comment by Ehesp** [comment]
Don't want to be that guy, but that is in the docs!

**Comment by pbassut** [comment]
It did build. But I'm still gettin a crash.
Will bring more info soon.

Enviado do meu iPhone

Em 18 de jul de 2017, às 04:32, Elliot Hesp <notifications@github.com<mailto:notifications@github.com>> escreveu:


Don't want to be that guy, but that is in the docs!

**Comment by pbassut** [comment]
Still getting a crash but for a different thing now. I'm not sure if that's caused by adding the `transitive = false` or it was already there. 
This is the error I'm getting:
```
![image](https://user-images.githubusercontent.com/1500037/28320625-70c05352-6ba7-11e7-9159-2c3e52f83fba.png)
```

This is ultimately because `NativeModules.RNFirebaseMessaging` is undefined.

Why would this be undefined?

**Comment by chrisbianca** [comment]
Have you followed the instructions and added `new RNFirebaseMessagingPackage()` to your MainApplication.java? See here: http://invertase.io/react-native-firebase/#/installation-android?id=_2-link-rnfirebase

**Comment by pbassut** [comment]
@chrisbianca I did follow the instructions once. It was working. This seems to be the result of an version upgrade. The setup changed maybe?

Now I see I'm not registering some packages.

**Comment by chrisbianca** [comment]
The setup did change as part of the v2 changes which we covered in the migration guide: http://invertase.io/react-native-firebase/#/migration-guide

**Comment by pbassut** [comment]
Yeah. My fault to do a blind upgrade to a new major version without checking for breaking changes.

**Comment by chrisbianca** [comment]
No problem, glad you've got it all sorted now
