### ISSUE TITLE
Dynamic links in 5.5.6 on Android crashes: requires com.google.firebase:firebase-invites:17.0.0: docs inaccurate?

### ISSUE THREAD

**Issue by pxpeterxu** [invertase/react-native-firebase#2528]
## Issue

When opening an Android app from a Firebase Dynamic Link (after the app is already installed), the app crashes due to the lack of `com.google.firebase.appinvite.FirebaseAppInvite` package:

Stack trace from `adb logcat`:

```
08-28 09:02:26.030 14675 14675 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/appinvite/FirebaseAppInvite;
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at io.invertase.firebase.links.RNFirebaseLinks.isInvitation(RNFirebaseLinks.java:207)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at io.invertase.firebase.links.RNFirebaseLinks.access$100(RNFirebaseLinks.java:29)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at io.invertase.firebase.links.RNFirebaseLinks$3.onSuccess(RNFirebaseLinks.java:124)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at io.invertase.firebase.links.RNFirebaseLinks$3.onSuccess(RNFirebaseLinks.java:120)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.appinvite.FirebaseAppInvite" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.wanderlog.android-fHCZ9CxaD4ptuJGRmRYUsQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.wanderlog.android-fHCZ9CxaD4ptuJGRmRYUsQ==/lib/arm64, /data/app/com.wanderlog.android-fHCZ9CxaD4ptuJGRmRYUsQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-28 09:02:26.030 14675 14675 E AndroidRuntime: 	... 12 more
```

Code within `react-native`:

```tsx
export default class App extends React.PureComponent<{}, State> {
  constructor(props: {}) {
    super(props);
    this.initializeLinking();
  }

  async initializeLinking() {
    firebase.links().onLink(this.handleUrlChange);
    const firebaseInitialUrl = await firebase.links().getInitialLink();

    Alert.alert(
      'Initial URLs',
      JSON.stringify({ firebaseInitialUrl }),
    );
  }

  handleUrlChange = (url: string) => { console.log(url); }
}
```

## Solution

I solved this by adding one line to my `android/app/build.gradle` for the library:

```groovy
implementation "com.google.firebase:firebase-invites:17.0.0"
```

Full excerpt:

```groovy
    // Added from https://rnfirebase.io/docs/v5.x.x/installation/android#3.-Add-Firebase-modules
    implementation project(':react-native-firebase')

    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"

    // Added from https://rnfirebase.io/docs/v5.x.x/links/android#Add-the-dependency
    implementation "com.google.firebase:firebase-dynamic-links:17.0.0"

    // Added to fix problem:
    implementation "com.google.firebase:firebase-invites:17.0.0"
```

Should the documentation be updated for `react-native-firebase` here? https://rnfirebase.io/docs/v5.x.x/links/android#Add-the-dependency

---

### iOS

Not really relevant, since the issue only happens on Android

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [X] my application is an AndroidX application?
- [X] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [X] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21 // Changed to 21 for https://github.com/unimodules/react-native-unimodules/tree/af49eb66d9db79da76937f129b4120846037d3e2#configure-android
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        // Added from https://rnfirebase.io/docs/v5.x.x/installation/android#2.-Setup-google-services.json
        classpath("com.google.gms:google-services:4.2.0")
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
    }
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

// Added from https://github.com/unimodules/react-native-unimodules/tree/af49eb66d9db79da76937f129b4120846037d3e2#configure-android
apply from: '../../node_modules/react-native-unimodules/gradle.groovy'

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.wanderlog.android"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"

        // Start added from https://github.com/ConduitMobileRND/react-native-simple-shadow-view
        // and https://developer.android.com/guide/topics/renderscript/compute#ide-setup
        renderscriptTargetApi 18
        renderscriptSupportModeEnabled true
        // End added
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        // Start added from https://facebook.github.io/react-native/docs/signed-apk-android#adding-signing-config-to-your-app-s-gradle-config
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
        // End added
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Changed based on https://facebook.github.io/react-native/docs/signed-apk-android#adding-signing-config-to-your-app-s-gradle-config
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
    // Added from https://rnfirebase.io/docs/v5.x.x/installation/android#3.-Add-Firebase-modules
    implementation project(':react-native-firebase')

    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.9"

    // Added from https://rnfirebase.io/docs/v5.x.x/links/android#Add-the-dependency
    implementation "com.google.firebase:firebase-dynamic-links:17.0.0"

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    // Added to fix react-native-google-signin from https://stackoverflow.com/a/54979149/319066
    implementation "androidx.appcompat:appcompat:1.1.0-rc01"

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }

    // Added from https://github.com/unimodules/react-native-unimodules/tree/af49eb66d9db79da76937f129b4120846037d3e2#configure-android
    addUnimodulesDependencies()
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

// Added from https://rnfirebase.io/docs/v5.x.x/installation/android#2.-Setup-google-services.json
apply plugin: 'com.google.gms.google-services'

```

#### `android/settings.gradle`:
// Start added from `react-native link react-native-firebase`
include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')
// End added

// Start added from https://github.com/facebook/react-native-fbsdk/tree/6d153bdd56533af330c46cd78e3b1b8f80893ed5#31-android
include ':react-native-fbsdk'
project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')
// End added

// Start added from https://github.com/unimodules/react-native-unimodules/tree/af49eb66d9db79da76937f129b4120846037d3e2#configure-android
apply from: '../node_modules/react-native-unimodules/gradle.groovy'
includeUnimodulesProjects()
// End added

rootProject.name = 'travelchime'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
package com.wanderlog.android;

import android.app.Application;
import android.util.Log;
import android.webkit.WebView;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;

// Start added from `react-native link react-native-firebase`
import io.invertase.firebase.RNFirebasePackage;
// End added

import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

// Start added from https://rnfirebase.io/docs/v5.x.x/links/android#Install-the-RNFirebase-Links-package
import io.invertase.firebase.links.RNFirebaseLinksPackage;
// End added

// Start added from https://github.com/unimodules/react-native-unimodules/tree/af49eb66d9db79da76937f129b4120846037d3e2#configure-android
import com.wanderlog.android.generated.BasePackageList;

import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;
import org.unimodules.core.interfaces.SingletonModule;
// End added

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {
  // Added from https://github.com/unimodules/react-native-unimodules/tree/af49eb66d9db79da76937f129b4120846037d3e2#configure-android
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), Arrays.<SingletonModule>asList());

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:

      // Added from https://github.com/unimodules/react-native-unimodules/tree/af49eb66d9db79da76937f129b4120846037d3e2#configure-android
      packages.add(new ModuleRegistryAdapter(mModuleRegistryProvider));

      // Added from https://rnfirebase.io/docs/v5.x.x/links/android#Install-the-RNFirebase-Links-package
      packages.add(new RNFirebaseLinksPackage());

      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    WebView.setWebContentsDebuggingEnabled(true);
  }
}
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 228.55 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.1 - ~/.nvm/versions/node/v10.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.1
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [X] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 5.5.6
- **`Firebase` module(s) you're using that has the issue:**
  - Dynamic links
- **Are you using `TypeScript`?**
  - Yes
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by pxpeterxu** [comment]
This has been fixed! Closing

**Comment by appli-intramuros** [comment]
Still have the issue with RN firebase 5.6.0 ...

**Comment by pxpeterxu** [comment]
To be clear, this was fixed in the sense that you still need to separately add the invites in `android/app/build.gradle`.

Make sure you follow the full instructions here:

https://rnfirebase.io/docs/v5.x.x/links/android

**Comment by appli-intramuros** [comment]
Ok thanks @pxpeterxu
