### ISSUE TITLE
analytics cause app crashing on android

### ISSUE THREAD

**Issue by jsina** [invertase/react-native-firebase#2754]
after I've added `@react-native-firebase/analytics` my app was crashed. although app compiled correctly but when app is opened it's crashed.
btw it's gonna work on iOS.
here is my `adb logcat`:
```10-20 21:03:09.377 15103 15103 E AndroidRuntime: Process: com.hitalent.hitalent, PID: 15103
10-20 21:03:09.377 15103 15103 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.hitalent.hitalent.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.hitalent.hitalent.MainApplication" on path: DexPathList[[zip file "/data/app/com.hitalent.hitalent-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hitalent.hitalent-1/lib/arm, /data/app/com.hitalent.hitalent-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:676)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6289)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:221)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7224)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.hitalent.hitalent.MainApplication" on path: DexPathList[[zip file "/data/app/com.hitalent.hitalent-1/base.apk"],nativeLibraryDirectories=[/data/app/com.hitalent.hitalent-1/lib/arm, /data/app/com.hitalent.hitalent-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1004)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:666)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	... 9 more
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.hitalent.hitalent.MainApplication
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 		... 12 more
10-20 21:03:09.377 15103 15103 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
10-20 21:03:09.442  4072 15118 E android.os.Debug: ro.product_ship = true
```
my package analytics and firebase versions are:
```
    "@react-native-firebase/analytics": "^6.0.2",
    "@react-native-firebase/app": "^6.0.2",
```
here is my react-native info:
```
System:
    OS: macOS Mojave 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 65.41 MB / 8.00 GB
    Shell: 2.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.16.0 - ~/.config/fnm/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.11.3 - ~/.config/fnm/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 16, 21, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.1, 28.0.3
      System Images: a...ult | ARM EABI v7a, a...-21 | Intel x86 Atom, a... | Intel x86 Atom_64
  IDEs:
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

**Comment by mikehardy** [comment]
Hi there, you didn't follow the template. So I don't know what your MainApplication looks like.

You didn't indicate what API you had problems with, but it smells like it could be a MultiDex problem. You'd enable it like these lines do  https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L136 

But this might be even more basic. If you'd included your AndroidManifest.xml we could see if it specifies the right class

**Comment by jsina** [comment]
thank for your response @mikehardy btw because I'm using `react-native-navigation` and this package have some conflict with multidex I've decrease app with this workaround:
android/build.gradle
```
...
subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion

                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (
                        names.contains("reactNative51") ||
                        names.contains("reactNative55") ||
                        names.contains("reactNative56") ||
                        names.contains("reactNative57") ||
                        names.contains("reactNative57_5")
                    ) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}
```
https://github.com/wix/react-native-navigation/issues/5273#issuecomment-510328273

**Comment by mikehardy** [comment]
still not following template
still smells like a multidex failure
I'm unaware of "conflicts with multidex", but I know it's possible to use multidex with react-native-navigation:

https://github.com/facebook/react-native/issues/15594#issuecomment-379237133
