### ISSUE TITLE
Firestore doesn't work on real android device.

### ISSUE THREAD

**Issue by kysonic** [invertase/react-native-firebase#2849]
(:fire:)(:fire:)(:fire:)

## Issue

My application breaks when I try to run any firestore method. Code snippet: 

```
import firestore from '@react-native-firebase/firestore';

const getUsers = async () => {
    const querySnapshot = await firestore()
        .collection('users')
        .get();

    console.log('Total users', querySnapshot.size);
    console.log('User Documents', querySnapshot.docs);
}

getUsers();
```
There were no errors in react's console, but I found the error via `adb logcat`. 

```
11-09 19:30:44.304 25172 25172 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to gain exclusive lock to the Firestore client's offline persistence. This generally means you are using Firestore from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing Firestore in your Application class. If you are intentionally using Firestore from multiple processes, you can only enable offline persistence (i.e. call setPersistenceEnabled(true)) in one of them.
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.local.SQLitePersistence.start(com.google.firebase:firebase-firestore@@20.2.0:128)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@20.2.0:254)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@20.2.0:117)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run(Unknown Source)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4(com.google.firebase:firebase-firestore@@20.2.0:311)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call(Unknown Source)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@20.2.0:287)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	... 8 more
11-09 19:30:44.304 25172 25172 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:569)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:549)
11-09 19:30:44.304 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:460)
11-09 19:30:44.305 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:390)
11-09 19:30:44.305 25172 25172 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
11-09 19:30:44.305 25172 25172 E AndroidRuntime: 	at com.google.firebase.firestore.local.SQLitePersistence.start(com.google.firebase:firebase-firestore@@20.2.0:125)
11-09 19:30:44.305 25172 25172 E AndroidRuntime: 	... 14 more

```

Seems the database is locked for some reason. It happens only for my real device (Black Shark [Android]) connected via USB cable. It works well for Android and iOS emulators.

**Comment by mikehardy** [comment]
That error message seems extremely detailed. Please confirm you have examine what it implies and the implied changes

**Comment by kysonic** [comment]
Seems it's related only to local device storage. I've switched local persistence off and now it's working well. 

```
await firestore().settings({
        persistence: false
});
```

But anyway it's not so good result because I wanted to save data on local devices as well.
