### ISSUE TITLE
Could not determine the dependencies of task ':@react-native-firebase_database:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by W8jonas** [invertase/react-native-firebase#2852]
## Issue
hello everyone, my issue is this:
I can do react-native run-android and the apps it's ok, but i can't  assembleRelease my app. I get this error below: 

Could not determine the dependencies of task ':@react-native-firebase_database:compileReleaseJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':@react-native-firebase_database:releaseCompileClasspath'.
   > Could not resolve project :@react-native-firebase_app.
     Required by:
         project :@react-native-firebase_database
      > Unable to find a matching configuration of project :@react-native-firebase_app: None of the consumable configurations have attributes.
---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x ] my application is an AndroidX application
- [x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
projects/modules.
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'com.google.gms:google-services:4.2.0' // 4.2.0  4.0.1
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

```

#### `android/app/build.gradle`:

```groovy
apply plugin: 'com.android.application'

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"


def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.learni"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-google-signin')
    implementation project(':react-native-firebase')
    
    implementation project(path: ":@react-native-firebase_app")
    implementation project(':@react-native-firebase_database')

    compile(project(':react-native-firebase')) {   
        transitive = false
    }
    
    implementation project(':@react-native-community_async-storage')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    
    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "com.google.android.gms:play-services-auth:16.0.0"
    
    // Firebase dependencies

    implementation 'com.google.firebase:firebase-iid:18.0.0'

    implementation "com.google.firebase:firebase-core:17.2.1"
    implementation "com.google.firebase:firebase-auth:19.1.0"        //19.1.0" 16.1.0
    implementation "com.google.firebase:firebase-messaging:18.0.0"   // 15.0.2 17.3.4  17.1.2.
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar'

    implementation 'com.google.firebase:firebase-database:17.0.0'
}


// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'

googleServices {
    disableVersionCheck = true
}
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'LearnI'

include ':@react-native-community_async-storage'
project(':@react-native-community_async-storage').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/async-storage/android')

include ':react-native-google-signin'
project(':react-native-google-signin').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-google-signin/android')

include ':@react-native-firebase_app'
project(':@react-native-firebase_app').projectDir = new File(rootProject.projectDir, './../node_modules/@react-native-firebase/app/android')

include ':react-native-firebase'
project(':react-native-firebase').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-firebase/android')

include ':@react-native-firebase_database'
project(':@react-native-firebase_database').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-firebase/database/android')


include ':app'

```

#### `MainApplication.java`:

```java
package com.learni;
import android.app.Application;

import com.facebook.react.ReactApplication;
import io.invertase.firebase.database.RNFirebaseDatabasePackage;
import co.apptailor.googlesignin.RNGoogleSigninPackage;

import io.invertase.firebase.app.RNFirebaseAppPackage;
import io.invertase.firebase.RNFirebasePackage;

import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;

import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNFirebaseAppPackage(),
            new RNFirebaseDatabasePackage(),
            new RNGoogleSigninPackage(),
            new RNFirebasePackage(),
            new RNFirebaseAuthPackage(),
            new AsyncStoragePackage(),
            new RNFirebaseNotificationsPackage(),
            new RNFirebaseMessagingPackage()

      );
    }
    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };
  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }
  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.learni">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>

    </application>

</manifest>

```
#### `Package.json`:

```xml
{
  "name": "LearnI",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "1.6.1",
    "@react-native-firebase/database": "6.0.3",
    "moment": "2.24.0",
    "react": "16.8.3",
    "react-native": "0.59.4",
    "react-native-calendars": "1.205.0",
    "react-native-firebase": "5.5.6",
    "react-native-google-signin": "1.0.0",
    "react-native-material-dropdown": "0.11.1",
    "react-navigation": "2.7.0",
    "react-redux": "5.0.7",
    "redux": "4.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.5.5",
    "@babel/runtime": "7.5.5",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "0.55.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}


```
</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
      Memory: 1.43 GB / 7.95 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5264788
```

- **Platform that you're experiencing the issue on**:
  - [x] Android

- **Are you using `TypeScript`?**
  - `N` 
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by chrisparton1991** [comment]
I had this same issue.

I had `implementation project(':react-native-firebase')` inside my `app/build.gradle`. Removing that did the job for me.

I started following the v5 setup guide before realising it was outdated, and forgot to remove that line after manually linking the library.

**Comment by mehraj43** [comment]
Hii im getting error when tyring to build my app i'm trying to firebase twitter login i have installed and followed the proper config steps plzz help me 
im getting this error

BUILD FAILED in 17s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.
     Required by:
         project :app > project :react-native-twitter-signin_twitter-signin

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 17s

    at makeError (C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16       
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

**Comment by mehraj43** [comment]
after cleaning graddle im getting this error now:

BUILD FAILED in 19s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.twitter.sdk.android:twitter-core:3.3.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/twitter/sdk/android/twitter-core/3.3.0/twitter-core-3.3.0.pom
    at makeError (C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16           at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\mehra\OneDrive\Desktop\React_Native_Practise\FirstProj\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
