### ISSUE TITLE
Error: Could not load the default credentials. - Cloud Functions

### ISSUE THREAD

**Issue by yash1511** [invertase/react-native-firebase#2951]
## Issue
I'm working on the group functionality for my react-native app. And I wish to send cloud messages to users who have been added when a group is created. I'm using cloud functions to do that.

But I am getting this error in my function:
```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/srv/node_modules/google-auth-library/build/src/auth/googleauth.js:161:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

![image](https://user-images.githubusercontent.com/44857776/69914525-c3e3b300-1445-11ea-91de-27fbd9f892ae.png)
Its unable to fetch the fcm-token from firestore to send the notification.

I had written cloud functions for sending friend requests and in that, the token is retrieved successfully from cloud firestore, and the notification is sent.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `functions/index.js`:

```javascript
//My cloud function:
//======================NOTIFY ADDED MEMBERS==========================//

exports.notifyAddedMembers = functions.https.onCall((data, context) => {
  const members = data.members;
  const groupName = data.groupName;
  var tokens = [];
  members.forEach(async member => {
    //send notifications to member.uid
    console.log('MEMBER.UID ', member.uid);
    await fetchTokenFromUid(member.uid)
      .then(token => {
        console.log('retrieved token: ', token);
        // tokens.push(token);
        const payload = {
          notification: {
            title: `You have been added to ${groupName}`,
            body: 'Share your tasks',
            sound: 'default',
          },
        };
        return admin.messaging().sendToDevice(token, payload);
      })
      .catch(err => console.log('err getting token', err));
  });
  // console.log('ALL TOKENS: ', tokens);
  console.log('GROUP NAME: ', groupName);
});

async function fetchTokenFromUid(uid) {
  var token = '';
  return await admin
    .firestore()
    .collection('Users')
    .doc(`${uid}`)
    .get()
    .then(async doc => {
      console.log('uid token: ', Object.keys(doc.data().fcmTokens));
      var tokenArray = Object.keys(doc.data().fcmTokens); //ARRAY
      for (var i = 0; i < tokenArray.length; i++) {
        token = tokenArray[i]; //Coverts array to string
      }
      return token; //return token as string
    });
}
```

**Comment by mikehardy** [comment]
1- do not post images, please post the actual text of all things
2- you did not follow the template :-(, no idea what state your project is in, what versions etc
