### ISSUE TITLE
:fire: Adding Performance Monitoring Crashes my App

### ISSUE THREAD

**Issue by hmajid2301** [invertase/react-native-firebase#3037]
## Issue

Describe your issue here

I have setup my app as explained in the quick guide, I've also managed to setup firebase analytics. However when I ever I `yarn add @react-native-firebase/perf` it crashes my app, even if i remove analytics and use only performance motioning.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "stegappasaurus",
  "scripts": {
    "android": "react-native run-android",
    "build-package": "cd android && ./gradlew bundleRelease --no-daemon",
    "bundle": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.bundle --sourcemap-output android/app/src/main/assets/index.map --assets-dest android/app/src/main/res && rm -r android/app/src/main/res/drawable-*",
    "clean-build": "cd android && ./gradlew clean",
    "clean-tests": "yarn tests -u",
    "code-formatter": "prettier src/**/*.{ts,tx,tsx} --write",
    "code-formatter-check": "prettier --check src/**/*.{ts,tx,tsx}",
    "coverage": "jest --coverage",
    "generate-dotenv": "sh util/generate-dotenv.sh > .env",
    "generate-gradle-properties": "sh util/generate-gradle-properties.sh > android/gradle.properties",
    "generate-licenses": "npm-license-crawler -onlyDirectDependencies --omitVersion -json src/data/licenses.json",
    "log": "react-native log-android",
    "lint": "tslint src/**/*.{ts,tx,tsx} -c tslint.json",
    "publish-package": "cd android && ./gradlew publishRelease",
    "start": "react-native start",
    "tests": "jest",
    "types-check": "tsc --project . --noEmit --pretty --skipLibCheck",
    "watch-tests": " jest --watch"
  },
  "dependencies": {
    "@react-native-community/async-storage": "1.6.2",
    "@react-native-community/cameraroll": "1.2.1",
    "@react-native-firebase/analytics": "6.2.0",
    "@react-native-firebase/app": "6.2.0",
    "@testing-library/react-native": "5.0.3",
    "bugsnag-react-native": "2.23.1",
    "lzutf8": "0.5.5",
    "react": "16.9.0",
    "react-native": "0.61.1",
    "react-native-app-intro-slider": "3.0.0",
    "react-native-appearance": "0.3.1",
    "react-native-circular-progress": "1.3.4",
    "react-native-collapsible": "1.4.0",
    "react-native-config": "0.11.7",
    "react-native-elements": "1.2.6",
    "react-native-gesture-handler": "1.4.1",
    "react-native-image-picker": "1.1.0",
    "react-native-markdown-renderer": "3.2.8",
    "react-native-navbar-color": "1.0.3",
    "react-native-navigation-bar-color": "^1.0.0",
    "react-native-permissions": "2.0.2",
    "react-native-rate": "1.1.6",
    "react-native-reanimated": "1.3.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-share": "2.0.0",
    "react-native-snackbar": "2.0.3",
    "react-native-splash-screen": "3.2.0",
    "react-native-svg": "9.13.3",
    "react-native-vector-icons": "6.6.0",
    "react-navigation": "4.0.10",
    "react-navigation-stack": "1.10.2",
    "react-navigation-tabs": "2.5.6",
    "rn-fetch-blob": "0.11.2",
    "stream": "0.0.2",
    "varint": "5.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.6.2",
    "@babel/runtime": "7.6.2",
    "@testing-library/jest-native": "3.1.0",
    "@types/jest": "24.0.15",
    "@types/jsdom": "12.2.4",
    "@types/react": "16.9.9",
    "@types/react-dom": "16.8.5",
    "@types/react-native": "0.60.21",
    "@types/react-native-app-intro-slider": "3.0.0",
    "@types/react-native-share": "1.1.2",
    "@types/react-navigation": "3.0.5",
    "@types/react-test-renderer": "16.8.2",
    "@types/varint": "5.0.0",
    "babel-plugin-module-resolver": "3.2.0",
    "jest": "24.9.0",
    "jest-fetch-mock": "2.1.2",
    "jest-react-native": "18.0.0",
    "jsdom": "15.1.1",
    "metro-react-native-babel-preset": "0.54.0",
    "mock-async-storage": "2.2.0",
    "npm-license-crawler": "0.2.1",
    "prettier": "1.19.1",
    "react-dom": "16.8.6",
    "react-native-bundle-visualizer": "^2.0.4",
    "react-native-mock-render": "0.1.5",
    "react-test-renderer": "16.9.0",
    "ts-jest": "24.0.2",
    "tslib": "1.9.3",
    "tslint": "5.20.0",
    "tslint-config-prettier": "1.18.0",
    "tslint-config-standard": "8.0.1",
    "tslint-react": "4.0.0",
    "typescript": "3.7.2"
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
        maven {
            url "https://maven.fabric.io/public"
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:3.5.0"
        classpath "com.github.triplet.gradle:play-publisher:2.4.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50"
        classpath 'com.google.gms:google-services:4.2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        google()
        jcenter()
    }
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"
apply plugin: "com.github.triplet.play"
apply plugin: "kotlin-android"
apply plugin: "kotlin-android-extensions"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         "bundleIn${productFlavor}${buildType}"
 *   //         "bundleIn${buildType}"
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         "devDisabledIn${productFlavor}${buildType}"
 *   //         "devDisabledIn${buildType}"
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require("./image.png")), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require("./image.png")), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don"t look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: true
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: project(":react-native-config").projectDir.getPath() + "/dotenv.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = "org.webkit:android-jsc-intl:+"`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = "org.webkit:android-jsc:+"
/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dexOptions {
        javaMaxHeapSize "4g"
    } 
    defaultConfig {
        applicationId "com.stegappasaurus"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        multiDexEnabled true
        testBuildType System.getProperty('testBuildType', 'debug')  // This will later be used to control the test apk build type
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty("MYAPP_RELEASE_STORE_FILE")) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            proguardFile "${rootProject.projectDir}/../node_modules/detox/android/detox/proguard-rules-app.pro"
            shrinkResources true
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    packagingOptions {
        pickFirst "**/armeabi-v7a/libc++_shared.so"
        pickFirst "**/x86/libc++_shared.so"
        pickFirst "**/arm64-v8a/libc++_shared.so"
        pickFirst "**/x86_64/libc++_shared.so"
        pickFirst "**/x86/libjsc.so"
        pickFirst "**/armeabi-v7a/libjsc.so"
    }
}

preBuild.doFirst {
    ant.replaceregexp(match: "android.support.annotation.NonNull;", replace: "androidx.annotation.NonNull;", flags: "g", byline: true) {
        fileset(dir: "../../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/transitions/", includes: "*.java")
    }
    ant.replaceregexp(match: "android.support.annotation.Nullable;", replace: "androidx.annotation.Nullable;", flags: "g", byline: true) {
        fileset(dir: "../../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/transitions/", includes: "*.java")
    }
    ant.replaceregexp(match: "android.support.transition", replace: "androidx.transition", flags: "g", byline: true) {
        fileset(dir: "../../node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/transitions/", includes: "*.java")
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
    implementation 'com.facebook.react:react-native:+'  // From node_modules
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50"
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
    androidTestImplementation('com.wix:detox:+') { transitive = true } 
    androidTestImplementation 'junit:junit:4.12'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into "libs"
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

play {
    defaultToAppBundles = true
    track = "internal"
    serviceAccountCredentials = file("./play-store.json")
    resolutionStrategy = "auto"
    outputProcessor {
        versionNameOverride = "$versionNameOverride.$versionCode"
    }
}

apply plugin: 'com.google.gms.google-services'
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'Stegappasaurus'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
package com.stegappasaurus;

import android.app.Application;
import android.util.Log;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.bugsnag.BugsnagReactNative;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List;

import com.stegappasaurus.bitmap.BitmapReactPackage;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new BitmapReactPackage());
      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    BugsnagReactNative.start(this);
    SoLoader.init(this, /* native exopackage */ false);
  }
}
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.stegappasaurus">
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:allowBackup="false" android:theme="@style/AppTheme">
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    <activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity" android:theme="@style/Base.Theme.AppCompat" />

    <activity android:name=".SplashActivity" android:theme="@style/SplashTheme" android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>

    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:screenOrientation="portrait" android:windowSoftInputMode="adjustResize" android:exported="true" android:launchMode="singleTask" />

    <meta-data android:name="com.bugsnag.android.API_KEY" android:value="@string/BUGSNAG_API_KEY" />
    <meta-data android:name="com.bugsnag.android.DETECT_NDK_CRASHES" android:value="true" />
  </application>
</manifest>
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (8) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 753.70 MB / 15.61 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 8.16.0 - /tmp/yarn--1577145598608-0.8718799103945696/node
    Yarn: 1.19.1 - /tmp/yarn--1577145598608-0.8718799103945696/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.2
      System Images: android-25 | Google APIs ARM EABI v7a
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1
Done in 3.41s.
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.2.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Analytics`
  - `Performance Monitroing`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.2`
  
</p>
</details>

---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
If there's a crash, there's a crash trace somewhere. What does the console of Xcode (ios crash) or logcat (android crash) say? That will contain the answer.

Not that for performance monitoring on ios you'll want up to date Pods or it will crash on iOS13

**Comment by hmajid2301** [comment]
Hey Mike,

If I run `adb logcat` I see a lot of logs, how do I know where the app crashed. I assume it'll have some stack trace but I see multiple stack traces etc.

Thanks

**Comment by mikehardy** [comment]
Your assumption is correct. There are lots of logs. But if you use terminal with big scrollback, and patience, you should see it. Crashes always leave a trace.

**Comment by hmajid2301** [comment]
I've got the full log output here https://pastebin.com/qGRpxEbc.
Below I've copied what I think is the relevant part.

```
12-25 13:51:03.902  3999  3999 D FirebasePerformance: onResume(): com.stegappasaurus.MainActivity: 1083844 microseconds
12-25 13:51:03.905  3999  4054 E AndroidRuntime: FATAL EXCEPTION: pool-12-thread-1
12-25 13:51:03.905  3999  4054 E AndroidRuntime: Process: com.stegappasaurus, PID: 3999
12-25 13:51:03.905  3999  4054 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at com.google.android.gms.internal.firebase-perf.zzbc.zzn(com.google.firebase:firebase-perf@@19.0.2:16)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at com.google.android.gms.internal.firebase-perf.zzbc.zzc(com.google.firebase:firebase-perf@@19.0.2:44)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at com.google.android.gms.internal.firebase-perf.zzbc$zza.zzq(com.google.firebase:firebase-perf@@19.0.2:19)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at com.google.firebase.perf.internal.zzf.zzam(com.google.firebase:firebase-perf@@19.0.2:42)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at com.google.firebase.perf.internal.zzf.zzc(com.google.firebase:firebase-perf@@19.0.2:194)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at com.google.firebase.perf.internal.zze.run(com.google.firebase:firebase-perf@@19.0.2:2)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-25 13:51:03.905  3999  4054 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
12-25 13:51:03.905  3999  4055 E AndroidRuntime: FATAL EXCEPTION: pool-12-thread-2
12-25 13:51:03.905  3999  4055 E AndroidRuntime: Process: com.stegappasaurus, PID: 3999
12-25 13:51:03.905  3999  4055 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.perf.internal.zzv.zzb(boolean)' on a null object reference
12-25 13:51:03.905  3999  4055 E AndroidRuntime:        at com.google.firebase.perf.internal.zzf.zzc(com.google.firebase:firebase-perf@@19.0.2:169)
12-25 13:51:03.905  3999  4055 E AndroidRuntime:        at com.google.firebase.perf.internal.zzi.run(com.google.firebase:firebase-perf@@19.0.2:2)
12-25 13:51:03.905  3999  4055 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-25 13:51:03.905  3999  4055 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-25 13:51:03.905  3999  4055 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
12-25 13:51:03.919  3999  3999 W .stegappasauru: Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
12-25 13:51:03.926  3999  4056 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_disabled_android_versions'.
12-25 13:51:03.926  3999  3999 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
12-25 13:51:03.926  3999  4056 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_enabled'.
12-25 13:51:03.928  3999  4056 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_disabled_android_versions'.
12-25 13:51:03.928  3999  4056 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_enabled'.
```

**Comment by mikehardy** [comment]
I've only see things like that when a local project has done things with gradle dependencies such that libraries resolve to unexpected / mismatched versions. I'd closely examine your android/build.gradle and android/app/build.gradle and make sure you've got consistent and up to date versions of all the firebase and play services libs.

You can override versions of firebase like so, in order to the a current version 
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L29

and current is 24.4.0
https://firebase.google.com/support/release-notes/android#bom_v24-4-0

You can diagnose what versions are actually resolved with `./gradlew :app:dependencies` in the android directory.

The output there is also massive, but it is thorough and an analysis will point the way.
