### ISSUE TITLE
Android app crashes on launch

### ISSUE THREAD

**Issue by iLevye** [invertase/react-native-firebase#3042]
## Issue
If I follow the link on the crash description, I'm having 'Manifest merger failed' error. Looks like I don't have to add anything to AndroidManifest.xml 

logcat output

```
12-21 20:45:46.074 20504 20504 D AndroidRuntime: Shutting down VM
12-21 20:45:46.076 20504 20504 E AndroidRuntime: FATAL EXCEPTION: main
12-21 20:45:46.076 20504 20504 E AndroidRuntime: Process: com.appid, PID: 20504
12-21 20:45:46.076 20504 20504 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: ******************************************************************************
12-21 20:45:46.076 20504 20504 E AndroidRuntime: * Invalid application ID. Follow instructions here:                          *
12-21 20:45:46.076 20504 20504 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
12-21 20:45:46.076 20504 20504 E AndroidRuntime: * to find your app ID.                                                       *
12-21 20:45:46.076 20504 20504 E AndroidRuntime: ******************************************************************************
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: Caused by: java.lang.IllegalStateException: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: ******************************************************************************
12-21 20:45:46.076 20504 20504 E AndroidRuntime: * Invalid application ID. Follow instructions here:                          *
12-21 20:45:46.076 20504 20504 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
12-21 20:45:46.076 20504 20504 E AndroidRuntime: * to find your app ID.                                                       *
12-21 20:45:46.076 20504 20504 E AndroidRuntime: ******************************************************************************
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at com.google.android.gms.internal.ads.zzxb.attachInfo(com.google.android.gms:play-services-ads-lite@@18.1.1:20)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@18.1.1:3)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
12-21 20:45:46.076 20504 20504 E AndroidRuntime: 	... 10 more

```
---

#### `package.json`:

```
"dependencies": {
    "@react-native-community/art": "^1.0.3",
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/netinfo": "^4.2.2",
    "@react-native-firebase/admob": "^6.0.0",
    "@react-native-firebase/analytics": "^6.0.0",
    "@react-native-firebase/app": "^6.0.0",
    "@react-native-firebase/auth": "^6.0.0",
    "@react-native-firebase/crashlytics": "^6.0.0",
    "@react-native-firebase/database": "^6.0.0",
    "@react-native-firebase/firestore": "^6.0.0",
    "@react-native-firebase/functions": "^6.0.0",
    "@react-native-firebase/in-app-messaging": "^6.0.0",
    "@react-native-firebase/messaging": "^6.0.0",
    "@react-native-firebase/remote-config": "^6.0.0",
    "@react-native-firebase/storage": "^6.0.0",
    "crypto-js": "^3.1.9-1",
    "emoji-utils": "^1.0.1",
    "javascript-time-ago": "^2.0.2",
    "native-base": "^2.13.8",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-anchor-carousel": "^3.1.1",
    "react-native-camera": "^3.6.0",
    "react-native-device-info": "^3.1.4",
    "react-native-dialog-input": "^1.0.7",
    "react-native-fs": "^2.14.1",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-gifted-chat": "^0.10.1",
    "react-native-iap": "^3.4.12",
    "react-native-image-picker": "^1.1.0",
    "react-native-localization": "^2.1.6",
    "react-native-md5": "^1.0.0",
    "react-native-progress": "^3.6.0",
    "react-native-progress-circle": "^2.0.1",
    "react-native-rate": "^1.1.7",
    "react-native-reanimated": "^1.3.0",
    "react-native-responsive-grid": "^0.41.992",
    "react-native-restart": "0.0.13",
    "react-native-swipe-gestures": "^1.0.3",
    "react-native-video": "^5.0.2",
    "react-native-video-editor": "^0.2.0",
    "react-native-webview": "5.0.0",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.2.2",
    "react-navigation-stack": "^1.9.0",
    "react-redux": "^7.1.1",
    "recyclerlistview": "^2.0.12",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6",
    "reactotron-react-native": "^4.0.2",
    "reactotron-redux": "^3.1.2"
  },
  "jest": {
    "preset": "react-native"
  }
```

#### `firebase.json` for react-native-firebase v6:
There is no firebase.json file. I searched v6 documentation and setup instructions. There is no mention to firebase.json. I just have google-services.json under android/app/

### iOS

It works great on iOS.

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

#### `AppDelegate.m`:

---

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
    }
}

```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    dexOptions {
        javaMaxHeapSize "12g"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.appid"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        missingDimensionStrategy 'react-native-camera', 'general'
        multiDexEnabled true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "com.google.android.gms:play-services-base:16.1.0"
    implementation "androidx.appcompat:appcompat:1.0.0"

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'
```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'appname'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `MainApplication.java`:

```java
package com.appid;

import android.app.Application;
import android.util.Log;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List;



public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());

      return packages;
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.appid">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data
                android:name="com.google.android.gms.ads.APPLICATION_ID"
                android:value="ca-app-pub-7590562592808907~9079411967"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

</p>
</details>

---

## Environment

**`react-native info` output:**

```
System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 74.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.3/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.0, 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.0.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Admob`
- **Are you using `TypeScript`?**
  - `Y`

**Comment by iLevye** [comment]
Looks like issue template is right. This is configuration issue! I've created firebase.json and its works. 
https://invertase.io/oss/react-native-firebase/v6/admob/quick-start

**Comment by andercard** [comment]
Just keep in mind that you add the **firebase.json** file well in the root

**Comment by Revathicolourmoon0140** [comment]
my app is crash after installing  npm i @react-native-firebase/admob and  react-native-firebase_app,

please help me

**Comment by mikehardy** [comment]
@Revathicolourmoon0140 you post no details on a bug getting close to a year old :thinking: 
You should become familiar with how to watch the device logs as you run your app, it will help you in your journey
My *guess* is you did not include the admob id in your app. You'll crash immediately on startup if you forget it.
As indicated here: https://rnfirebase.io/admob/usage#setting-up-google-admob
And demonstrated here: https://github.com/mikehardy/rnfbdemo/blob/9e80bacc9b62961f89246eea82dd956f4f8660f8/make-demo.sh#L138-L144

**Comment by AliRehman7141** [comment]
@mikehardy could you please help me I am facing this error when I integrate crashlytics
https://github.com/facebook/react-native/issues/30828

**Comment by mikehardy** [comment]
Check out the make-demo.sh script I link to in this repo all the time. It will show up in searches. Pay attention to the multidex lines.

**Comment by AliRehman7141** [comment]
@mikehardy Thanks for your response!!!!!!!!

Sorry for inconvience!
It is fixed for now I have used Facebook login in the past but now it is removed from react-native code and package.json but the integration not removed from the android side.

I removed these lines
```
---      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
---      <provider android:authorities="com.facebook.app.FacebookContentProvider249341956089060 android:name="com.facebook.FacebookContentProvider"
---          android:exported="true" />

```
![Screen Shot 2021-02-02 at 5 35 52 PM](https://user-images.githubusercontent.com/33172988/106601142-202bf080-657d-11eb-86ba-c94bd280f3d0.png)
