### ISSUE TITLE
🔥Android crashes on launching from notification (about Messaging module background task)

### ISSUE THREAD

**Issue by dehypnosis** [invertase/react-native-firebase#3399]
## Issue

when **closed app** received FCM message (data only), headless background task runs.
And the background handler post a notification with this library.
A notification appears well but when touching the notification, app crashes while launching and nothing shows.
There are no problems for active and inactive mode both. crashes only when launched from **closed (quite)** state.
Logs attached.

```
[15:39:10] D | ReactNative ▶︎ [CodePush] Loading JS bundle from "assets://index.android.bundle"

[15:39:10] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[15:39:10] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()

[15:39:11] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()
                           │ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()

[15:39:11] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[15:39:11] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[15:39:11] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[15:39:11] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge

[15:39:11] D | ReactNative ▶︎ CatalystInstanceImpl.runJSBundle()
                           │ ReactInstanceManager.setupReactContext()
                           └ CatalystInstanceImpl.initialize()

[15:39:13] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() start
                           └ CatalystInstanceImpl.destroyV1() start

[15:39:14] I | ReactNativeJS ▶︎ 'global background handler', { sentTime: 1586155150864,
                             │ ttl: 2419200,
                             │ data:
                             │ { title: '안녕 title from server',
                             │ time: '16:39:10',
                             │ body: 'body from server' },
                             │ messageId: '0:1586155151591077%686395e72087b7d4',
                             │ from: '490321196875',
                             └ collapseKey: 'PBmao4recL/kfD1kTBkUkj0IwJg=' }

[15:39:14] D | ReactNativeJS ▶︎ 'notification post', { title: '안녕 title from server (global)',
                             └ message: 'body from server' }

[15:39:14] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() end
```
a notification showed then tapped.
```
[15:40:03] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.attachRootViewToInstance()
here app crashed and nothing happened.
```
below is adb crash log
```
04-06 15:40:03.108  5562  5562 E AndroidRuntime: FATAL EXCEPTION: main
04-06 15:40:03.108  5562  5562 E AndroidRuntime: Process: com.qmit.plco.debug, PID: 5562
04-06 15:40:03.108  5562  5562 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmit.plco.debug/com.qmit.plco.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.UIManager.addRootView(android.view.View, com.facebook.react.bridge.WritableMap, java.lang.String)' on a null object reference
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6986)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.UIManager.addRootView(android.view.View, com.facebook.react.bridge.WritableMap, java.lang.String)' on a null object reference
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1116)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootView(ReactInstanceManager.java:796)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactRootView.attachToReactInstanceManager(ReactRootView.java:620)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:407)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:370)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:103)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:90)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:85)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:45)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at com.qmit.plco.MainActivity.onCreate(MainActivity.java:23)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7326)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7317)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
04-06 15:40:03.108  5562  5562 E AndroidRuntime: 	... 11 more
```

*java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmit.plco.debug/com.qmit.plco.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int com.facebook.react.bridge.UIManager.addRootView(android.view.View, com.facebook.react.bridge.WritableMap, java.lang.String)' on a null object reference*

Seems UIManager not ready to open the activity..... because... the notification has been created from background mode?
Could I get any hints?

---

#### `package.json`:

```json
"react-native": "^0.62.1",
"@react-native-firebase/messaging": "^6.4.0",
"react-native-push-notification": "^3.1.9",
```

</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 3.72 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.4.0`
- **`Firebase` module(s) you're using that has the issue:**
  - Messaging
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

**Comment by wincjh** [comment]
did you solve the problem?

**Comment by dehypnosis** [comment]
@wincjh check this out!
https://github.com/facebook/react-native/issues/28553#issuecomment-611850465

**Comment by mbrehme** [comment]
Hey I have kind of the same problem. The App is blank when opened after the background task (`messaging().setBackgroundMessageHandler`) has run (I don't see any specific error on start but the app is kind of blank).

@dehypnosis how did you used the given approach from the other issue?

the `AppRegistry.runApplication("noop", { rootTag: null });` block the finishing of the background task and I think therefore is never really killed...

Would be awesome if you share your solution to overcome this issue.

Thanks in advance

**Comment by dehypnosis** [comment]
@mbrehme right it make a background task immortal. it is basically imcomplete solution.
just invoke running code once at the last of background handler
