### ISSUE TITLE
[Android][Messaging] Unable to subscribe to topic

### ISSUE THREAD

**Issue by samkotlove** [invertase/react-native-firebase#3480]
## Issue

Hi! I'm currently running into an issue with subscribing to topics. I'm able to send messages directly to the android device (testing on an actual phone) using the fcm token, but am unable to subscribe to a topic. I have the following function:
```
static async subscribeToTopic(topic) {
    try {
      console.log('subscribeToTopic called')
      await messaging().subscribeToTopic(topic);
        console.log('subscribeToTopic done')
    } catch (e) {
      console.log('subscribeToTopic failed');
    }
  }
```
Which never resolves/fails in the js code(i.e. neither the done or failed message seem to ever print). Checking the logs in android studio I see a couple interesting lines:
```
2020-04-16 00:26:00.079 15897-16086/com.myapp.myapp.debug E/FirebaseMessaging: Failed to sync topics. Won't retry sync. FIS_AUTH_ERROR
2020-04-16 00:28:01.697 15897-16942/com.myapp.myapp.debug E/FirebaseInstanceId: Failed to get FIS auth token
    java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException
        at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
        at com.google.android.gms.tasks.Tasks.await(Unknown Source:23)
        at com.google.firebase.iid.zzt.zzb(com.google.firebase:firebase-iid@@20.1.5:54)
        at com.google.firebase.iid.zzt.zza(com.google.firebase:firebase-iid@@20.1.5:72)
        at com.google.firebase.iid.zzs.run(Unknown Source:12)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: com.google.firebase.installations.FirebaseInstallationsException
        at com.google.firebase.installations.FirebaseInstallations.doNetworkCall(com.google.firebase:firebase-installations@@16.2.1:350)
        at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationInternal$0(com.google.firebase:firebase-installations@@16.2.1:323)
        at com.google.firebase.installations.FirebaseInstallations$$Lambda$5.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919) 
2020-04-16 00:28:01.703 15460-16944/? V/FA-SVC: Background event processing time, ms: 30
2020-04-16 00:28:01.712 785-16958/? E/ResolverController: No valid NAT64 prefix (101, <unspecified>/0)
2020-04-16 00:28:01.792 15897-15962/com.myapp.myapp.debug E/FirebaseInstanceId: Topic sync or token retrieval failed on hard failure exceptions: FIS_AUTH_ERROR. Won't retry the operation.
```
The one line seems to imply that the subscribe to topic call failed:
```
E/FirebaseMessaging: Failed to sync topics. Won't retry sync. FIS_AUTH_ERROR
```
I didn't find any reliable information from google on the error message `FIS_AUTH_ERROR` but there are a few stackoverflow and github discussions about it (such as [here](https://stackoverflow.com/questions/60698622/java-io-ioexception-fis-auth-error-in-android-firebase)) that seem to imply it has to do with a broken version of `com.google.firebase:firebase-messaging`, starting at version 20.1.1 . I'm less fluent in android development, so I'm not sure how to determine which version is being used. I tried calling out different versions in the build.gradle inside `node_modules/@react-native-firebase/messaging/` but that didnt seem to help. It's definitely possibly this is the issue but I didn't handle it properly.

As a note in relation to the other line coming from iid, my code also failed when calling messaging().getToken() (The react-native-push-notification library has similar functionality to get the fcm token, which is how I was able to confirm sending messages to a specific device works) but thought it might be related to the above issue. I'm not actually using iid at the moment though, so could be unrelated 🤷 
```
E/FirebaseInstanceId: Failed to get FIS auth token
```
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "MYAPP",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "android-port": "adb reverse tcp:8081 tcp:8081",
    "android-clean": "cd android && ./gradlew clean",
    "postinstall": "patch-package"
  },
  "rnpm": {
    "assets": [
      "./src/fonts/"
    ]
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^3.2.0",
    "@react-native-community/async-storage": "github:react-native-community/async-storage",
    "@react-native-community/netinfo": "^4.4.0",
    "@react-native-community/push-notification-ios": "^1.1.1",
    "@react-native-firebase/app": "6.4.1-alpha.0",
    "@react-native-firebase/crashlytics": "6.4.1-alpha.0",
    "@react-native-firebase/iid": "6.4.1-alpha.0",
    "@react-native-firebase/messaging": "6.4.1-alpha.0",
    "@react-navigation/core": "^3.5.1",
    "amazon-cognito-identity-js": "^3.1.3",
    "aws-amplify": "^2.2.6",
    "luxon": "^1.21.3",
    "patch-package": "^6.2.2",
    "react": "16.8.1",
    "react-native": "0.61.4",
    "react-native-admob": "^2.0.0-beta.6",
    "react-native-admob-native-ads": "^0.1.1",
    "react-native-config": "^0.11.7",
    "react-native-device-info": "^4.0.1",
    "react-native-elements": "^1.2.6",
    "react-native-fs": "^2.16.1",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-push-notification": "^3.1.9",
    "react-native-screens": "^2.4.0",
    "react-native-sound": "^0.11.0",
    "react-native-svg": "^9.12.0",
    "react-native-unimodules": "^0.6.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-xml2js": "^1.0.3",
    "react-navigation": "^3.13.0",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "superagent": "^5.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.1.0",
    "babel-preset-fbjs": "^3.3.0",
    "jest": "^24.1.0",
    "metro-react-native-babel-preset": "^0.51.1",
    "react-test-renderer": "16.8.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "crashlytics_debug_enabled": true
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        versionCode = 26
        versionNumber = "2.1.2"
    }
    repositories {
        google()
        jcenter()
        // crashlytics
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath('com.android.tools.build:gradle:3.5.0')

        // crashlytics
        classpath 'com.google.gms:google-services:4.3.3'
        classpath('io.fabric.tools:gradle:1.28.1')

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven {
            url "https://s3.amazonaws.com/moat-sdk-builds"
            content {
                includeGroupByRegex "com\\.moat.*"
            }
        }
    }
}
```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"
apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = false

def jscFlavor = 'org.webkit:android-jsc:+'

def enableHermes = project.ext.react.get("enableHermes", false)

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    dexOptions {
        incremental true
        javaMaxHeapSize "4G"
    }
    defaultConfig {
        applicationId "com.myapp.myapp"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 26
        versionName "2.1.2"
        multiDexEnabled true

        // react-native-config
        resValue "string", "build_config_package", "com.myapp.myapp.debug"
        resValue "string", "build_config_package", "com.myapp.myapp"
    }
    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}


configurations.all {
    resolutionStrategy {
        force "com.google.android.gms:play-services-base:16.1.0"
        force "com.google.android.gms:play-services-gcm:16.1.0"
        force "com.google.android.gms:play-services-ads:19.0.0"
    }
}
dependencies {
    implementation project(':react-native-fs')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-push-notification')

    ...

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/"
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

project.ext.envConfigFiles = [
    debug: ".env.dev",
    release: ".env.prod",
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); 
applyNativeModulesAppBuildGradle(project)
apply plugin: 'com.google.gms.google-services'

```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'MYAPP'
include ':react-native-fs'
project(':react-native-fs').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fs/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = file('../node_modules/react-native-push-notification/android')
include ':app'
```

#### `MainApplication.java`:

```java
package com.myapp.myapp;

import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;
import com.rnfs.RNFSPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import io.invertase.firebase.messaging.ReactNativeFirebaseMessagingPackage;


public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());

          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this); // Remove this line if you don't want Flipper enabled
  }

  /**
   * Loads Flipper in React Native templates.
   *
   * @param context
   */
  private static void initializeFlipper(Context context) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.facebook.flipper.ReactNativeFlipper");
        aClass.getMethod("initializeFlipper", Context.class).invoke(null, context);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}

```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.myapp.myapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="com.android.vending.BILLING" />
    <permission
       android:name="${applicationId}.permission.C2D_MESSAGE"
       android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:configChanges="keyboardHidden|orientation|screenSize"
      android:largeHeap="true"
      android:theme="@style/AppTheme"
      android:usesCleartextTraffic="true">
      <meta-data
          android:name="com.google.android.gms.ads.APPLICATION_ID"
          android:value="ca-app-pub-6862671365772667~8592711245"/>
      <meta-data android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@mipmap/ic_notification"/>
      <meta-data android:name="com.dieam.reactnativepushnotification.notification_color"
          android:resource="@android:color/white"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
          android:value="com.myapp.myapp"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
          android:value="com.myapp.myapp"/>
      
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
          </intent-filter>
      </receiver>

      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm" android:exported="false" >
        <intent-filter>
          <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        </intent-filter>
      </service>
      <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>
      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:exported="true"
        />
      <activity
        android:name=".SplashActivity"
        android:theme="@style/SplashTheme"
        android:label="@string/app_name">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"
                android:windowSoftInputMode="adjustNothing"
      />
    </application>

</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 408.18 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.1 => 16.8.1
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.61.2
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `6.4.1-alpha.0`, `6.4.0`, `6.3.4`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by samkotlove** [comment]
On further research I learned a couple things, the command I was looking for to determine the installed dependency is `./gradlew app:dependencies`. I was partially on the right path by changing the @react-native-firebase/messaging build.gradle file to 
```
 implementation  'com.google.firebase:firebase-messaging:20.1.0' 
```
but when running`./gradlew app:dependencies` it showed:
```
+--- project :react-native-firebase_messaging
|    +--- com.google.firebase:firebase-messaging:20.1.0 -> 20.1.5
```
From my understanding the left side of the arrow is the requested version and the right is the resolved version. What I actually needed to do was change the build.gradle to:
```
  implementation('com.google.firebase:firebase-messaging') {
      version {
          strictly '20.1.0'
      }
  }
```
and after printing the dependencies I can see:
```
+--- project :react-native-firebase_messaging
|    +--- com.google.firebase:firebase-messaging:{strictly 20.1.0} -> 20.1.0 (*)
```

And after testing the topic issue is resolved. Might dig more into what the actual issue is and see if I can solve it. The relevant portion from the [release notes](https://firebase.google.com/support/release-notes/android#messaging_v20-1-1):
> Apps that use the Firebase auto-initialization process and the Gradle plugin to convert google-services.json into resources are unaffected. However, apps that create their own FirebaseOptions instances must provide a valid API key, Firebase project ID, and application ID.

**Comment by russellwheatley** [comment]
Glad you were able to find a solution!

**Comment by samkotlove** [comment]
This stopped work and im at a loss for why, still trying to figure it out

@russellwheatley I dont know that this should be closed even if that solution did work

**Comment by samkotlove** [comment]
The original solution does work (I think the way this library is creating `firebaseoptions` causes problems with `com.google.firebase:firebase-messaging:20.1.1` and up ) but the reason my solution stopped working was due to my integration with [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) for local pushes. In my configuration for that library,  I included `senderID` which seemed to cause issues with this library. There were conflicting device tokens between the libraries, after removing that property the issue seems to be resolved. Hopefully I can save somebody else time.

**Comment by omarDtp** [comment]
@samkotlove  Hello I am having a similar issue i guess where im obliged to use both libraries
onesignal and react-native-push-notification
I neither could manage to fix it nor be able to understand what you have done to solve this issue
can you please help and elaborate
im only getting the issue on android devices

below is the following error

2020-05-27 16:51:16.628 27376-27663/xx.xxx.xxxxx E/FirebaseInstanceId: Failed to get FIS auth token
2020-05-27 16:51:16.639 27376-27376/xx.xxx.xxxxx E/RNPushNotification: exception
    java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.2.0:16)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
2020-05-27 16:51:16.639 27376-27376/xx.xxx.xxxxx E/RNPushNotification: exception
    java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.firebase.iid.zzu.then(com.google.firebase:firebase-iid@@20.2.0:16)
        at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
2020-05-27 16:52:31.196 27376-27764/xx.xxx.xxxxx E/FirebaseInstanceId: Failed to get FIS auth token

**Comment by samkotlove** [comment]
> @samkotlove Hello I am having a similar issue i guess where im obliged to use both libraries
> onesignal and react-native-push-notification
> I neither could manage to fix it nor be able to understand what you have done to solve this issue
> can you please help and elaborate

Did you try the solution I described above?

> 
> What I actually needed to do was change the build.gradle to:
> 
>  ``` 
> implementation('com.google.firebase:firebase-messaging') {
>       version {
>           strictly '20.1.0'
>       }
>   }
