### ISSUE TITLE
cannot react-native run-android after installing react-native-firebase

### ISSUE THREAD

**Issue by anthony-elhaddad** [invertase/react-native-firebase#3483]
i have followed the tutorial on adding react-native-firebase to an existing app, then i have tried running the app but it gave me an error saying: 

``` events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'C:\code\ReactNativeProjects\navigator2App\android\app\build\generated\source\buildConfig\debug\com\navigator2app\BuildConfig.java'
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.<anonymous> (C:\code\ReactNativeProjects\navigator2App\node_modules\sane\src\node_watcher.js:291:16)
    at FSReqCallback.oncomplete (fs.js:166:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\code\\ReactNativeProjects\\navigator2App\\android\\app\\build\\generated\\source\\buildConfig\\debug\\com\\navigator2app\\BuildConfig.java'
}
```

then i tried to look for a solution online:
some answers were delete node_modules and re install, 
others were ''cd android'' ''gradlew clean''
i tried both with no success. but what happened in gradlew clean shows this:

```
> Configure project :react-native-firebase_app
:react-native-firebase_app:firebase.bom using default value: 24.1.0
:react-native-firebase_app package.json found at C:\code\ReactNativeProjects\naviage.json
:react-native-firebase_app:version set from package.json: 6.4.0 (6,4,0 - 6004000)
:react-native-firebase_app:android.compileSdk using custom value: 28
:react-native-firebase_app:android.targetSdk using custom value: 28
:react-native-firebase_app:android.minSdk using custom value: 16
:react-native-firebase_app:reactNativeAndroidDir C:\code\ReactNativeProjects\navi

> Configure project :react-native-firebase_auth
:react-native-firebase_auth:firebase.bom using default value: 24.1.0
:react-native-firebase_auth package.json found at C:\code\ReactNativeProjects\navckage.json
:react-native-firebase_auth:version set from package.json: 6.4.0 (6,4,0 - 6004000
:react-native-firebase_auth:android.compileSdk using custom value: 28
:react-native-firebase_auth:android.targetSdk using custom value: 28
:react-native-firebase_auth:android.minSdk using custom value: 16
:react-native-firebase_auth:reactNativeAndroidDir C:\code\ReactNativeProjects\nav

Deprecated Gradle features were used in this build, making it incompatible with G
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:comma
```

so i ran the gradle build --warning-mode all
and im stuck here. 

EDIT1: 
after that build is finished with success, i tried react-native run-android, and i got the following error:

```
> Task :react-native-gesture-handler:packageDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
35 actionable tasks: 35 executed
Note: C:\code\ReactNativeProjects\navigator2App\node_modules\@react-native-firebase\app\android\src\reactnative\java\io\invertase\firebase\app\ReactNativeFirebaseAppInitProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.
```

has this happened to anybody ?
thanks in advance

**Comment by mikehardy** [comment]
no template
looks like you're trying v6? clone this and run it - generates a clean sample project and you can compare with your efforts to see where things went off the rails?
https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh
