### ISSUE TITLE
Update ShortcutBadger

### ISSUE THREAD

**Issue by MatthieuPeyrot** [invertase/react-native-firebase#356]
Hi 

I have an issue on my samsung galaxy S6 , it crash when i try to update the badgeNumber.
I thing it because you are not using the last version of ShortcutBadger

you are using :  compile 'me.leolin:ShortcutBadger:1.1.10@aar'
now it's : compile 'me.leolin:ShortcutBadger:1.1.18@aar'

that's the crash : 

0 | io.invertase.firebase.messaging.BadgeHelper.setBadgeCount | BadgeHelper.java:33
1 | io.invertase.firebase.messaging.MessagingService.handleBadge | MessagingService.java:41
2 | io.invertase.firebase.messaging.MessagingService.onMessageReceived | MessagingService.java:23
3 | com.google.firebase.messaging.FirebaseMessagingService.handleIntent | Unknown Source
4 | com.google.firebase.iid.zzc.run | Unknown Source
5 | java.util.concurrent.ThreadPoolExecutor.runWorker | ThreadPoolExecutor.java:1133
6 | java.util.concurrent.ThreadPoolExecutor$Worker.run | ThreadPoolExecutor.java:607
7 | java.lang.Thread.run | Thread.java:762

1. Target Platform  (Android):
2. Development Operating System (macOS Sierra):
3. React Native version (0.47.2):
4. RNFirebase Version (2.1.3):

**Comment by MatthieuPeyrot** [comment]
![screenshot_20170824-103559](https://user-images.githubusercontent.com/22000269/29663515-c67920d0-88cb-11e7-879f-db7f74bc2921.png)

**Comment by gusgard** [comment]
Have the same issue but using the last version of me.leolin:ShortcutBadger:1.1.18@aar doesn't fix it.

**Comment by MatthieuPeyrot** [comment]
Me neither

**Comment by chrisbianca** [comment]
@MatthieuPeyrot I'm unable to reproduce this.  Can you send the contents of your `app/build.gradle`?

**Comment by MatthieuPeyrot** [comment]
hi i maybe find a solution i don't have the red screen by adding this in the build.gradle 

repositories {
    mavenCentral()
}

but the notif badge don't change on my samsung device.

**Comment by erezrokah** [comment]
The ShortcutBadger badger lib has an app to test if it works on your phone:
https://play.google.com/store/apps/details?id=me.leolin.isbadgeworking

I got the link from their repo:
https://github.com/leolin310148/ShortcutBadger

We tried it on several phones and only one of them actually showed the badge

**Comment by MatthieuPeyrot** [comment]
it work on the samsung galaxy s5  (android 6 )but not on the s6 edge (android 7 )
But i have to add compile 'me.leolin:ShortcutBadger:1.1.18@aar' and 
repositories {
mavenCentral()
}
on my build.gradle 
not on react native firebase
that's weird

**Comment by chrisbianca** [comment]
I've updated the dependency to the latest version of Shortcut Badger for the upcoming v3 release

**Comment by cluny85** [comment]
Still happen this problem with the last version. I don't know why because i can see ShortcutBadger exported like a Library in the react-native-firebase project.
Didn't work also adding the compile on the build.gradle of the main project.
Could be my version of gradle (2.3.3)? is necessary to have 3.0> ?
Thanks

**Comment by hegelstad** [comment]
This still happens with latest build.

**Comment by pilot4u** [comment]
I have similar app crash after upgrading to version 4.0.3:
`java.lang.RuntimeException: Unable to instantiate service io.invertase.firebase.messaging.MessagingService: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.messaging.MessagingService" on path: DexPathList[[zip file "/data/app/com.myApp.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myApp.app-2/lib/arm, /data/app/com.myApp.app-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2896)
                                                                         at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.messaging.MessagingService" on path: DexPathList[[zip file "/data/app/com.myApp.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.myApp.app-2/lib/arm, /data/app/com.myApp.app-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                         at android.app.ActivityThread.handleCreateService(ActivityThread.java:2893)
                                                                         at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1446) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                     	Suppressed: java.lang.ClassNotFoundException: io.invertase.firebase.messaging.MessagingService
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                         		... 10 more
                                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by kkusanagi** [comment]
There is no documentation after v3.3.x. I think they had remove it.

**Comment by haseebnaseem** [comment]
Still happening with 4.2.0

**Comment by turboc** [comment]
implementation "com.google.firebase:firebase-messaging:17.1.0"
implementation 'me.leolin:ShortcutBadger:1.1.21@aar'

I've downloaded the 'isBadgeWorking?' in a Samsung and it's working.
But it does not work when my app receives a message and shows the notification.

**Comment by kkusanagi** [comment]
About this, it got a simple method.
Follow the step below.
[react-native-push-notifications-with-firebase-cloud-functions](https://medium.com/the-modern-development-stack/react-native-push-notifications-with-firebase-cloud-functions-74b832d45386)

Use below payload while sending notification.
```
let payload = {
      notification: {
      title: 
      body:
      sound:
      badge:
     }
    }
```

Or,

Use firebase console to send a notification to your mobile phone by token.
Of course, you can also send a notification to all mobile that use the app. 

if your phone receive notification, mean it works. 
if not, there is something wrong with your setting.


Finally as for this thread issue, you need to use 

```
firebase.notifications().setBadge(10). //to set badge number

firebase.notifications().getBadge() // to get badge number

```

[Firebase Notification Library](https://rnfirebase.io/docs/v4.3.x/notifications/reference/Notifications)

**Comment by Biplovkumar** [comment]
> implementation "com.google.firebase:firebase-messaging:17.1.0"
> implementation 'me.leolin:ShortcutBadger:1.1.21@aar'
> 
> I've downloaded the 'isBadgeWorking?' in a Samsung and it's working.
> But it does not work when my app receives a message and shows the notification.

thanku so much @turboc .
u saved my day.

**Comment by mikehardy** [comment]
Careful - ShortcutBadger hasn't really been updated in 2 years https://github.com/leolin310148/ShortcutBadger - it doesn't work on all vendors and Google specifically will not support badging. Attempting to do badging on Android is fighting the platform - something that always results in resources spent for little gain

**Comment by huent-1493** [comment]
Hi, I have a issue: setBadge(0) in android not working , getBadge() in android is 0 but in icon app show number >0.
`const currentNumber = await firebase.notifications().getBadge()
    console.log('currentNumber ', currentNumber) // in here currentNumber = 0
    if (number <= 0) {
      await firebase.notifications().setBadge(0)
      // go to here but in icon app, badge >0
    } else {
      await firebase.notifications().setBadge(number)
    }`
Please help me.
 "react-native-firebase": "5.5.6"
 "react-native": "0.63.3"

**Comment by mikehardy** [comment]
No help whatsoever is offered for react-native-firebase v5
And specifically, badging in general is an anti-pattern on Android because it is not part of the platform and specifically not a desired feature in AOSP. It was removed on purpose
