### ISSUE TITLE
Issue: Unable to get provider io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider

### ISSUE THREAD

**Issue by rahulkasana** [invertase/react-native-firebase#3670]
Hello, I've been using 
"react-native": "0.61.5",
"@react-native-firebase/app": "^6.3.4",
"@react-native-firebase/crashlytics": "^6.3.4"

I recently uploaded the app on playstore and when playstore ran pre launch reports the app is crashing only for Galaxy S3 running at Android 4.3
It's working on 11 devices but failing on just 1 device.

This is the error -
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to get provider io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider" on path: /data/app/com.abc-1.apk
	at android.app.ActivityThread.installProvider(ActivityThread.java:5122)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
	at android.app.ActivityThread.access$1400(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider" on path: /data/app/com.abc-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5107)

So is it an issue OR Android 4.x is not supported by Firebase v6?

**Comment by mikehardy** [comment]
Smells like a multidex issue somehow if it's down on the Android 4.x devices. It should work fine on those though - assuming multidex is set up correctly. t†https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh#L125

**Comment by rahulkasana** [comment]
Thanks @mikehardy that solved the issue!

**Comment by RahulMJ5** [comment]
Hey @mikehardy, I got stuck into the same issue and was unable to access the link which you shared - Can you please reshare the fix for the multidex

**Comment by mikehardy** [comment]
There is no need for multidex, no version of Android still supported needs it. It is no longer a needed solution in any supported cases I'm aware of

**Comment by RahulMJ5** [comment]
Oh, Anyway I keep getting this below error on the logcat after the app crash,
The temporary solution is to clean the Gradle and re-run the app.
Let me know If you have a better Solution


Fatal Exception: java.lang.RuntimeException
Unable to get provider io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider" on path: DexPathList[[zip file "/data/app/~~yeXGdfsHTo-FRvuQPtYLmA==/com.pocomosapp.android-mEuPlxy9ktvARkYaDO4Bog==/base.apk"],nativeLibraryDirectories=[/data/app/~~yeXGdfsHTo-FRvuQPtYLmA==/com.pocomosapp.android-mEuPlxy9ktvARkYaDO4Bog==/lib/arm64, /data/app/~~yeXGdfsHTo-FRvuQPtYLmA==/com.pocomosapp.android-mEuPlxy9ktvARkYaDO4Bog==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]


Caused by java.lang.ClassNotFoundException
Didn't find class "io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider" on path: DexPathList[[zip file "/data/app/~~yeXGdfsHTo-FRvuQPtYLmA==/com.pocomosapp.android-mEuPlxy9ktvARkYaDO4Bog==/base.apk"],nativeLibraryDirectories=[/data/app/~~yeXGdfsHTo-FRvuQPtYLmA==/com.pocomosapp.android-mEuPlxy9ktvARkYaDO4Bog==/lib/arm64, /data/app/~~yeXGdfsHTo-FRvuQPtYLmA==/com.pocomosapp.android-mEuPlxy9ktvARkYaDO4Bog==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
