### ISSUE TITLE
Crashlytics android app crash

### ISSUE THREAD

**Issue by Spyspyspy** [invertase/react-native-firebase#3720]
Hello, I've installed crashlytics, but cannot run android app, because it crashes, while starting:
This is my stacktrace: 

java.lang.RuntimeException: Unable to get provider io.invertase.firebase.crashlytics.ReactNativeFirebaseCrashlyticsInitProvider: java.lang.RuntimeException: STUB: getEmptyProviderAuthority override not implemented
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: STUB: getEmptyProviderAuthority override not implemented
        at io.invertase.firebase.common.ReactNativeFirebaseInitProvider.getEmptyProviderAuthority(ReactNativeFirebaseInitProvider.java:48)
        at io.invertase.firebase.common.ReactNativeFirebaseInitProvider.attachInfo(ReactNativeFirebaseInitProvider.java:53)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by andersonaddo** [comment]
Why didn't you follow the template?

**Comment by Saschamz** [comment]
Having the same exact issue as you after following the instructions in the docs

**Comment by mikehardy** [comment]
@Saschamz the original user didn't post any details about their problem, and neither did you. Please post a new issue and follow the template to receive help

**Comment by mikehardy** [comment]
This may be related to #3711 and imply the need to fully update packages and run `npx react-native-clean-project` to make sure your local environment is in a consistent state
