### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to instantiate service io.invertase.firebase.messaging.RNFirebaseMessagingService: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by ravichandran18390** [invertase/react-native-firebase#3912]
Im facing this issue while launching an app only first time, logs & other details are added below

Logs:
Fatal Exception: java.lang.RuntimeException: Unable to instantiate service io.invertase.firebase.messaging.RNFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.messaging.RNFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.nagra.uk.jado-wDztxBUw-h33vOv56zcOog==/base.apk"],nativeLibraryDirectories=[/data/app/com.nagra.uk.jado-wDztxBUw-h33vOv56zcOog==/lib/x86, /data/app/com.nagra.uk.jado-wDztxBUw-h33vOv56zcOog==/base.apk!/lib/x86, /system/lib]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3519)
       at android.app.ActivityThread.access$1300(ActivityThread.java:199)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

versions
OSx - Mojave 10.14.5

IDE
android studio: 3.5.3
xcode: 11.2.1 (11B500)

react / react-native: 
"react": "16.9.0",
"react-native": "0.61.1",

react-native-firebase:
"@react-native-firebase/analytics": "7.1.5",
"@react-native-firebase/app": "7.3.0",
"@react-native-firebase/crashlytics": "7.1.6",
"@react-native-firebase/messaging": "7.1.7",

have followed the documentations are below
Getting started - https://rnfirebase.io/
and 
https://rnfirebase.io/migrating-to-v6#removing-v5-from-android

android/app/build.gradle:
dependencies {
.....
implementation "com.google.firebase:firebase-messaging:20.0.0"
implementation 'com.google.firebase:firebase-analytics:17.2.2'
implementation 'com.google.firebase:firebase-crashlytics:17.1.0'
....
}

at last of above file
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android/build.gradle:
dependencies {
		classpath 'com.android.tools.build:gradle:3.4.2'
		classpath 'com.google.gms:google-services:4.3.3'
		classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }

settings.gradle
no changes added 

please take a note that crashlytics and analytics works fine, but the issue is only with messaging
Fatal Exception: java.lang.RuntimeException: Unable to instantiate service io.invertase.firebase.messaging.RNFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.messaging.RNFirebaseMessagingService"

Please help me to fix this issue

**Comment by ravichandran18390** [comment]
The below code got removed from AndroidManifest.xml and then the issue is fixed

<service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
	<intent-filter>
		<action android:name="com.google.firebase.MESSAGING_EVENT" />
	</intent-filter>
</service>

Thanks
