### ISSUE TITLE
Android crash on receipt of message from FCM (possible resolution)

### ISSUE THREAD

**Issue by dannyshisler** [invertase/react-native-firebase#411]
### Issue

After successfully setting up the library and retrieving my FCM registration token I tried using the Firebase console to send my device a message.  On receipt of the message the app crashed everytime (in foreground and background mode) with nothing in the RN logs.

The Android logs showed the following:
```
09-15 00:49:27.968 2237-4154/com.myapp E/AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1
    Process: com.myapp, PID: 2237
    java.lang.NoSuchMethodError: No static method zzcs(Landroid/content/Context;)Lcom/google/android/gms/internal/zzbdo; in class Lcom/google/android/gms/internal/zzbdp; or its super classes (declaration of 'com.google.android.gms.internal.zzbdp' appears in /data/app/com.myapp-2/base.apk)
        at com.google.android.gms.internal.zzcap.zzit(Unknown Source)
        at com.google.android.gms.internal.zzcbj.zzuh(Unknown Source)
        at com.google.android.gms.internal.zzcdm.initialize(Unknown Source)
        at com.google.android.gms.internal.zzcco.<init>(Unknown Source)
        at com.google.android.gms.internal.zzcco.zzdm(Unknown Source)
        at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source)
        at com.google.firebase.messaging.zzd.zzct(Unknown Source)
        at com.google.firebase.messaging.zzd.zzb(Unknown Source)
        at com.google.firebase.messaging.zzd.zzg(Unknown Source)
        at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
        at com.google.firebase.iid.zzc.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```
I think I've fixed it by leaving the firebase-core reference  in `android/app/build.gradle` 
` compile "com.google.firebase:firebase-core:11.2.2"`
but removing the reference to:
`compile "com.google.firebase:firebase-analytics:11.2.2"`

According to [https://firebase.google.com/docs/android/setup#available_libraries](https://firebase.google.com/docs/android/setup#available_libraries):
> Note: com.google.firebase:firebase-core is a recommended alias for the com.google.firebase:firebase-analytics library.

My assumption is that having both references in the build file was causing problems.

I'm new to Android development so I don't know if this is definitely the case? Perhaps someone else could advise?  But if I'm correct then the documentation should be updated to reflect the potential conflict.

N.B. I think this is a similar issue to the one fixed by https://github.com/invertase/react-native-firebase/pull/309

### Environment

1. Application Target Platform: 
Android

2. Development Operating System: 

3. Build Tools: 

4. React Native version: 
0.47.2

5. RNFirebase Version: 
2.2.0

6. Firebase Module: 
Messaging and analytics

**Comment by chrisbianca** [comment]
I've updated the documentation to remove references to the unnecessary analytics dependency for both Android and iOS.

Thanks for raising.
