### ISSUE TITLE
🔥 [🐛] Not allowed to start service Intent { cmp=.../io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) } without permission Background bind not allowed

### ISSUE THREAD

**Issue by TPXP** [invertase/react-native-firebase#4669]
## Issue
We have crash reports on Crashlytics regarding an exception when trying to start a background job. The issue is probably caused by a crappy vendor software since it only occurs on Wiko VIew 4 and Wiko View 4 Lite devices, but maybe it can be fixed ? The devices are running Android 10

Here's the full stacktrace
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver: java.lang.SecurityException: Not allowed to start service Intent { cmp=.../io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) } without permission Background bind not allowed
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3860)
       at android.app.ActivityThread.access$1500(ActivityThread.java:230)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1930)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:232)
       at android.app.ActivityThread.main(ActivityThread.java:7441)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "postinstall": "jetify"
  },
  ....
  "dependencies": {
    "@react-native-firebase/analytics": "^10.1.0",
    "@react-native-firebase/app": "^10.1.0",
    "@react-native-firebase/auth": "^10.1.0",
    "@react-native-firebase/crashlytics": "^10.1.0",
    "@react-native-firebase/firestore": "^10.1.0",
    "@react-native-firebase/functions": "^10.1.0",
    "@react-native-firebase/messaging": "^10.1.0",
    "@react-native-firebase/remote-config": "^10.1.0",
    "@react-native-firebase/storage": "^10.1.0",
    "react-native-unimodules": "^0.11.0",
    "react": "16.13.1",
    "react-native": "0.63.3"
  }
  ....
}
```

#### `firebase.json` for react-native-firebase v6:

```json
{ "react-native": {
  "crashlytics_debug_enabled": true
} }
```
...Because we like testing crashlytics even in dev

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '10.0'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'OurApp' do
  config = use_native_modules!
  use_unimodules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper - not for CI builds as it takes some build time
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  unless ENV['CI']
    use_flipper!('Flipper' => '0.62.0')
    post_install do |installer|
      flipper_post_install(installer)
    end
  end
end

target 'ImageNotification' do
  pod 'Firebase/Messaging'
end
```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>

#import <UMCore/UMModuleRegistry.h>
#import <UMReactNativeAdapter/UMNativeModulesProxy.h>
#import <UMReactNativeAdapter/UMModuleRegistryAdapter.h>

#import "RNFBMessagingModule.h"

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>
static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@import Firebase;

@implementation AppDelegate

// Make sure to reset the badge number when the app is opened
- (void)applicationDidBecomeActive:(UIApplication *)application
{
  [application setApplicationIconBadgeNumber:0];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  // Initialize Firebase
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  NSDictionary *appProperties = [RNFBMessagingModule addCustomPropsToUserProps:nil withLaunchOptions:launchOptions];
  
  self.moduleRegistryAdapter = [[UMModuleRegistryAdapter alloc] initWithModuleRegistryProvider:[[UMModuleRegistryProvider alloc] init]];
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"Our App" initialProperties:appProperties];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:0.855f green:0 blue:0 alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  return YES;
}

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  NSArray<id<RCTBridgeModule>> *extraModules = [_moduleRegistryAdapter extraModulesForBridge:bridge];
  // You can inject any extra modules that you would like here, more information at:
  // https://facebook.github.io/react-native/docs/native-modules-ios.html#dependency-injection
  return extraModules;
}

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?
I'm not sure, but jetifier is called in our `postinstall` script so I think we've migrated to AndroidX

- [x] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
package com.techx.arya;

import android.app.Application;

import android.content.Context;
import android.content.Intent;

import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import com.facebook.applinks.AppLinkData;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.Arrays;

// React native unimodules
import com.techx.arya.generated.BasePackageList;
import org.unimodules.adapters.react.ModuleRegistryAdapter;
import org.unimodules.adapters.react.ReactModuleRegistryProvider;
import org.unimodules.core.interfaces.SingletonModule;

public class MainApplication extends Application implements ReactApplication {
  private final ReactModuleRegistryProvider mModuleRegistryProvider = new ReactModuleRegistryProvider(new BasePackageList().getPackageList(), Arrays.<SingletonModule>asList());

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());

          // Add unimodules
          List<ReactPackage> unimodules = Arrays.<ReactPackage>asList(
            new ModuleRegistryAdapter(mModuleRegistryProvider)
          );
          packages.addAll(unimodules);

          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("our.app.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="our.app">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <!-- OPTIONAL PERMISSIONS, REMOVE WHATEVER YOU DO NOT NEED -->
    <uses-permission android:name="android.permission.MANAGE_DOCUMENTS" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <!-- These require runtime permissions on M -->
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <!-- END OPTIONAL PERMISSIONS -->

    <!-- I'd like to sell in my app -->
    <uses-permission android:name="com.android.vending.BILLING" />

    <!-- Features we use, put here to tell the play store not to filter devices based on this -->
    <uses-feature android:name="android.hardware.microphone" android:required="false" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />
    <uses-feature android:name="android.hardware.faketouch" android:required="false" />
    <uses-feature android:name="android.hardware.wifi" android:required="false" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:usesCleartextTraffic="true"
      android:theme="@style/AppTheme">
        <activity
          android:name=".MainActivity"
          android:label="@string/app_name"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
          android:launchMode="singleTask"
          android:theme="@style/SplashScreenTheme"
          android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="ourapp"
                      android:host="mobapp" />
            </intent-filter>

        </activity>
        <!-- Expo image picker -->
        <activity
          android:name="com.theartofdev.edmodo.cropper.CropImageActivity"
          android:theme="@style/Base.Theme.AppCompat">
        </activity>

        <!-- Set custom default icon. This is used when no icon is set for incoming notification messages.
             See README(https://goo.gl/l4GJaQ) for more. -->
        <meta-data
          android:name="com.google.firebase.messaging.default_notification_icon"
          android:resource="@drawable/ic_state_ic_notification" />
        <!-- Set color used with incoming notification messages. This is used when no color is set for the incoming
             notification message. See README(https://goo.gl/6BKBk7) for more. -->
        <meta-data
          android:name="com.google.firebase.messaging.default_notification_color"
          android:resource="@color/notificationColor"
          tools:replace="android:resource" />
    </application>
</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 71.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.2.0 - /var/folders/pg/1z2xwlhd0kz2wyv6g_62frdwsw7wbq/T/yarn--1607681891890-0.6818005418993509/node
    Yarn: 1.22.10 - /var/folders/pg/1z2xwlhd0kz2wyv6g_62frdwsw7wbq/T/yarn--1607681891890-0.6818005418993509/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 12.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `10.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging` (v10.1.0)
- **Are you using `TypeScript`?**
  - `No` (we probably should, but that's another story)

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Mmm this seems like a vendor power management thing like https://dontkillmyapp.com but maybe there is something we can help with. We certainly won't be able to test or reproduce though so you'll need to recruit a volunteer if possible then experiment with adding permissions to the androidmanifest.xml and requesting same until it works

Once we have an idea of what would work then we can think about how to accommodate

**Comment by TPXP** [comment]
I wasn't able to get the device to experiment with, but I believe it can be useful to some. Hopefully we will gather feedback

**Comment by AndroidDeveloperLB** [comment]
I got this same issue on "View Max Pro" by "QMobile" running Android 10.
Any idea of a workaround of this?
Something to add to the manifest?

**Comment by mikehardy** [comment]
There is no effective workaround when vendors break Android APIs. https://dontkillmyapp.com

**Comment by AndroidDeveloperLB** [comment]
@mikehardy I was hoping that maybe I could add something to the manifest.

**Comment by mikehardy** [comment]
I was hoping Android vendors would implement the Android platform, but hope doesn't ship apps...

**Comment by Sumit-Budhiraja** [comment]
Any updates/solutions for fixing this one.?

**Comment by mikehardy** [comment]
@Sumit-Budhiraja there is no workaround for broken android implementations. You probably need to find a react-native package that exposes whether power saving is on or not for your app, and if it is, educate the user about why they need to turn that off for your app, then send them to the power settings control panel. Sort of like what we (Invertase) do here https://notifee.app/react-native/docs/android/background-restrictions

**Comment by dev-vrajesh** [comment]
Hello everyone, I faced the same issue,  
Stack: 
 E/RNFirebaseMsgReceiver: Background messages only work if the message priority is set to 'high'

` android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.fo.dev.praguecity/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: app is in background uid UidRecord{63042e7 u0a149 RCVR idle change:uncached procs:0 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1861)
        at android.app.ContextImpl.startService(ContextImpl.java:1817)
        at android.content.ContextWrapper.startService(ContextWrapper.java:774)
        at android.content.ContextWrapper.startService(ContextWrapper.java:774)
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver.onReceive(ReactNativeFirebaseMessagingReceiver.java:53)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4308)
        at android.app.ActivityThread.access$1600(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2064)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

` Any solution find?

**Comment by mikehardy** [comment]
@dev-vrajesh you have a different issue, read your error message carefully, as it contains your solution (web search for firebase how to set message priority to high)
