### ISSUE TITLE
[🐛🔥] NullPointerException Firebase Crashlytics

### ISSUE THREAD

**Issue by trizin** [invertase/react-native-firebase#4706]
## Issue
Hello! I'm using react native firebase in my app. I've discovered the issue while viewing crashlytics reports. Also some user reported that the app is crashing. The issue occurs on a few amount of devices.

Crashlytics logs:
`Error: Exception in HostObject::get(propName:RNFBUtilsModule): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference, stack: <unknown>@787:648 assign@-1 v@653:1922 N@653:1993 N@-1 createModuleNamespace@653:464 <unknown>@786:1265 v@2:1473 <unknown>@785:220 v@2:1473 <unknown>@403:368 v@2:1473 <unknown>@6:57 v@2:1473 d@2:875 global code@795:3`
```
Fatal Exception: com.facebook.react.common.JavascriptException: 
Error: Exception in HostObject::get(propName:RNFBUtilsModule): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference, stack:
<unknown>@787:648
assign@-1
v@653:1922
N@653:1993
N@-1
createModuleNamespace@653:464
<unknown>@786:1265
v@2:1473
<unknown>@785:220
v@2:1473
<unknown>@403:368
v@2:1473
<unknown>@6:57
v@2:1473
d@2:875
global code@795:3

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:818)
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
  "@react-native-firebase/app": "^10.1.0",
    "@react-native-firebase/crashlytics": "^10.1.1",
    "@react-native-firebase/firestore": "^10.1.1",
    "@react-native-firebase/messaging": "^10.1.1",
    "@react-native-firebase/remote-config": "^10.1.1",
    "@react-native-firebase/storage": "^10.1.1",
 "react": "16.13.1",
    "react-native": "0.63.4",
```

</details>

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [X] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```
(I'll update these soon)

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [X] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^10.1.0`
- **Are you using `TypeScript`?**
  - `N`

</p>
</details>

**Comment by mikehardy** [comment]
Largely skipped the template, hard to help, sorry
Please update to 10.3.1 and try to reproduce
If you can reproduce this with https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh and an App.js that we can drop in it, we can try to reopen and look

But this looks like some javascript level error specific to your project, using a react-native-firebase method but on some incorrect file path or something configured for your project?

**Comment by LittoCats** [comment]
This issue is going on version 11.0.0;

This is causeed by the java module [`io.invertase.firebase.utils.ReactNativeFirebaseUtilsModule`](https://github.com/invertase/react-native-firebase/blob/master/packages/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java);

Line 164: `constants.put(KEY_DOCUMENT_DIRECTORY, context.getExternalFilesDir(null).getAbsolutePath());` maybe throw NullPointerException because the return value of `context.getExternalFilesDir` is `@Nullable`

Please reopen this issue and fix it.

**Comment by LittoCats** [comment]
```
  @Override
  public Map<String, Object> getConstants() {
    Map<String, Object> constants = new HashMap<>();

    constants.put("isRunningInTestLab", isRunningInTestLab());
    constants.put("androidPlayServices", getPlayServicesStatusMap());

    Context context = getReactApplicationContext();
    constants.put(KEY_MAIN_BUNDLE, "");
    constants.put(KEY_LIBRARY_DIRECTORY, context.getFilesDir().getAbsolutePath());
    constants.put(KEY_TEMP_DIRECTORY, context.getCacheDir().getAbsolutePath());
    constants.put(KEY_CACHE_DIRECTORY, context.getCacheDir().getAbsolutePath());


    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      constants.put(KEY_DOCUMENT_DIRECTORY, context.getExternalFilesDir(null).getAbsolutePath());
    } else {
      constants.put(KEY_DOCUMENT_DIRECTORY, context.getFilesDir().getAbsolutePath());
    }

    constants.put(KEY_PICS_DIRECTORY, Environment
      .getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)
      .getAbsolutePath());

    constants.put(KEY_MOVIES_DIRECTORY, Environment
      .getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES)
      .getAbsolutePath());

    File externalStorageDirectory = Environment.getExternalStorageDirectory();
    if (externalStorageDirectory != null) {
      constants.put(KEY_EXT_STORAGE_DIRECTORY, externalStorageDirectory.getAbsolutePath());
    }

    File externalDirectory = context.getExternalFilesDir(null);
    if (externalDirectory != null) {
      constants.put(KEY_EXTERNAL_DIRECTORY, externalDirectory.getAbsolutePath());
    }

    return constants;
  }
```

should be replaced with: 

```
  @Override
  public Map<String, Object> getConstants() {
    Map<String, Object> constants = new HashMap<>();

    constants.put("isRunningInTestLab", isRunningInTestLab());
    constants.put("androidPlayServices", getPlayServicesStatusMap());

    Context context = getReactApplicationContext();
    constants.put(KEY_MAIN_BUNDLE, "");
    constants.put(KEY_LIBRARY_DIRECTORY, context.getFilesDir().getAbsolutePath());
    constants.put(KEY_TEMP_DIRECTORY, context.getCacheDir().getAbsolutePath());
    constants.put(KEY_CACHE_DIRECTORY, context.getCacheDir().getAbsolutePath());


    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      File externalDirectory = context.getExternalFilesDir(null);
        if (externalDirectory != null) {
          constants.put(KEY_EXTERNAL_DIRECTORY, externalDirectory.getAbsolutePath());
        }
    } else {
      constants.put(KEY_DOCUMENT_DIRECTORY, context.getFilesDir().getAbsolutePath());
    }

    constants.put(KEY_PICS_DIRECTORY, Environment
      .getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)
      .getAbsolutePath());

    constants.put(KEY_MOVIES_DIRECTORY, Environment
      .getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES)
      .getAbsolutePath());

    File externalStorageDirectory = Environment.getExternalStorageDirectory();
    if (externalStorageDirectory != null) {
      constants.put(KEY_EXT_STORAGE_DIRECTORY, externalStorageDirectory.getAbsolutePath());
    }

    return constants;
  }
```

**Comment by mikehardy** [comment]
PRs happily accepted!

**Comment by mikehardy** [comment]
Nearly fixed thanks to @LittoCats efforts - only a question of getting #5118 in shape and merging
