### ISSUE TITLE
react-native-firebase-messaging in jitsi-meet crash when app in background

### ISSUE THREAD

**Issue by bhavesh18** [invertase/react-native-firebase#4802]
Project used: https://github.com/jitsi/jitsi-meet
I cloned the jitsi-meet project and tried to use the @react-native-firebase/messaging and getting following crash when app goes to background.(working well when app in foreground)

npm package:
"@react-native-firebase/app": "^10.4.0",
"@react-native-firebase/messaging": "^10.4.1",
Reference: https://rnfirebase.io/messaging/usage

Unable to start service io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService@c592dc0 with Intent { cmp=org.jitsinotification.meet/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3722)
at android.app.ActivityThread.access$1700(ActivityThread.java:200)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6810)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.facebook.react.ReactApplication
at com.facebook.react.HeadlessJsTaskService.getReactNativeHost(HeadlessJsTaskService.java:166)
at com.facebook.react.HeadlessJsTaskService.startTask(HeadlessJsTaskService.java:97)
at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:48)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3700)

<img width="1329" alt="Screenshot 2021-01-17 at 6 37 23 PM" src="https://user-images.githubusercontent.com/22396203/105169068-ffa57480-5b40-11eb-9a18-aea410a01ff4.png">

**Comment by mikehardy** [comment]
You'll have to take this up with JitsiMeet
Doesn't look like their Activity extends the expected superclass https://github.com/jitsi/jitsi-meet/blob/61037b982b2c4cc42b65c57caf7091328fcf24dd/android/app/src/main/java/org/jitsi/meet/MainActivity.java#L50

**Comment by bhavesh18** [comment]
Do you have any hack to overcome this problem?

**Comment by mikehardy** [comment]
no, it is not related to react-native-firebase as far as I can tell

**Comment by iim-norse** [comment]
somebody have solution ?

**Comment by iim-norse** [comment]
i write how i fix this here: https://github.com/jitsi/jitsi-meet/issues/8431#issuecomment-1077728063
