### ISSUE TITLE
App Crash on Android version 4.3

### ISSUE THREAD

**Issue by sonivaibhav27** [invertase/react-native-firebase#5062]
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: com.google.android.gms.internal.ads.zzzt
	at com.google.android.gms.ads.MobileAdsInitProvider.<init>(com.google.android.gms:play-services-ads-lite@@19.7.0:2)
	at java.lang.Class.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1130)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5107)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
	at android.app.ActivityThread.access$1400(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(Activi tyThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)

Versions
    "@react-native-firebase/admob": "^10.5.1",
    "@react-native-firebase/app": "^10.5.0",
    "react-native": "0.63.4",
I have followed all the steps in the installation guide

**Comment by WadhahEssam** [comment]
I don't know if this issue is a rn-firebase issue, or an android issue, but it sure needs some serious investigations. 

tons of my users are not able to use the app at all in android, including me.

and this happens when I open a screen that has any admob ad including (initiating interstitial, showing banners).

someone in stakeoverflow suggested that updating chrome helped solving the issue, and I tried it and it worked.

https://stackoverflow.com/questions/46747775/firebase-firestore-get-key-with-collection-add

**Comment by WadhahEssam** [comment]
a lesson learned from this, maybe ads visibility should be toggled throw a remote config value to avoid this in the future.

**Comment by mikehardy** [comment]
@WadhahEssam are you related profesionally to @sonivaibhav27 at all, or are you hijacking this thread?

@sonivaibhav27 you have not provided the details in the template, so I'm closing this.

When I see "NoClassDefFound" errors on Android 4.x I immediately think "they've probably not implemented multidex" - https://rnfirebase.io/#android-enabling-multidex

Without the template information though there is nothing to go on, I will close the issue.

**Comment by WadhahEssam** [comment]
@mikehardy 

https://user-images.githubusercontent.com/24798045/112153836-c5b22680-8bf4-11eb-90ff-80fd3e0d6a58.mov

**Comment by mikehardy** [comment]
Check the news. https://www.engadget.com/android-gmail-stop-running-webview-234125352.html

**Comment by WadhahEssam** [comment]
@mikehardy Thank you for this insight, and sorry for the disruption + I am not related to the gentle man who created the issue.
