### ISSUE TITLE
When i tap R on metro after reload it shows the error Exception in native call from js

### ISSUE THREAD

**Issue by osramesh06** [invertase/react-native-firebase#5225]
![Screenshot_20210428_112159 1](https://user-images.githubusercontent.com/40054457/116363148-74fba200-a820-11eb-8649-b0149135f424.jpg)

**Comment by efstathiosntonas** [comment]
same here, out of the sudden.

 logcat: 

```
E/unknown:ReactNative: Tried to remove non-existent frame callback
2021-04-28 12:46:07.742 15167-15494/com.xxx E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at io.invertase.firebase.common.TaskExecutorService.shutdown(TaskExecutorService.java:104)
        at io.invertase.firebase.common.ReactNativeFirebaseModule.onCatalystInstanceDestroy(ReactNativeFirebaseModule.java:92)
        at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:110)
        at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:85)
        at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:362)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:225)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
2021-04-28 12:46:07.742 15167-15494/com.xxxx E/unknown:ReactNative: Exception in native call
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at io.invertase.firebase.common.TaskExecutorService.shutdown(TaskExecutorService.java:104)
        at io.invertase.firebase.common.ReactNativeFirebaseModule.onCatalystInstanceDestroy(ReactNativeFirebaseModule.java:92)
        at com.facebook.react.bridge.ModuleHolder.destroy(ModuleHolder.java:110)
        at com.facebook.react.bridge.NativeModuleRegistry.notifyJSInstanceDestroy(NativeModuleRegistry.java:85)
        at com.facebook.react.bridge.CatalystInstanceImpl$1.run(CatalystInstanceImpl.java:362)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:225)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)

```

**Comment by mikehardy** [comment]
Well, a stack trace from logcat with the version gets bonus points, that helps us actually locate the issue. v11.3.x has a new high-performance task core that allows parallel execution but, it's new, and things that are hard to test (like hot reloads) are edge cases I'd expect to see some bugs in. ConcurrentModificationException issues are typically easy to fix though, let me see

**Comment by mikehardy** [comment]
Reproduced locally, fixing

**Comment by mikehardy** [comment]
next release will have it, just pending CI and I'll release a fix for this one

In the meantime you may get moving locally if you grab the [patch-package](https://github.com/ds300/patch-package) patch set from the artifacts list on this CI action https://github.com/invertase/react-native-firebase/actions/runs/794045768#artifacts

**Comment by efstathiosntonas** [comment]
@mikehardy it works as a charm now, thanks for your hard work!

**Comment by mikehardy** [comment]
Release 11.4.1 just went out with the change related to this among other fixes + features. Enjoy! :rocket:
