### ISSUE TITLE
Android: Cannot find selected module for constraint platform-runtime -> com.google.firebase:firebase-iid:21.0.1

### ISSUE THREAD

**Issue by alex-mironov** [invertase/react-native-firebase#5293]
I'm getting this weird error when trying to build the app on android, ios works fine though:
`Corrupt serialized resolution result. Cannot find selected module (438) for constraint platform-runtime -> com.google.firebase:firebase-iid:21.0.1`

Below are the versions I'm using:
_package.json_
```
    "@react-native-firebase/analytics": "^10.8.1",
    "@react-native-firebase/app": "^10.8.1",
```

_android/build.gradle_

```
    dependencies {
...
        classpath 'com.google.gms:google-services:4.3.2'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.1.1'
    }
```

_android/app/build.gradle_
```
dependencies {
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
    implementation 'com.google.android.gms:play-services-tagmanager:17.0.0'
...
}
```
Any guidance would be highly appreciated. Thanks.

**Comment by mikehardy** [comment]
Hi there, old versions of react-native-firebase and the gradle plugins please update

Hard dependency on analytics not necessary I think, may need to use our iid module as well? Make sure tag manager dependency is compatible with firebase, admob just did a breaking change on the native side and we are not ready to cross the major version increase yet

Our tests app is a good example of current dependencies as is my rnfbdemo/make-demo.sh script (search here for it to grab the link I'm mobile right now sorry)

**Comment by ozymand1as** [comment]
I'm now getting the same error on 11.4.1. [Other FCM libraries](https://github.com/zo0r/react-native-push-notification/issues/1979) started to have the same problem a few hours ago. Seems to be related to the updated version of firebase-messaging. Apparent workaround can be found [here](https://github.com/zo0r/react-native-push-notification/issues/1979#issuecomment-839746868).

**Comment by mikehardy** [comment]
I'll pin this issue on our issues list for others though - appears to be all of the sudden popular!

**Comment by kuznetsov-from-wonderland** [comment]
My app crashes

```
Name
FATAL EXCEPTION: pool-20-thread-1

Reason
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~owrZHV8tp9z-ri1ISMKZjQ==/app.xxx.yyy-DwoMc8cyBFdfvdATt7GVtA==/base.apk"],nativeLibraryDirectories=[/data/app/~~owrZHV8tp9z-ri1ISMKZjQ==/app.xxx.yyy-DwoMc8cyBFdfvdATt7GVtA==/lib/arm64, /data/app/~~owrZHV8tp9z-ri1ISMKZjQ==/app.xxx.yyy-DwoMc8cyBFdfvdATt7GVtA==/base.apk!/lib/arm64-v8a, /system/lib64]]

Stacktrace
FATAL EXCEPTION: pool-20-thread-1

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:120)
at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$LUheXkbDzdlAr-7YkGRwRuErEUc.call(Unknown Source:4)
at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
```

**Comment by kuznetsov-from-wonderland** [comment]
```
    "@react-native-firebase/analytics": "^11.4.1",
    "@react-native-firebase/app": "^11.4.1",
    "@react-native-firebase/crashlytics": "^11.4.1",
    "@react-native-firebase/messaging": "^11.4.1",
    ```

**Comment by kuznetsov-from-wonderland** [comment]
I guess the reason is the same

**Comment by ozymand1as** [comment]
Have you tried pinning the firebase-messaging version in android/build.gradle?
`buildscript {
    ext {
        ***
        firebaseMessagingVersion = "21.1.0"
    }
}`

**Comment by gluons** [comment]
@ozymand1as As [maintainer of `react-native-push-notification` said](https://github.com/zo0r/react-native-push-notification/issues/1979#issuecomment-839755772).

> I do not recommend you to downgrade the firebase-messaging version to v21
> This will keep you stuck into old version never patched

So, it's workaround for temporary fix.

We should have some solution for the latest version of every packages/dependencies.

**Comment by ozymand1as** [comment]
Certainly, this can't be considered a proper solution, but it will at least let the apps run without crashing on launch.
Should this issue be reopened?

**Comment by tastafur** [comment]
> My app crashes
> 
> ```
> Name
> FATAL EXCEPTION: pool-20-thread-1
> 
> Reason
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/data/app/~~owrZHV8tp9z-ri1ISMKZjQ==/app.xxx.yyy-DwoMc8cyBFdfvdATt7GVtA==/base.apk"],nativeLibraryDirectories=[/data/app/~~owrZHV8tp9z-ri1ISMKZjQ==/app.xxx.yyy-DwoMc8cyBFdfvdATt7GVtA==/lib/arm64, /data/app/~~owrZHV8tp9z-ri1ISMKZjQ==/app.xxx.yyy-DwoMc8cyBFdfvdATt7GVtA==/base.apk!/lib/arm64-v8a, /system/lib64]]
> 
> Stacktrace
> FATAL EXCEPTION: pool-20-thread-1
> 
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
> at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:120)
> at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$LUheXkbDzdlAr-7YkGRwRuErEUc.call(Unknown Source:4)
> at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:923)
> ```

I have this same problem but I do not understand why I can use the workaround you say but it is dangerous, but why does this problem occur?

**Comment by mikehardy** [comment]
if a module (like react-native-push-notifications) depends on an [unconstrained `+` version range](https://github.com/zo0r/react-native-push-notification/blob/7315f4362edea523d4abba69baad72f80801b391/android/build.gradle#L58) (which is the actual dangerous thing, [and should never be done](https://stackoverflow.com/a/57775759/9910298))

Then even a well-tested module that cautiously pins the dependency to a known-good version ([like we do here](https://github.com/invertase/react-native-firebase/blob/98ed88f170eb1a0da6781ebc8bd57e3c7a1597a4/packages/app/android/build.gradle#L80) using [a central version definition](https://github.com/invertase/react-native-firebase/blob/98ed88f170eb1a0da6781ebc8bd57e3c7a1597a4/packages/app/package.json#L72) that relies on [a tested-together set](https://firebase.google.com/docs/android/learn-more#bom)) will have the unconstrained dependency leak in [like this](https://github.com/invertase/react-native-firebase/pull/5189)

And then you will have incompatibilities, even if you try your best to only release versions that use well-tested, version-specified dependencies.

It's quite frustrating.

This module and your project is the collateral damage of poor dependency management in your other modules. Please complain to them.

**Comment by mikehardy** [comment]
(as a side note - other modules may not want the hassle of doing real semantic versioning, which is required by depending on real versions internally vs `+` and implies doing real release notes and bumping major versions and checking for incompatibilities - that's fine, they can take that stance but it is shirking duty in my opinion - what they are saying is "you the library consumer are responsible for managing breaking change releases on our internal dependencies and will have to occasionally put in build.gradle verison pins". Lobby them to change their policy and include dependency breaking changes in their sem-ver consideration, or choose different libraries that don't put the complexity on you the library consumer)

**Comment by watadarkstar** [comment]
Is this a live chat or a Github ticket? 👍  Haha nice response times @mikehardy

**Comment by wayne-tt** [comment]
Because of the QA schedule, I was in a hurry to successfully build.

add a line " implementation 'com.google.firebase:firebase-iid:21.0.0' " to ./android/app/build.gradle

**Comment by gluons** [comment]
@wayne-tt I guess it's because [`com.google.firebase:firebase-messaging`](https://firebase.google.com/support/release-notes/android#messaging_v22-0-0) release v22. It has breaking change.

And previous `react-native-push-notification` version use `+`. So, it'll install the latest `com.google.firebase:firebase-messaging` that have breaking change.

**Comment by alex-mironov** [comment]
Bumped the versions
_android/build.gradle_
```
-        classpath 'com.google.gms:google-services:4.3.2'
+        classpath 'com.google.gms:google-services:4.3.5'
```

_package.json_
```
-    "@react-native-firebase/analytics": "^10.8.1",
-    "@react-native-firebase/app": "^10.8.1",
-    "@react-native-firebase/crashlytics": "^10.8.1",
-    "@react-native-firebase/messaging": "^10.8.1",
-    "@react-native-firebase/remote-config": "^10.8.1",
+    "@react-native-firebase/analytics": "^11.4.1",
+    "@react-native-firebase/app": "^11.4.1",
+    "@react-native-firebase/crashlytics": "^11.4.1",
+    "@react-native-firebase/messaging": "^11.4.1",
+    "@react-native-firebase/remote-config": "^11.4.1",
...
-    "react-native-push-notification": "^3.1.9",
+    "react-native-push-notification": "^7.3.1",
```

Removed explicit link to firebase-analytics
```
-    implementation 'com.google.firebase:firebase-analytics:17.2.0'
```

Seems to be working.

**Comment by xkevin190** [comment]
my project still is failed, first i updated react-native-push-notification `v7.3.1 ` and added `classpath 'com.google.gms:google-services:4.3.5'` and i have 

 "@react-native-firebase/analytics": "^11.4.1",
  "@react-native-firebase/app": "^11.4.1",
  "@react-native-firebase/crashlytics": "^11.4.1",
  "@react-native-firebase/messaging": "^11.4.1",
 "@react-native-firebase/remote-config": "^11.4.1",

i have this error: 

```
E/FirebaseCrashlytics: .
    .     |  | 
    .     |  |
    .     |  |
    .   \ |  | /
    .    \    /
    .     \  /
    .      \/
    .
    The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
    .
    .      /\
    .     /  \
    .    /    \
    .   / |  | \
    .     |  |
I/chatty: uid=10327(com.habitsv2) identical 1 line
E/FirebaseCrashlytics: .     |  |
    .
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.habitsv2, PID: 7703
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at android.app.ActivityThread.installProvider(ActivityThread.java:7191)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6669)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6586)
        at android.app.ActivityThread.access$1500(ActivityThread.java:233)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7561)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:125)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:207)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:54)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.access$lambda$0(Unknown Source:0)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar$$Lambda$1.create(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$ComponentRuntime(ComponentRuntime.java:132)
        at com.google.firebase.components.-$$Lambda$ComponentRuntime$CLI-XObGztS2iu7RD22eoA3PpJU.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2117)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2091)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7186)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6669) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6586) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:233) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7561) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 


```

**Comment by mikehardy** [comment]
@xkevin190 that issue is unrelated, it seems more like a basic crashlytics installation issue, possibly need a fresh google-services.json from firebase console or similar. Unknown. Investigate construction / installation of a clean app https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by mikehardy** [comment]
react-native-firebase v12 has been released which uses the new underlying firebase-android-sdk / firebase-ios-sdk versions and should be compatible with future versions of react-native-push-notifications that share the set of dependencies - @Dallas62 - thanks for working across repos working through the breaking changes in the underlying SDK releases

**Comment by hongzhou85** [comment]
ReactNativeFirebaseMessagingModule.lambda$getToken$2 (ReactNativeFirebaseMessagingModule.java:120)

I'm seeing this error too when my app runs, which is the working versions that would not conflict?

**Comment by mikehardy** [comment]
@hongzhou85 the most current versions of both react-native-firebase and react-native-push-notifications I *think*? I'm not as familiar with react-native-push-notifications but I *think* they are using or can use firebase-android-sdk v27+ (v28 is current) which would resolve this when used with react-native-firebase v12+ and firebase-android-sdk v28+

**Comment by hongzhou85** [comment]
Thanks @mikehardy , I'm going to try this and post back on it again
