### ISSUE TITLE
React Native App crashed Unfortunately  

### ISSUE THREAD

**Issue by ElangoPrince** [invertase/react-native-firebase#5300]
React native app crashed unfortunately. Working fine but suddenly it's happened. When I'm trying to run my project I'm getting following error. 
```
  2021-05-12 20:47:17.560 12374-13197/..... E/AndroidRuntime: FATAL EXCEPTION: pool-13-thread-1
    Process: ....., PID: 12374
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:116)
        at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call(Unknown Source:4)
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.iid.FirebaseInstanceId" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/.....-f3FhjOZe-tG0r9Ee4AHX7g==/base.apk"],nativeLibraryDirectories=[/data/app/.....-f3FhjOZe-tG0r9Ee4AHX7g==/lib/arm64, /data/app/.....-f3FhjOZe-tG0r9Ee4AHX7g==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingModule.lambda$getToken$2(ReactNativeFirebaseMessagingModule.java:116) 
        at io.invertase.firebase.messaging.-$$Lambda$ReactNativeFirebaseMessagingModule$Vj2oWQrpOl3AM5fw0hvH-cnu3p8.call(Unknown Source:4) 
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```
    
This is my package information:

    "@react-native-firebase/app": "^10.0.0",
    "@react-native-firebase/messaging": "^10.0.0",
    "react-native-push-notification": "^7.1.1",

**Comment by mikehardy** [comment]
Duplcate #5293  - react-native-push-notification is including unpinned android dependencies and they are not compatible here. We're working on forward-porting and there's a workaround in linked issue

**Comment by ElangoPrince** [comment]
Finally this thread helping me [https://github.com/zo0r/react-native-push-notification/issues/1979#issuecomment-839746868]
Thanks !
