### ISSUE TITLE
[🐛] Bug Installing Firebase Bug 

### ISSUE THREAD

**Issue by medonagy45** [invertase/react-native-firebase#5342]
I get the following error while running pod install 

`[!] Error installing Firebase

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――   

### Command

```
C:/Ruby30-x64/bin/pod install --repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]
    RubyGems : 3.2.15
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.23.0.windows.1
Ruby lib dir : C:/Ruby30-x64/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 90ef574581ae8dece3d171baaf801abf6570f181

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'



target 'BankSms' do

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods       
    :hermes_enabled => false
  )
  target 'BankSmsTests' do
    inherit! :complete
    # Pods for testing
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and        
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ dir_s_mkdir - C:/Users/UNTITLED/Library/Caches/CocoaPods/Pods/Release/Firebase/7.11.0-c121f/FirebaseInAppMessaging/Tests/Integration/FunctionalTestApp/ExternalAppExample/fiam-external-ios-testing-app/fiam-external-ios-testing-app/Assets.xcassets/AppIcon.appiconset
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1385:in `mkdir'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1385:in `copy'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:500:in `block in copy_entry'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1513:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:497:in `copy_entry'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:471:in `block in cp_r'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'       
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
C:/Ruby30-x64/lib/ruby/3.0.0/fileutils.rb:470:in `cp_r'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:157:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:42:in `download'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:561:in `install_source_of_pod'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:512:in `block (2 levels) in install_pod_sources'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:511:in `block in install_pod_sources'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `each'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `install_pod_sources'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:253:in `block in download_dependencies'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:252:in `download_dependencies'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:161:in `install!'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
C:/Ruby30-x64/bin/pod:23:in `load'
C:/Ruby30-x64/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――   

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+dir_s_mkdir+-+C%3A%2FUsers%2FUNTITLED%2FLibrary%2FCaches%2FCocoaPods%2FPods%2FRelease%2FFirebase%2F7.11.0-c121f%2FFirebaseInAppMessaging%2FTests%2FIntegration%2FFunctionalTestApp%2FExternalAppExample%2Ffiam-external-ios-testing-app%2Ffiam-external-ios-testing-app%2FAssets.xcassets%2FAppIcon.appiconset&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass`

the package.json file 

`{
  "name": "bank-message",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-firebase/admob": "^11.2.0",
    "@react-native-firebase/analytics": "^11.2.0",
    "@react-native-firebase/app": "^11.2.0",
    "react": "17.0.1",
    "react-native": "^0.64.0",
    "react-native-i18n": "^2.0.15",
    "react-native-iap": "^5.2.13",
    "react-native-modal": "^11.7.0",
    "react-native-rate": "^1.2.4",
    "react-native-ratings": "^7.6.1",
    "rmc-picker": "^5.0.10"
  },
  "devDependencies": {
    "@babel/core": "^7.13.14",
    "@babel/runtime": "^7.13.10",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.23.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "prettier": "^2.2.1",
    "react-native-clean-project": "^3.6.3"
  }
}
`
pod --version -->1.10.1

**Comment by mikehardy** [comment]
This is a ruby issue it appears, there will not be a change in this module as a result of any resolution of this.
There is something wrong in your local environment I think. sorry. Also, you should try with current stable versions, not v11.2

**Comment by medonagy45** [comment]
I am using windows ,could that be the reason ???

**Comment by mikehardy** [comment]
Maybe? It works on windows though. I used the WSL and made https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh work on it before - read that script for comments on where you need to run in WSL vs when you may stop and use native windows tools. I don't recall having any problems at all, except with the way my script uses `sed`, thus the use of WSL for parts of the script.
