### ISSUE TITLE
[🐛] jest unable to mock crashlytics (in time?)

### ISSUE THREAD

**Issue by Pinwheeler** [invertase/react-native-firebase#5511]
🔥

## Issue

Been using `@react-native-firebase` `app`, `messaging`,  and `admob` in my test environment for awhile now. I just added Crashlytics and my tests aren't running.

```  ● Test suite failed to run

    You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.app().

    Ensure you have either linked the module or added it to your projects Podfile.

    See http://invertase.link/ios for full setup instructions.

```

## Jest config

```javascript
const { pathsToModuleNameMapper } = require("ts-jest/utils")
const { compilerOptions } = require("./tsconfig")

module.exports = {
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: "<rootDir>/",
  }),
  projects: [
    {
      name: "react",

      preset: "react-native",
      testMatch: ["<rootDir>/src/**/__tests__/**"],
      testPathIgnorePatterns: ["<rootDir>/__tests__/helpers"],
      transformIgnorePatterns: ["node_modules/native-base/"],
      moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
        prefix: "<rootDir>/",
      }),
      setupFilesAfterEnv: [
        "<rootDir>/__test_helpers__/mockFirebase.js",
        "<rootDir>/__test_helpers__/mockNavigation.js",
        "<rootDir>/__test_helpers__/misc_setup.js",
      ],
    },
  ],
}
```

## mockFirebase (mentioned in jest config)

```javascript
console.log("&&&&&&&&&&&&&&&& MOCKING FIREBASE")
jest.mock("react-native/Libraries/EventEmitter/NativeEventEmitter")
jest.mock("@react-native-firebase/crashlytics")
jest.mock("@react-native-firebase/app", () => {
  return () => ({
    onNotification: jest.fn(),
    onNotificationDisplayed: jest.fn(),
  })
})
```

potentially relevant- my debugging console statement appears AFTER the failure in question.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "plenti",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "ENVFILE=.env.staging react-native run-android --variant=betaDebug",
    "android:staging": "ENVFILE=.env.staging react-native run-android --variant=betaStagingRelease",
    "android:prod": "ENVFILE=.env.production react-native run-android --variant=betaRelease",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "start:clean": "react-native start --reset-cache",
    "lint": "eslint '**/*.ts*' --fix",
    "test": "jest",
    "test:ci": "jest --maxWorkers=2",
    "build": "tsc"
  },
  "format": "prettier --write \"src/**/*.ts\" \"src/**/*.js\"",
  "lint": "tslint -p tsconfig.json",
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-native-community/slider": "^2.0.9",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-native-firebase/admob": "^11.5.0",
    "@react-native-firebase/app": "^11.5.0",
    "@react-native-firebase/crashlytics": "^11.5.0",
    "@react-native-firebase/messaging": "^11.5.0",
    "@react-navigation/drawer": "^5.11.4",
    "@react-navigation/material-bottom-tabs": "^5.3.10",
    "@react-navigation/material-top-tabs": "^5.3.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "@types/lodash": "^4.14.165",
    "@types/react": "^16.14.2",
    "@types/react-native": "^0.64.8",
    "@types/react-native-vector-icons": "^6.4.6",
    "@types/yup": "^0.26.36",
    "aws-sdk": "^2.876.0",
    "axios": "^0.21.1",
    "axios-logger": "^2.4.0",
    "base64-arraybuffer": "^0.2.0",
    "compare-versions": "^3.6.0",
    "formik": "^2.2.5",
    "geolib": "^3.2.1",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "plenti-api": "^1.0.58",
    "react": "^17.0.1",
    "react-native": "^0.64.2",
    "react-native-code-push": "^7.0.1",
    "react-native-config": "^1.4.2",
    "react-native-device-info": "^5.6.5",
    "react-native-fs": "^2.16.6",
    "react-native-iap": "^5.2.13",
    "react-native-iaphub": "^6.1.5",
    "react-native-image-picker": "^3.3.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-open-maps": "^0.3.6",
    "react-native-paper": "^4.9.1",
    "react-native-permissions": "^3.0.4",
    "react-native-push-notification": "^7.3.1",
    "react-native-swipe-list-view": "^2.5.0",
    "react-native-tab-view": "^2.15.2",
    "react-native-tcp-socket": "^3.5.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-version-info": "^1.1.0",
    "react-navigation-hooks": "^1.1.0",
    "react-navigation-stack": "^2.10.2",
    "yup": "^0.28.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@bam.tech/react-native-make": "^3.0.3",
    "@react-native-community/eslint-config": "^1.1.0",
    "@types/enzyme": "^3.10.8",
    "@types/jest": "^24.9.1",
    "@types/react-test-renderer": "^16.9.4",
    "@typescript-eslint/eslint-plugin": "^4.9.0",
    "@typescript-eslint/parser": "^4.9.0",
    "babel-jest": "^25.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-react": "^7.21.5",
    "jest": "^25.1.0",
    "jest-mock": "^25.5.0",
    "jetifier": "^1.6.6",
    "metro-react-native-babel-preset": "^0.59.0",
    "mockdate": "^2.0.5",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-reanimated": "^2.0.1",
    "react-native-safe-area-context": "^0.6.4",
    "react-native-screens": "^2.15.0",
    "react-native-typescript-transformer": "^1.2.13",
    "react-test-renderer": "^16.14.0",
    "rn-nodeify": "^10.2.0",
    "ts-jest": "^26.5.4",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "^4.1.2"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "admob_android_app_id": "ca-app-pub-8710033578892632~2011851170",
    "admob_ios_app_id": "ca-app-pub-8710033578892632~6609571734"
  },
  "crashlytics_debug_enabled": false,
  "crashlytics_disable_auto_disabler": true,
  "crashlytics_auto_collection_enabled": true,
  "crashlytics_is_error_generation_on_js_crash_enabled": true,
  "crashlytics_javascript_exception_handler_chaining_enabled": false
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'plenti' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  target 'plentiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper! // https://github.com/facebook/react-native/issues/30836
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # Ads
  pod 'GoogleAppMeasurement'
  pod 'Google-Mobile-Ads-SDK'
end

target 'plenti-tvOS' do
  # Pods for plenti-tvOS

  target 'plenti-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.1.2')

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files

        // This is an exception https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android&authuser=0
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false)

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "dev.plenti.plenti"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 79
        versionName "2.0.0"
        resValue 'string', "CODE_PUSH_APK_BUILD_TIME", String.format("\"%d\"", System.currentTimeMillis())
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            resValue "string", "CodePushDeploymentKey", '""'
//            resValue "string", "CodePushDeploymentKey", '"eOz7xcRuhR2XWXdGMYH5UThdVeK4uIbANtzr5"'
        }
        stagingRelease {
            resValue "string", "CodePushDeploymentKey", '"eOz7xcRuhR2XWXdGMYH5UThdVeK4uIbANtzr5"'
            signingConfig signingConfigs.release
            // Note: It is a good idea to provide matchingFallbacks for the new buildType you create to prevent build issues
            // Add the following line if not already there
            matchingFallbacks = ['release']
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.release
            resValue "string", "CodePushDeploymentKey", '"5dWzm99Y9p5V9vkMoon6w5IxJWjX4x2kf0dqB"'
        }
    }
    flavorDimensions "environment"
    productFlavors {
        beta {
            resValue "string", "build_config_package", "dev.plenti.plenti"
        }
        prod {
            resValue "string", "build_config_package", "dev.plenti.plenti"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation project(':@react-native-community_slider')
    implementation project(':@react-native-community_geolocation')
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    // google ads
    implementation 'com.google.android.gms:play-services-ads:19.8.0'

    // ReactNative Navigation
    implementation 'androidx.appcompat:appcompat:1.3.0-alpha02'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.2.0-alpha01'

    // IAP
    implementation "com.android.billingclient:billing:3.0.2"

    implementation 'me.leolin:ShortcutBadger:1.1.22@aar'

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/"
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

project.ext.vectoricons = [
        iconFontNames: [ 'MaterialCommunityIcons.ttf', 'EvilIcons.ttf' ] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
// https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android&authuser=0
apply plugin: 'com.google.firebase.crashlytics'
// https://invertase.io/oss/react-native-firebase/quick-start/android-firebase-credentials
apply plugin: 'com.google.gms.google-services'

```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'plenti'
include ':@react-native-community_slider'
project(':@react-native-community_slider').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/slider/android')
include ':@react-native-community_geolocation'
project(':@react-native-community_geolocation').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/geolocation/android')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
include ':@react-native-community_async-storage'
project(':@react-native-community_async-storage').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/async-storage/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app', ':react-native-code-push'
project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')

```

#### `MainApplication.java`:

```java
package dev.plenti.plenti;

import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;

import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;

import java.lang.reflect.InvocationTargetException;
import java.util.List;

import com.microsoft.codepush.react.CodePush;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

        @Override
        protected String getJSBundleFile() {
            return CodePush.getJSBundleFile();
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.rndiffapp.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}

```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="dev.plenti.plenti">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <!-- Sample AdMob App ID: ca-app-pub-3940256099942544~3347511713 -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-8710033578892632~2011851170"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 84.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.18.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/anthonydreessen/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.1 => 17.0.1
    react-native: ^0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
  - [ x] Neither- pure NPM issue
- **`react-native-firebase` version you're using that has this issue:**
  - 11.5.0
- **`Firebase` module(s) you're using that has the issue:**
  - Crashlytics
- **Are you using `TypeScript`?**
  -  Y ^4.1.2

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!
Have you considered simply using our mock file? It should work https://github.com/invertase/react-native-firebase/blob/master/jest.setup.ts

...at least I think it should. Curious to hear

**Comment by Pinwheeler** [comment]
not sure exactly what that did, but it seems to be breaking some other parts of the tests due to missing some react-native properties?

I'm assuming that what I should be doing is adding this mock as a `setupFilesAfterEnv` file?

```bash
  ● ForgotPasswordForm › has some form items

    TypeError: Cannot read property 'medium' of undefined

      at Component (node_modules/react-native-paper/lib/commonjs/components/Button.tsx:175:3)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7918:13)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9019:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12649:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12622:22)
      at callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12333:9)
      at eventHandler (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1825:24)
      at Scheduler_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1775:10)

  ● ForgotPasswordForm › has some form items

    TypeError: Cannot read property 'props' of undefined

      39 |
      40 |   it("has some form items", () => {
    > 41 |     expect(emailField.props.label).toEqual("Email")
         |                       ^
      42 |     expect(emailField.props.name).toEqual("email")
      43 |     expect(textOf(button)).toEqual("Reset Password")
      44 |   })

      at Object.<anonymous> (src/account/__tests__/ForgotPasswordForm.test.tsx:41:23)
```

**Comment by Pinwheeler** [comment]
I ended up having to write a wrapper with conditional imports. Maybe it's not the best way, but it's a way!

```typescript
import { AccountEntity } from "plenti-api"
import { Environment } from "./Environment"
import { MockCrashlytics } from "./__mocks__/MockCrashlytics"

export class LoggerService {
  private static _instance: LoggerService

  static instance() {
    if (!this._instance) {
      this._instance = new LoggerService()
    }

    return this._instance
  }

  private async _crashlytics(): Promise<any> {
    if (!Environment.get().TESTING) {
      // Don't import crashlytics
      const module = await import("@react-native-firebase/crashlytics")
      return module.default()
    } else {
      return Promise.resolve(MockCrashlytics)
    }
  }

  async error(err: Error, jsErrorName?: string, logToConsole: boolean = false) {
    if (logToConsole) {
      // eslint-disable-next-line no-console
      console.error(err)
    }
    const c = await this._crashlytics()
    c.recordError(err, jsErrorName)
  }

  async log(message: string, logToConsole: boolean = false) {
    if (logToConsole) {
      // eslint-disable-next-line no-console
      console.log(message)
    }
    const c = await this._crashlytics()
    c.log(message)
  }

  async setAccount(account?: AccountEntity) {
    const c = await this._crashlytics()
    if (account) {
      c.setUserId(account.id.toString())
    } else {
      c.setUserId("-1")
    }
  }

  async setAttributes(attributes: { [key: string]: string }) {
    const c = await this._crashlytics()
    c.setAttributes(attributes)
  }
}
```

**Comment by mikehardy** [comment]
Jest setups are always project-specific, and "a way" that works, works ;-)
Glad you found a way
