### ISSUE TITLE
[🐛] getNativeModule requires @ReactModule - Issue with getNativeModule on Android

### ISSUE THREAD

**Issue by Qwin** [invertase/react-native-firebase#5665]
getting the following error trying to access native module on Android, I am using react-native 0.63 which retrieves modules by annotation @ReactModule(name = "my module name"). Guess the only way for me to retrieve the lib on the native side is if you guys add this to each module in this repo?

It's sad that there isn't a getNativeModule string parameter... :( 

/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company.myapp, PID: 7227
    java.lang.IllegalArgumentException: Could not find @ReactModule annotation in io.invertase.firebase.database.ReactNativeFirebaseDatabaseModule
        at com.facebook.react.bridge.CatalystInstanceImpl.getNameFromAnnotation(CatalystInstanceImpl.java:603)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:566)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:165)
        at com.company.MainApplication$2.onReactContextInitialized(MainApplication.java:73)
        at com.facebook.react.ReactInstanceManager$6.run(ReactInstanceManager.java:1105)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by mikehardy** [comment]
Sorry, you have skipped our issue template.

**Comment by mikehardy** [comment]
(open to PRs though, including native changes just for brown-field / mixed-native/react-native use cases)

**Comment by Qwin** [comment]
@mikehardy it was really late yesterday, hence the skipped template.
