### ISSUE TITLE
[🐛] Config Plugin breaks on Expo SDK 44

### ISSUE THREAD

**Issue by nandorojo** [invertase/react-native-firebase#5936]
## Issue

If you upgrade to Expo SDK 44, and run `expo prebuild -p ios --clean`, you get this error:

<details>
<summary>
Click to view error
</summary>

```sh
(Use `node --trace-deprecation ...` to show where the warning was created)
✖ Config sync failed
[ios.dangerous]: withIosDangerousBaseMod: Failed to match "/(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])/g" in contents:
#import "AppDelegate.h"
@import Firebase;

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTConvert.h>

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif
  
  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [UIColor whiteColor];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
 }

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  // If you'd like to export some custom RCTBridgeModules, add them here!
  return @[];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
 #else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
 #endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

@end

Error: [ios.dangerous]: withIosDangerousBaseMod: Failed to match "/(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])/g" in contents:
#import "AppDelegate.h"
@import Firebase;

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTConvert.h>

#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
#if defined(FB_SONARKIT_ENABLED) && __has_include(<FlipperKit/FlipperClient.h>)
  InitializeFlipper(application);
#endif
  
  RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [self.reactDelegate createRootViewWithBridge:bridge moduleName:@"main" initialProperties:nil];
  rootView.backgroundColor = [UIColor whiteColor];
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [self.reactDelegate createRootViewController];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];

  [super application:application didFinishLaunchingWithOptions:launchOptions];

  return YES;
 }

- (NSArray<id<RCTBridgeModule>> *)extraModulesForBridge:(RCTBridge *)bridge
{
  // If you'd like to export some custom RCTBridgeModules, add them here!
  return @[];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
 #ifdef DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
 #else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
 #endif
}

// Linking API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  return [RCTLinkingManager application:application openURL:url options:options];
}

// Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler {
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

@end

    at addLines (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/utils/generateCode.ts:82:19)
    at mergeContents (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/utils/generateCode.ts:55:17)
    at modifyObjcAppDelegate (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js:24:45)
    at /Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/plugin/build/ios/appDelegate.js:41:28
    at action (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:23)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/Developer/madison-hacks/app/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at action (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:21)
    at interceptingMod (/Users/user/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
```
</details>

I'm omitting most other fields in this issue, since they don't apply to Expo projects. But let me know if you need any more info.

It was working before upgrading to SDK 44.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-firebase/app": "^13.1.0",
    "@react-native-firebase/auth": "^13.1.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [x] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `13.1.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `basic installation`
- **Are you using `TypeScript`?**
  - `4.4.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by nandorojo** [comment]
It looks like this regex isn't matching: https://github.com/invertase/react-native-firebase/blob/main/packages/app/plugin/src/ios/appDelegate.ts#L7

**Comment by mikehardy** [comment]
Oh darn - this happened with Expo 34 as well. It appears there is no stable interface here yet?
#5788 and then PR #5796
Historically ("once") @barthap has lent a hand here but it would be fantastic if there was more than one motivated / expo-savvy contributor around here. I don't use Expo myself so I can't be counted on for it unfortunately but I am willing to collaborate and get anything merged. Do you think you could give a fix a try?

Additionally I'm not sure if Expo allows patch-package to do it's thing but if you *do* propose anything, I made a CI action that generates a patch-package set for the monorepo packages, which helps get you over the hurdle of quick feedback, although I suppose tweaking a regex in node_modules isn't that hard of a case

**Comment by nandorojo** [comment]
A patch would be fine here for me. Unfortunately I have no idea where to start — I don’t know what an app delegate looks like or anything like that. I’m spoiled by expo and only know JS haha.

**Comment by barthap** [comment]
They promised not to change AppDelegate template since SDK 43 and use the plain React Native template, but I found out they actually did it again 🙄 I'm sorry. Afaik it's related to some "app delegate extensions", but I'm not into that deep into the topic yet.

I'll open a PR later, but now a quick patch for `@react-native-firebase/app`:
```patch
diff --git a/packages/app/plugin/src/ios/appDelegate.ts b/packages/app/plugin/src/ios/appDelegate.ts
index 7059a21c..e86741d4 100644
--- a/packages/app/plugin/src/ios/appDelegate.ts
+++ b/packages/app/plugin/src/ios/appDelegate.ts
@@ -5,7 +5,7 @@ import fs from 'fs';
 const methodInvocationBlock = `[FIRApp configure];`;
 // https://regex101.com/r/Imm3E8/1
 const methodInvocationLineMatcher =
-  /(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[\[RCTBridge alloc\])/g;
+  /(?:(self\.|_)(\w+)\s?=\s?\[\[UMModuleRegistryAdapter alloc\])|(?:RCTBridge\s?\*\s?(\w+)\s?=\s?\[(\[RCTBridge alloc\]|self\.reactDelegate))/g;
 
 export function modifyObjcAppDelegate(contents: string): string {
   // Add import
```

The Regex101 proof: https://regex101.com/r/mPgaq6/1

**Comment by mikehardy** [comment]
I'm going to issue it as a release in just a moment, so it'll be out on npmjs.com - I have a different bugfix I just merged that I want to get out there

**Comment by nandorojo** [comment]
Hey guys, following up here. I am having a slight issue with React Native Firebase with Expo SDK 44. 

When I call `auth().signInWithPhoneNumber(...)`, everything works perfectly.

However, when I build the app on Expo's hosted EAS service, calling this function results in the app crashing. 

To summarize: if I do `expo run:ios`, which builds the app locally, then `auth().signInWithPhoneNumber()` works. On the other hand, if I build the app via `eas build`, then calling `auth().signInWithPhoneNumber()` causes the app to crash.

@barthap does anything come to mind for why this might be? Do you expect it to be on the Expo side, or perhaps on the plugin side? I tried running `eas build --local`, and indeed had the issue on my locally-built EAS binary.

Thank you so much!

**Comment by barthap** [comment]
I doubt that it's related to the config plugin in any way. It looks more like an EAS issue. Do you have any logs from that crash?

**Comment by mikehardy** [comment]
I was thinking the same thing. Crash === crash trace needed for diagnosis

**Comment by nandorojo** [comment]
> I doubt that it's related to the config plugin in any way. It looks more like an EAS issue. Do you have any logs from that crash?

Yeah my instinct says the same. Sorry for the silly question, but what's the easiest way to get shareable crash logs? Is it logcat? (I'm not used to native debugging; I usually use the Console app.)

Thank you both!

**Comment by mikehardy** [comment]
Plug device in to computer, Console.app should show the device and from there you will have the ability to see device logs I believe

Also of note but unrelated, react-native 0.68 is releasing shortly and the react-native template has moved to `.mm` (Objective-C++) so there will be ongoing change here. Looks like expo support will be a treadmill of a feature

**Comment by nandorojo** [comment]
I found the cause of the crash, which led me to https://github.com/invertase/react-native-firebase/issues/2346:

<img width="1482" alt="Screen Shot 2022-03-30 at 10 40 10 AM" src="https://user-images.githubusercontent.com/13172299/160861723-62c2d5d9-a520-4667-af47-b7e7cc36919a.png">

 I think I incorrectly followed the [Firebase captcha instructions](https://firebase.google.com/docs/auth/ios/phone-auth#set-up-recaptcha-verification). I'm not sure why this only crashed on the EAS build though. Captcha worked fine on my simulator from local builds.

The Firebase captcha instructions require editing fields inside of XCode, using a field from the `GoogleService-Info.plist`. I wonder if this should be done via config plugin for the `auth` package, perhaps under a `captcha` key?

<img width="921" alt="image" src="https://user-images.githubusercontent.com/13172299/160864206-afe6153a-e93a-4536-941d-198ecc3b6685.png">

Thank you so much for the lead on checking out the crash logs, and for responding quick in general. The moral support helps.

**Comment by barthap** [comment]
Related: https://github.com/invertase/react-native-firebase/discussions/5787

**Comment by mikehardy** [comment]
@nandorojo if this (the captcha info.plist expo command to define the url scheme) could use a pointer in the docs a PR would be awesome :pray: :smile:

**Comment by mikehardy** [comment]
A lot of people use app without auth, auth config / functionality should not be included in app

**Comment by barthap** [comment]
Nitpick regarding your plugin code - you might want to read the location of your Google services file from `config.ios.googleServicesFile` to make this solution more generic.

**Comment by nandorojo** [comment]
> Nitpick regarding your plugin code - you might want to read the location of your Google services file from config.ios.googleServicesFile to make this solution more generic.

Definitely – this is just in my own app's code to see if it works for now

**Comment by mikehardy** [comment]
Sure - I wish Expo support were frictionless (that is: required no maintenance at all or config plugins or anything) but until then, this can help people. Thanks!

**Comment by nandorojo** [comment]
Yeah I hear you. I personally like that it lets me encapsulate all the native config steps using JS APIs. Opened a PR at https://github.com/invertase/react-native-firebase/pull/6167
