### ISSUE TITLE
[🐛][🔥][Auth][Android] Getting "Cannot read property 'token' of undefined" in release mode

### ISSUE THREAD

**Issue by apapalillo** [invertase/react-native-firebase#5998]
## Issue

Hi, I'm having a weird error with Firebase Auth if I try to login in release mode with Android:

> TypeError: Cannot read property 'token' of undefined
>     at _callee$ (address at index.android.bundle:1:1508944)
>     at call (native)
>     at tryCatch (address at index.android.bundle:1:72591)
>     at invoke (address at index.android.bundle:1:73597)
>     at anonymous (address at index.android.bundle:1:72739)
>     at call (native)
>     at tryCatch (address at index.android.bundle:1:72591)
>     at invoke (address at index.android.bundle:1:72824)
>     at anonymous (address at index.android.bundle:1:73265)
>     at tryCallTwo (/tmp/hermes/staging/hermes/cmake/intlRelease/armeabi-v7a/lib/InternalBytecode/InternalBytecode.js:61:9)
>     at doResolve (/tmp/hermes/staging/hermes/cmake/intlRelease/armeabi-v7a/lib/InternalBytecode/InternalBytecode.js:216:25)
>     at Promise (/tmp/hermes/staging/hermes/cmake/intlRelease/armeabi-v7a/lib/InternalBytecode/InternalBytecode.js:82:14)
>     at callInvokeWithMethodAndArg (address at index.android.bundle:1:73227)
>     at enqueue (address at index.android.bundle:1:73174)
>     at anonymous (address at index.android.bundle:1:72739)
>     at anonymous (address at index.android.bundle:1:74985)
>     at _callee (address at index.android.bundle:1:1508782)
>     at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlRelease/armeabi-v7a/lib/InternalBytecode/InternalBytecode.js:53:16)
>     at anonymous (/tmp/hermes/staging/hermes/cmake/intlRelease/armeabi-v7a/lib/InternalBytecode/InternalBytecode.js:139:27)
>     at apply (native)
>     at anonymous (address at index.android.bundle:1:182809)
>     at _callTimer (address at index.android.bundle:1:181705)
>     at _callReactNativeMicrotasksPass (address at index.android.bundle:1:181910)
>     at callReactNativeMicrotasks (address at index.android.bundle:1:183908)
>     at __callReactNativeMicrotasks (address at index.android.bundle:1:93484)
>     at anonymous (address at index.android.bundle:1:92567)
>     at __guard (address at index.android.bundle:1:93325)
>     at flushedQueue (address at index.android.bundle:1:92478)
>     at callFunctionReturnFlushedQueue (address at index.android.bundle:1:92334)

I think it happens inside this Promise: `auth().signInWithCredential(credential)`
It happens with Google and Twitter credentials

Most important thing: this doesn't happen in debug mode, which is also **signed with release keys**. In debug mode everything with Auth goes fine.
The only difference in build.gradle is that release has minifyEnabled set to true. But if I set it to false it doesn't fix the issue.

The command used to run in release mode: `react-native run-android --variant=release`

Some time ago I've upgraded React Native from 0.63.4 to 0.66.4, I don't know if this could be the cause

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
```json
    "react": "17.0.2",
    "react-native": "0.66.4",
    "@react-native-firebase/app": "^14.2.2",
    "@react-native-firebase/auth": "^14.2.2",
    "@react-native-google-signin/google-signin": "^7.0.4",
    "@react-native-twitter-signin/twitter-signin": "^1.2.0",
    "react-native-fbsdk-next": "^4.3.0",
```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {
    "android_task_executor_maximum_pool_size": 10,
    "android_task_executor_keep_alive_seconds": 3
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [x] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [x] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.22 GB / 15.81 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    Visual Studio: Not Found
  Languages:
    Java: 17.0.1
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `14.2.2`
- **`Firebase` module(s) you're using that has the issue:**
  - `@react-native-firebase/auth`
- **Are you using `TypeScript`?**
  - `Y` & `4.4.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!
This isn't quite information to go on: https://stackoverflow.com/help/how-to-ask

Is it on emulators as well? Real device only? Some device types but not others? Debug vs release is usually either a timing issue or a release config issue. This seems like it may be a timing issue

> I think it happens inside this Promise: auth().signInWithCredential(credential)

what happens when you reach in to node_modules/@react-native-firebase/auth in the file with that method and log the API call the module makes to the native layer with all the parameters, and then log all of the values that come out?

I feel like this was discussed recently but I don't believe there was resolution - I can note that the token may apparently be null at least via the iOS Objective-C documentation https://github.com/invertase/react-native-firebase/discussions/5990

What does the upstream firebase android documentation for the underlying API say with regard to nullability?

**Comment by apapalillo** [comment]
> Hi there! This isn't quite information to go on: https://stackoverflow.com/help/how-to-ask

Yeah, sorry, it's my first github issue, it really is my last resort :)
Let me explain better

> Is it on emulators as well? Real device only? Some device types but not others? Debug vs release is usually either a timing issue or a release config issue. This seems like it may be a timing issue

I've tested it both on emulators and real devices (Samsung Galaxy A5 and Oneplus Nord), they all have the same issue. Yeah it seems like a timing issue

Also, I don't know why, but it seems there are two different AndroidManifest files, one on _main_ folder, and the other on _debug_ folder, but I don't know if the latter is somehow used in the debug build.

**android/app/src/main/AndroidManifest.xml**

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="my.package.name">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <service android:name="com.asterinet.react.bgactions.RNBackgroundActionsTask" />
    </application>

</manifest>
```

**android/app/src/debug/AndroidManifest.xml**

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools">

    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
            android:usesCleartextTraffic="true"
            tools:targetApi="28"
            tools:ignore="GoogleAppIndexingWarning">
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
</manifest>
```


> what happens when you reach in to node_modules/@react-native-firebase/auth in the file with that method and log the API call the module makes to the native layer with all the parameters, and then log all of the values that come out?

I've tried by putting some console.logs:

```
  signInWithCredential(credential) {
    console.log(credential.providerId, credential.token, credential.secret);
    return this.native
      .signInWithCredential(credential.providerId, credential.token, credential.secret)
      .then(userCredential => {
        console.log(userCredential);
        this._setUserCredential(userCredential);
      });
  }
```

The first returns "google.com", a 1125-long token, and an undefined.
The seconds returns a JSON with my Google user's metadata, which seems to be normal.
It seems to be working as intended and it seems to reach the "then" method of the promise, then why does my code catch an error?

This is the google sign-in method:

```
import { GoogleSignin } from '@react-native-google-signin/google-signin';
import auth from '@react-native-firebase/auth';

// Init
GoogleSignin.configure({
  webClientId: '#########################.apps.googleusercontent.com',
});

export async function googleSignin() {
  // Get the users ID token
  const { idToken } = await GoogleSignin.signIn();

  // Create a Google credential with the token
  const googleCredential = auth.GoogleAuthProvider.credential(idToken);

  // Sign-in the user with the credential
  return auth().signInWithCredential(googleCredential);
}
```

And this is how it's called:

```
googleSignin().catch((err: Error) => {
  // err logging
})
```

Also, I'm debugging the onAuthStateChanged subscriber

```
  // Handle user state changes
  function onAuthStateChanged(user: FirebaseAuthTypes.User | null) {
    dispatch({
      type: DispatchType.SET_USER,
      user: user,
    });
  }

  React.useEffect(() => {
    const subscriber = auth().onAuthStateChanged(onAuthStateChanged);
    return subscriber; // unsubscribe on unmount
  }, []);
```

And it seems to be called twice after the login. The first returns the actual user info, the second (after a half second) returns a null value. I have no idea why, but it doesn't happen in a debug build.

It's somehow like it calls the _signInWithCredential_ method is called twice in release mode, with the second try failing, but in the logging I see it's only called once.

**Comment by apapalillo** [comment]
> Some time ago I've upgraded React Native from 0.63.4 to 0.66.4, I don't know if this could be the cause

I can definitely exclude this scenario, I've tried to checkout a commit prior to this upgrade, did a clean build and still have the issue

**Comment by androidIsForVivek** [comment]
facing the same issue

**Comment by apapalillo** [comment]
> Hello 👋, to help manage issues we automatically close stale issues. This issue has been automatically marked as stale because it has not had activity for quite some time. Has this issue been fixed, or does it still require the community's attention?
> 
> > This issue will be closed in 15 days if no further activity occurs.
> > Thank you for your contributions.

Nope. This issue still exists and it's blocking. I really need a fix for this.

**Comment by mikehardy** [comment]
@apapalillo Sorry there is no progress here yet - this is not something that I reproduce personally so I can't really assist much

**Comment by apapalillo** [comment]
Thank God I found the issue.

It was something wrong with axios and non-SSL (http without s) requests (http without s) not starting in release mode, so these requests were uncatchable in axios promises. It was nearly impossible to debug. 😒

The good news is that it has nothing to do with rn-firebase. Sorry to bother you and thanks for your support, we can definitely close this issue.
