### ISSUE TITLE
Can not compile: Multiple dex files define Lcom/google/firebase/iid/zzb

### ISSUE THREAD

**Issue by arturictus** [invertase/react-native-firebase#62]
when I run react-native run-android I get this error:
```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
```

This are my android dependencies:

I think the problem is that many libraries already use `com.google.android.gms:play-services-iid:10.2.1` and firebase is still stack at `com.google.firebase:firebase-iid:10.2.0`

```
_debugCompile - ## Internal use, do not manually configure ##
+--- project :react-native-firebase
|    +--- com.android.support:multidex:1.0.1
|    +--- com.facebook.react:react-native:+ -> 0.41.2
|    |    +--- javax.inject:javax.inject:1
|    |    +--- com.android.support:appcompat-v7:23.0.1
|    |    |    \--- com.android.support:support-v4:23.0.1 -> 24.0.0
|    |    |         \--- com.android.support:support-annotations:24.0.0
|    |    +--- com.android.support:recyclerview-v7:23.4.0
|    |    |    +--- com.android.support:support-annotations:23.4.0 -> 24.0.0
|    |    |    \--- com.android.support:support-v4:23.4.0 -> 24.0.0 (*)
|    |    +--- com.facebook.fbui.textlayoutbuilder:textlayoutbuilder:1.0.0
|    |    |    \--- com.facebook.fbui.textlayoutbuilder:staticlayout-proxy:1.0
|    |    +--- com.facebook.fresco:fresco:0.11.0
|    |    |    +--- com.facebook.fresco:drawee:0.11.0
|    |    |    |    +--- com.android.support:support-v4:23.2.1 -> 24.0.0 (*)
|    |    |    |    \--- com.facebook.fresco:fbcore:0.11.0
|    |    |    +--- com.facebook.fresco:fbcore:0.11.0
|    |    |    \--- com.facebook.fresco:imagepipeline:0.11.0
|    |    |         +--- com.android.support:support-v4:23.2.1 -> 24.0.0 (*)
|    |    |         +--- com.facebook.fresco:fbcore:0.11.0
|    |    |         +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    |         +--- com.nineoldandroids:library:2.4.0
|    |    |         \--- com.facebook.fresco:imagepipeline-base:0.11.0
|    |    |              +--- com.android.support:support-v4:23.2.1 -> 24.0.0 (*)
|    |    |              +--- com.facebook.fresco:fbcore:0.11.0
|    |    |              +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    |              \--- com.nineoldandroids:library:2.4.0
|    |    +--- com.facebook.fresco:imagepipeline-okhttp3:0.11.0
|    |    |    +--- com.facebook.fresco:fbcore:0.11.0
|    |    |    +--- com.squareup.okhttp3:okhttp:3.0.1 -> 3.4.1
|    |    |    |    \--- com.squareup.okio:okio:1.9.0
|    |    |    \--- com.facebook.fresco:imagepipeline:0.11.0 (*)
|    |    +--- com.facebook.soloader:soloader:0.1.0
|    |    +--- com.google.code.findbugs:jsr305:3.0.0
|    |    +--- com.squareup.okhttp3:okhttp:3.4.1 (*)
|    |    +--- com.squareup.okhttp3:okhttp-urlconnection:3.4.1
|    |    |    \--- com.squareup.okhttp3:okhttp:3.4.1 (*)
|    |    +--- com.squareup.okhttp3:okhttp-ws:3.4.1
|    |    |    \--- com.squareup.okhttp3:okhttp:3.4.1 (*)
|    |    +--- com.squareup.okio:okio:1.9.0
|    |    \--- org.webkit:android-jsc:r174650
|    +--- me.leolin:ShortcutBadger:1.1.10
|    +--- com.google.android.gms:play-services-base:10.2.0 -> 10.2.1
|    |    +--- com.google.android.gms:play-services-basement:10.2.1
|    |    |    \--- com.android.support:support-v4:24.0.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:10.2.1
|    |         \--- com.google.android.gms:play-services-basement:10.2.1 (*)
|    +--- com.google.firebase:firebase-core:10.2.0
|    |    \--- com.google.firebase:firebase-analytics:10.2.0
|    |         +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |         +--- com.google.firebase:firebase-common:10.2.0
|    |         |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |         |    \--- com.google.android.gms:play-services-tasks:10.2.0 -> 10.2.1 (*)
|    |         \--- com.google.firebase:firebase-analytics-impl:10.2.0
|    |              +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |              +--- com.google.firebase:firebase-iid:10.2.0
|    |              |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |              |    \--- com.google.firebase:firebase-common:10.2.0 (*)
|    |              +--- com.google.firebase:firebase-common:10.2.0 (*)
|    |              \--- com.google.android.gms:play-services-tasks:10.2.0 -> 10.2.1 (*)
|    +--- com.google.firebase:firebase-config:10.2.0
|    |    +--- com.google.android.gms:play-services-base:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.firebase:firebase-iid:10.2.0 (*)
|    |    +--- com.google.firebase:firebase-common:10.2.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:10.2.0 -> 10.2.1 (*)
|    +--- com.google.firebase:firebase-auth:10.2.0
|    |    +--- com.google.android.gms:play-services-base:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.firebase:firebase-common:10.2.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:10.2.0 -> 10.2.1 (*)
|    +--- com.google.firebase:firebase-analytics:10.2.0 (*)
|    +--- com.google.firebase:firebase-database:10.2.0
|    |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.firebase:firebase-database-connection:10.2.0
|    |    |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |    |    \--- com.google.firebase:firebase-common:10.2.0 (*)
|    |    +--- com.google.firebase:firebase-common:10.2.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:10.2.0 -> 10.2.1 (*)
|    +--- com.google.firebase:firebase-storage:10.2.0
|    |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.firebase:firebase-storage-common:10.2.0
|    |    |    \--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.firebase:firebase-common:10.2.0 (*)
|    |    \--- com.google.android.gms:play-services-tasks:10.2.0 -> 10.2.1 (*)
|    +--- com.google.firebase:firebase-messaging:10.2.0
|    |    +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|    |    +--- com.google.firebase:firebase-iid:10.2.0 (*)
|    |    \--- com.google.firebase:firebase-common:10.2.0 (*)
|    \--- com.google.firebase:firebase-crash:10.2.0
|         +--- com.google.android.gms:play-services-basement:10.2.0 -> 10.2.1 (*)
|         +--- com.google.firebase:firebase-iid:10.2.0 (*)
|         +--- com.google.firebase:firebase-common:10.2.0 (*)
|         \--- com.google.firebase:firebase-analytics:10.2.0 (*)
+--- project :react-native-photo-view
|    +--- com.facebook.react:react-native:+ -> 0.41.2 (*)
|    +--- com.facebook.fresco:fresco:0.11.0 (*)
|    \--- me.relex:photodraweeview:1.0.0
+--- project :react-native-device-info
|    \--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-calendar-events
|    \--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-fs
|    \--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-video
|    \--- com.yqritc:android-scalablevideoview:1.0.1
+--- project :react-native-geocoder
|    \--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-image-picker
|    \--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-code-push
|    \--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-custom-tabs
|    +--- com.facebook.react:react-native:+ -> 0.41.2 (*)
|    \--- com.github.droibit.customtabslauncher:launcher:1.0.2
|         \--- com.android.support:customtabs:23.3.0
|              +--- com.android.support:support-v4:23.3.0 -> 24.0.0 (*)
|              \--- com.android.support:support-annotations:23.3.0 -> 24.0.0
+--- project :react-native-vector-icons
|    \--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-appsee
|    +--- com.appsee:appsee-android:2.3
|    \--- com.facebook.react:react-native:0+ -> 0.41.2 (*)
+--- com.android.support:appcompat-v7:23.0.1 (*)
+--- com.facebook.react:react-native:+ -> 0.41.2 (*)
+--- project :react-native-onesignal
|    +--- com.facebook.react:react-native:+ -> 0.41.2 (*)
|    +--- com.onesignal:OneSignal:3.+ -> 3.4.4
|    +--- com.google.android.gms:play-services-gcm:+ -> 10.2.1
|    |    +--- com.google.android.gms:play-services-base:10.2.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:10.2.1 (*)
|    |    \--- com.google.android.gms:play-services-iid:10.2.1
|    |         +--- com.google.android.gms:play-services-base:10.2.1 (*)
|    |         \--- com.google.android.gms:play-services-basement:10.2.1 (*)
|    +--- com.google.android.gms:play-services-analytics:+ -> 10.2.1
|    |    +--- com.google.android.gms:play-services-analytics-impl:10.2.1
|    |    |    +--- com.google.android.gms:play-services-base:10.2.1 (*)
|    |    |    \--- com.google.android.gms:play-services-basement:10.2.1 (*)
|    |    +--- com.google.android.gms:play-services-base:10.2.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:10.2.1 (*)
|    |    \--- com.google.android.gms:play-services-tagmanager-v4-impl:10.2.1
|    |         +--- com.google.android.gms:play-services-analytics-impl:10.2.1 (*)
|    |         +--- com.google.android.gms:play-services-base:10.2.1 (*)
|    |         \--- com.google.android.gms:play-services-basement:10.2.1 (*)
|    \--- com.google.android.gms:play-services-location:+ -> 10.2.1
|         +--- com.google.android.gms:play-services-base:10.2.1 (*)
|         +--- com.google.android.gms:play-services-basement:10.2.1 (*)
|         \--- com.google.android.gms:play-services-tasks:10.2.1 (*)
+--- project :react-native-i18n
|    \--- com.facebook.react:react-native:0.12.+ -> 0.41.2 (*)
+--- com.facebook.fresco:animated-gif:0.11.0
|    +--- com.android.support:support-v4:23.2.1 -> 24.0.0 (*)
|    +--- com.parse.bolts:bolts-tasks:1.4.0
|    +--- com.nineoldandroids:library:2.4.0
|    +--- com.facebook.fresco:fbcore:0.11.0
|    \--- com.facebook.fresco:animated-base:0.11.0
|         +--- com.android.support:support-v4:23.2.1 -> 24.0.0 (*)
|         +--- com.facebook.fresco:fbcore:0.11.0
|         +--- com.parse.bolts:bolts-tasks:1.4.0
|         +--- com.nineoldandroids:library:2.4.0
|         +--- com.facebook.fresco:imagepipeline-base:0.11.0 (*)
|         \--- com.facebook.fresco:imagepipeline:0.11.0 (*)
\--- com.google.firebase:firebase-core:9.0.0 -> 10.2.0 (*)
```

**Comment by Ehesp** [comment]
Hi - this issue has been raised a number of times. Please follow the guide in the FAQs on how to resolve this:

https://github.com/invertase/react-native-firebase/blob/master/docs/faqs.md#android-duplicate-dex-files-error-build-time-error

**Comment by arturictus** [comment]
Thank you!! @Ehesp

**Comment by roots-ai** [comment]
The above link is broken

**Comment by Ehesp** [comment]
Fixed it, thanks for flagging

**Comment by isacoskun** [comment]
Hello, I have such a problem. How could I solve it?

https://stackoverflow.com/questions/48630943/when-i-want-to-create-apk-in-the-android-studio-i-get-this-error

**Comment by Salakar** [comment]
@isacoskun there's an additional log that follows that error on how to deal with it:

![image](https://user-images.githubusercontent.com/5347038/29476094-572dcc5a-845a-11e7-95da-276b9c6b1170.png)

**Comment by tcscott** [comment]
@Salakar the page that sends you to appears broken https://rnfirebase.io/docs/v3.1.*/faqs

**Comment by clevertree** [comment]
link still broken

**Comment by Ehesp** [comment]
https://rnfirebase.io/docs/v4.0.x/troubleshooting/android#Duplicate-Dex-Files-error-(build-time-error)
