### ISSUE TITLE
[ANDROID] App crashed immediately on start

### ISSUE THREAD

**Issue by kevindavee** [invertase/react-native-firebase#635]
### Environment
1. Application Target Platform: Android
2. Development Operating System: macOS High Sierra
3. Build Tools:  Android Studio, SDK v.23
4. React Native version: 0.47.2
5. RNFirebase Version: 5.5.1
6. Firebase Module: Initialization

Hello. My application immediately crashed when starting`react-native run-android`
Here I provide my debug log. I hope you guys can help me 

```
11-21 10:19:39.270 11042-11042/? I/art: Not late-enabling -Xcheck:jni (already on)
11-21 10:19:39.271 11042-11042/? W/art: Unexpected CPU variant for X86 using defaults: x86
11-21 10:19:39.292 11042-11049/? I/art: Debugger is no longer active
11-21 10:19:39.292 11042-11049/? I/art: Starting a blocking GC Instrumentation
11-21 10:19:39.324 11042-11042/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
11-21 10:19:39.328 11042-11042/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
11-21 10:19:39.337 11042-11042/? I/FirebaseInitProvider: FirebaseApp initialization successful
11-21 10:19:39.344 11042-11042/? V/fb-UnpackingSoSource: locked dso store /data/user/0/com.yumboxapp/lib-main
11-21 10:19:39.345 11042-11042/? V/fb-UnpackingSoSource: deps mismatch on deps store: regenerating
11-21 10:19:39.345 11042-11042/? V/fb-UnpackingSoSource: so store dirty: regenerating
11-21 10:19:39.355 11042-11058/? I/FA: App measurement is starting up, version: 11717
11-21 10:19:39.355 11042-11058/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
11-21 10:19:39.356 11042-11058/? I/FA: To enable faster debug mode event logging run:
                                         adb shell setprop debug.firebase.analytics.app com.yumboxapp
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libfb.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libfolly_json.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libglog.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libglog_init.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libgnustl_shared.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libicu_common.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libimagepipeline.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libjsc.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libreactnativejni.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? D/ApkSoSource: not allowing consideration of lib/x86/libyoga.so: deferring to libdir
11-21 10:19:39.380 11042-11042/? V/fb-UnpackingSoSource: regenerating DSO store com.facebook.soloader.ApkSoSource
11-21 10:19:39.381 11042-11042/? V/fb-UnpackingSoSource: starting syncer worker
11-21 10:19:39.387 11042-11042/? V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.yumboxapp/lib-main (from syncer thread)
11-21 10:19:39.387 11042-11042/? V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.yumboxapp/lib-main (syncer thread started)
11-21 10:19:39.394 11042-11042/? D/ReactNative: ReactInstanceManager.ctor()
11-21 10:19:39.399 11042-11042/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-21 10:19:39.414 11042-11042/? D/ReactNative: ReactInstanceManager.createReactContextInBackground()
11-21 10:19:39.414 11042-11042/? D/ReactNative: ReactInstanceManager.recreateReactContextInBackgroundInner()
11-21 10:19:39.433 11042-11042/? W/unknown:ReactNative: Packager connection already open, nooping.
11-21 10:19:39.433 11042-11042/? W/unknown:ReactNative: Inspector connection already open, nooping.
11-21 10:19:39.434 11042-11058/? I/FA: Tag Manager is not found and thus will not be used
11-21 10:19:39.572 11042-11068/? I/OpenGLRenderer: Initialized EGL, version 1.4
11-21 10:19:39.572 11042-11068/? D/OpenGLRenderer: Swap behavior 1
11-21 10:19:39.572 11042-11068/? W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
11-21 10:19:39.572 11042-11068/? D/OpenGLRenderer: Swap behavior 0
11-21 10:19:39.573 11042-11068/? D/EGL_emulation: eglCreateContext: 0x9cd1eda0: maj 2 min 0 rcv 2
11-21 10:19:39.574 11042-11068/? D/EGL_emulation: eglMakeCurrent: 0x9cd1eda0: ver 2 0 (tinfo 0x8c812160)
11-21 10:19:39.582 11042-11068/? D/EGL_emulation: eglMakeCurrent: 0x9cd1eda0: ver 2 0 (tinfo 0x8c812160)
11-21 10:19:39.635 11042-11068/? D/EGL_emulation: eglMakeCurrent: 0x9cd1eda0: ver 2 0 (tinfo 0x8c812160)
11-21 10:19:39.885 11042-11068/? D/EGL_emulation: eglMakeCurrent: 0x9cd1eda0: ver 2 0 (tinfo 0x8c812160)
11-21 10:19:39.890 11042-11042/? D/ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
11-21 10:19:39.897 11042-11042/? I/art: Thread[1,tid=11042,Native,Thread*=0xa680b400,peer=0x73d96610,"main"] recursive attempt to load library "/data/app/com.yumboxapp-1/lib/x86/libfb.so"
11-21 10:19:39.901 11042-11042/? D/ReactNative: ReactInstanceManager.recreateReactContextInBackground()
11-21 10:19:39.901 11042-11042/? D/ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
11-21 10:19:39.903 11042-11074/? D/ReactNative: ReactInstanceManager.createReactContext()
11-21 10:19:39.913 11042-11074/? I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
11-21 10:19:39.913 11042-11074/? I/art:     at void com.airbnb.android.react.maps.AirMapManager.<init>(com.facebook.react.bridge.ReactApplicationContext) (AirMapManager.java:50)
11-21 10:19:39.913 11042-11074/? I/art:     at java.util.List com.airbnb.android.react.maps.MapsPackage.createViewManagers(com.facebook.react.bridge.ReactApplicationContext) (MapsPackage.java:39)
11-21 10:19:39.913 11042-11074/? I/art:     at java.util.List com.facebook.react.ReactInstanceManager.createAllViewManagers(com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:715)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.createUIManager(com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:198)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.access$200(com.facebook.react.CoreModulesPackage, com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:73)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.NativeModule com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:150)
11-21 10:19:39.913 11042-11074/? I/art:     at java.lang.Object com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:147)
11-21 10:19:39.913 11042-11074/? I/art:     at java.util.List com.facebook.react.LazyReactPackage.createNativeModules(com.facebook.react.bridge.ReactApplicationContext) (LazyReactPackage.java:81)
11-21 10:19:39.913 11042-11074/? I/art:     at void com.facebook.react.NativeModuleRegistryBuilder.processPackage(com.facebook.react.ReactPackage) (NativeModuleRegistryBuilder.java:106)
11-21 10:19:39.913 11042-11074/? I/art:     at void com.facebook.react.ReactInstanceManager.processPackage(com.facebook.react.ReactPackage, com.facebook.react.NativeModuleRegistryBuilder) (ReactInstanceManager.java:1071)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.NativeModuleRegistry com.facebook.react.ReactInstanceManager.processPackages(com.facebook.react.bridge.ReactApplicationContext, java.util.List, boolean) (ReactInstanceManager.java:1042)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.createReactContext(com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:980)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.access$600(com.facebook.react.ReactInstanceManager, com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:109)
11-21 10:19:39.913 11042-11074/? I/art:     at void com.facebook.react.ReactInstanceManager$4.run() (ReactInstanceManager.java:802)
11-21 10:19:39.913 11042-11074/? I/art:     at void java.lang.Thread.run() (Thread.java:761)
11-21 10:19:39.913 11042-11074/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.yumboxapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yumboxapp-1/lib/x86, /system/fake-libs, /data/app/com.yumboxapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
11-21 10:19:39.913 11042-11074/? I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
11-21 10:19:39.913 11042-11074/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
11-21 10:19:39.913 11042-11074/? I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
11-21 10:19:39.913 11042-11074/? I/art:     at void com.airbnb.android.react.maps.AirMapManager.<init>(com.facebook.react.bridge.ReactApplicationContext) (AirMapManager.java:50)
11-21 10:19:39.913 11042-11074/? I/art:     at java.util.List com.airbnb.android.react.maps.MapsPackage.createViewManagers(com.facebook.react.bridge.ReactApplicationContext) (MapsPackage.java:39)
11-21 10:19:39.913 11042-11074/? I/art:     at java.util.List com.facebook.react.ReactInstanceManager.createAllViewManagers(com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:715)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.createUIManager(com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:198)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.access$200(com.facebook.react.CoreModulesPackage, com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:73)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.NativeModule com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:150)
11-21 10:19:39.913 11042-11074/? I/art:     at java.lang.Object com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:147)
11-21 10:19:39.913 11042-11074/? I/art:     at java.util.List com.facebook.react.LazyReactPackage.createNativeModules(com.facebook.react.bridge.ReactApplicationContext) (LazyReactPackage.java:81)
11-21 10:19:39.913 11042-11074/? I/art:     at void com.facebook.react.NativeModuleRegistryBuilder.processPackage(com.facebook.react.ReactPackage) (NativeModuleRegistryBuilder.java:106)
11-21 10:19:39.913 11042-11074/? I/art:     at void com.facebook.react.ReactInstanceManager.processPackage(com.facebook.react.ReactPackage, com.facebook.react.NativeModuleRegistryBuilder) (ReactInstanceManager.java:1071)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.NativeModuleRegistry com.facebook.react.ReactInstanceManager.processPackages(com.facebook.react.bridge.ReactApplicationContext, java.util.List, boolean) (ReactInstanceManager.java:1042)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.createReactContext(com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:980)
11-21 10:19:39.913 11042-11074/? I/art:     at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.access$600(com.facebook.react.ReactInstanceManager, com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:109)
11-21 10:19:39.913 11042-11074/? I/art:     at void com.facebook.react.ReactInstanceManager$4.run() (ReactInstanceManager.java:802)
11-21 10:19:39.913 11042-11074/? I/art:     at void java.lang.Thread.run() (Thread.java:761)
11-21 10:19:39.913 11042-11074/? E/AndroidRuntime: FATAL EXCEPTION: Thread-3
                                                   Process: com.yumboxapp, PID: 11042
                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
                                                       at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:50)
                                                       at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
                                                       at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:715)
                                                       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:198)
                                                       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:73)
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:150)
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:147)
                                                       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071)
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042)
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980)
                                                       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                                                       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
                                                       at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                       at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:50) 
                                                       at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
                                                       at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:715) 
                                                       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:198) 
                                                       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:73) 
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:150) 
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:147) 
                                                       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071) 
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042) 
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980) 
                                                       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109) 
                                                       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802) 
                                                       at java.lang.Thread.run(Thread.java:761) 
                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
                                                       at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:50) 
                                                       at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
                                                       at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:715) 
                                                       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:198) 
                                                       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:73) 
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:150) 
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:147) 
                                                       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071) 
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042) 
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980) 
                                                       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109) 
                                                       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802) 
                                                       at java.lang.Thread.run(Thread.java:761) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.yumboxapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yumboxapp-1/lib/x86, /system/fake-libs, /data/app/com.yumboxapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:50) 
                                                       at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39) 
                                                       at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:715) 
                                                       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:198) 
                                                       at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:73) 
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:150) 
                                                       at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:147) 
                                                       at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071) 
                                                       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042) 
                                                       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980) 
                                                       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109) 
                                                       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802) 
                                                       at java.lang.Thread.run(Thread.java:761) 

```

**Comment by chrisbianca** [comment]
@kevindavee This is not a RNFirebase issue for two reasons:

1) We do not have a version 5.5.1
2) The error log clearly shows this is an error from the airbnb maps package:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
                                                       at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:50)
```

**Comment by kevindavee** [comment]
Im sorry. Wrong version checked. My current react-native-firebase version is **3.1.0**

The error occurred after I install react native firebase, and configure it for android. Before I install react-native-firebase, my app works perfectly

**Comment by chrisbianca** [comment]
You're likely to be trying to import different versions of the google play services libraries. This tends to cause errors like the one you're seeing... The fix is similar to the steps explained here: https://rnfirebase.io/docs/v3.1.*/faqs#[Android]-Duplicate-Dex-Files-error-(build-time-error)
