### ISSUE TITLE
[🐛]  E/Auth: signInWithCredential:onComplete:failure - Firebase auth package

### ISSUE THREAD

**Issue by evgenyshenets** [invertase/react-native-firebase#6359]
I am using the firebase auth package for google sign-in and followed the docs from here: https://rnfirebase.io/auth/social-auth

package.json: 
    "@apollo/client": "^3.5.10",
    "@apollo/react-hooks": "^4.0.0",
    "@react-native-async-storage/async-storage": "^1.17.1",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/analytics": "^14.10.1",
    "@react-native-firebase/app": "^14.11.0",
    "@react-native-firebase/auth": "^14.11.0",
    "@react-native-firebase/database": "^14.11.0",
    "@react-native-firebase/messaging": "^14.10.1",
    "@react-native-google-signin/google-signin": "^7.2.2",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/elements": "^1.3.3",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.2",
    "@react-navigation/stack": "^6.2.1",
    "apollo-link-http": "^1.5.17",
    "babel-plugin-module-resolver": "^4.1.0",
    "jwt-decode": "^3.1.2",
    "react": "17.0.2",
    "react-i18next": "^11.16.2",
    "react-native": "0.67.4",
    "react-native-calendars": "^1.1283.0",
    "react-native-config": "^1.4.5",
    "react-native-reanimated": "^2.6.0",

```Using the simple sign-in function: 
  const signIn = async () => {
    const { idToken } = await GoogleSignin.signIn();

    const googleCredential = auth.GoogleAuthProvider.credential(idToken);

    return auth().signInWithCredential(googleCredential);   <----- firebase auth.
  };
```

In debug mode all works as expected, but when I am creating release build I am getting an error. Log from android studio is here:
`2022-07-01 19:07:14.008 20676-22505/? E/Auth: signInWithCredential:onComplete:failure
    com.google.firebase.FirebaseException: An internal error has occurred. [ CONFIGURATION_NOT_FOUND ]
        at com.google.android.gms.internal.firebase-auth-api.zztj.zza(com.google.firebase:firebase-auth@@21.0.5:4)
        at com.google.android.gms.internal.firebase-auth-api.zzuh.zza(com.google.firebase:firebase-auth@@21.0.5:9)
        at com.google.android.gms.internal.firebase-auth-api.zzui.zzl(com.google.firebase:firebase-auth@@21.0.5:1)
        at com.google.android.gms.internal.firebase-auth-api.zzuf.zzh(com.google.firebase:firebase-auth@@21.0.5:25)
        at com.google.android.gms.internal.firebase-auth-api.zzth.zzh(com.google.firebase:firebase-auth@@21.0.5:1)
        at com.google.android.gms.internal.firebase-auth-api.zzrf.zza(com.google.firebase:firebase-auth@@21.0.5:2)
        at com.google.android.gms.internal.firebase-auth-api.zzuq.zza(com.google.firebase:firebase-auth@@21.0.5:22)
        at com.google.android.gms.internal.firebase-auth-api.zztw.zzq(com.google.firebase:firebase-auth@@21.0.5:4)
        at com.google.android.gms.internal.firebase-auth-api.zzrm.zzA(com.google.firebase:firebase-auth@@21.0.5:4)
        at com.google.android.gms.internal.firebase-auth-api.zzti.zzu(com.google.firebase:firebase-auth@@21.0.5:5)
        at com.google.android.gms.internal.firebase-auth-api.zzso.zzc(com.google.firebase:firebase-auth@@21.0.5:1)
        at com.google.android.gms.internal.firebase-auth-api.zzuj.run(com.google.firebase:firebase-auth@@21.0.5:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2022-07-01 19:07:14.012 20676-20725/? E/ReactNativeJS: 'Unhandled promise rejection', [Error: [auth/configuration-not] An internal error has occurred. [ CONFIGURATION_NOT_FOUND ]]
2022-07-01 19:07:14.016 1787-9585/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
2022-07-01 19:07:14.023 20676-20726/? E/unknown:ReactNative: console.error: Unhandled promise rejection Error: [auth/configuration-not] An internal error has occurred. [ CONFIGURATION_NOT_FOUND ], js engine: hermes, stack:
    _construct@1:190114
    Wrapper@1:189768
    _createSuperInternal@1:187841
    SyntheticError@1:189236
    reactConsoleErrorHandler@1:188869
    anonymous@1:2979998
    dispatchEvent@1:2974402
    anonymous@1:2974604
    anonymous@1:2980043
    anonymous@1:2974508
    anonymous@1:210307
    _callTimer@1:209251
    _callReactNativeMicrotasksPass@1:209456
    callReactNativeMicrotasks@1:211390
    __callReactNativeMicrotasks@1:199270
    anonymous@1:198402
    __guard@1:199147
    flushedQueue@1:198313
    invokeCallbackAndReturnFlushedQueue@1:198256` 

Does someone have any suggestions how to fix it?

**Comment by mikehardy** [comment]
My first search result here looks about right for the possible causes

https://search.brave.com/search?q=com.google.firebase.FirebaseException%3A+An+internal+error+has+occurred.+%5B+CONFIGURATION_NOT_FOUND+%5D+at+com.google.android.gms.internal.firebase-auth-api.zztj.zza(com.google.firebase%3Afirebase-auth%40%4021.0.5%3A4)

maybe triple check project config in firebase console for allowed auth methods, re-download the config files (google-services.json) make sure they are in your release build and re try?

**Comment by evgenyshenets** [comment]
I have rechecked the or more times in debug mode it works but when I make assembleRelease with correct keystore, it still returns CONFIGURATION_NOT_FOUND
