### ISSUE TITLE
[🐛] Crashlytics - No report sent with a crash from CSS bad value on Android

### ISSUE THREAD

**Issue by GautierAnd** [invertase/react-native-firebase#6747]
## Issue

Hi everybody,

On Android TV (not tested on tvOS), if i write an error in the CSS of my code, the app crashes.
Error sample :
```js
const styles = StyleSheet.create({
  container: {
    height: 'calc(100% - 10)',
});
```
This is the error stack generated on Android:
```
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:117)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320)
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:261)
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:505)
        at com.facebook.react.uimanager.ReanimatedUIManager.createView(ReanimatedUIManager.java:72)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:209)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:914)
     Caused by: java.lang.IllegalArgumentException: Unknown value: calc(100% - 960)
        at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:63)
        at com.facebook.react.uimanager.LayoutShadowNode.setHeight(LayoutShadowNode.java:154)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:117) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65) 
        at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320) 
        at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:261) 
        at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:505) 
        at com.facebook.react.uimanager.ReanimatedUIManager.createView(ReanimatedUIManager.java:72) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:209) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) 
        at java.lang.Thread.run(Thread.java:914) 
D/EventLogger: isPlaying [eventTime=10.68, mediaPos=7.81, window=0, period=0, false]
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 25413 (mqt_native_modu), pid 25365 (r.playsuisse.tv)
```

With this type of error, Crashlytics reports are never sent. 
Did I miss something with the setup or is this a bug from the package ?

Thank in advance,
Gautier.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 126.04 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2022.06.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 16, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 28.0.1, 28.0.3, 29.0.1, 30.0.2, 31.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google TV Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_221 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    @sebastien_rts/react-native-tvos:  0.68.2-7-15
    react: 17.0.2 => 17.0.2
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `^16.4.6`
- **`Firebase` module(s) you're using that has the issue:**
  - `Crashlytics`
- **Are you using `TypeScript`?**
  - `Y` & `~4.5.5`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Hi there!

It is a shame that you opted to ignore the template, it could have saved some time by allowing you to access help:

```
firebase.json for react-native-firebase v6:
# N/A
```

https://stackoverflow.com/help/how-to-ask


You'll want to read this in order to configure things well and so you know how to verify they are configured well: https://invertase.io/blog/react-native-firebase-crashlytics-configuration

In the absence of information needed to help and with the idea the configuration guide above should get you there I'll close this as un-actionable

If you follow that guide and provide details to reproduce the problem we can revisit

**Comment by GautierAnd** [comment]
Hi again @mikehardy,
I've updated my issue with the most information I could to complete the pattern.
And I've added steps to reproduce the bug.
If it is OK for you, could you re-open the issue please ?

**Comment by mikehardy** [comment]
Your firebase.json does not seem to follow the guide here https://invertase.io/blog/react-native-firebase-crashlytics-configuration - I expect something more like 

```json
{
  "react-native": {
    "crashlytics_debug_enabled": true,
    "crashlytics_disable_auto_disabler": true,
    "crashlytics_auto_collection_enabled": true,
    "crashlytics_is_error_generation_on_js_crash_enabled": true,
    "crashlytics_javascript_exception_handler_chaining_enabled": true
  }
}
```

Please confirm you have followed that guide, made those changes, rebuilt the app, re-tested it watching adb logcat as instructed (that is, `adb logcat | grep -i crash`) and describe what you saw

**Comment by GautierAnd** [comment]
Thank for the feedback, I've fixed my firebase.json.
I followed the guide and everything went well. I've correctly received the crash report after I clicked on the button with `undefinedVariable.notAFunction();` code.

After this, I tried to connect logcat with my CSS crash and this is what I got.
**Before the crash**
```
11-30 11:22:35.059  7822  7822 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
11-30 11:22:45.943  7874  7874 I FirebaseCrashlytics: Initializing Firebase Crashlytics 18.3.2 for ch.srgssr.playsuisse.tv
11-30 11:22:46.045  7874  7874 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBJSON: true
11-30 11:22:46.045  7874  7874 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled after checking crashlytics_debug_enabled: true
11-30 11:22:46.045  7874  7874 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:22:46.045  7874  7906 D libcrashlytics: Initializing libcrashlytics version 3.2.0
11-30 11:22:46.048  7874  7874 I RNFBCrashlyticsInit: initialization successful
11-30 11:22:46.054  7874  7906 D libcrashlytics: Initializing native crash handling successful.
11-30 11:22:54.889  7874  7963 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBJSON: true
11-30 11:22:54.889  7874  7963 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled after checking crashlytics_debug_enabled: true
11-30 11:22:54.889  7874  7963 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:22:54.889  7874  7963 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled via RNFBJSON: true
11-30 11:22:54.889  7874  7963 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled final value: true
11-30 11:22:54.889  7874  7963 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled via RNFBJSON: true
11-30 11:22:54.889  7874  7963 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled final value: true
11-30 11:23:29.013  8941  8941 D AndroidRuntime: Calling main entry org.chromium.components.crash.browser.CrashpadMain
11-30 11:23:29.888  9012  9012 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
11-30 11:23:29.894  1745  1745 I /system/bin/tombstoned: received crash request for pid 7964
11-30 11:23:29.905  9012  9012 I crash_dump32: performing dump of process 7874 (target tid = 7964)
11-30 11:23:30.046  9012  9012 W crash_dump32: type=1400 audit(0.0:3313): avc: denied { read } for name="u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=7273 scontext=u:r:crash_dump:s0:c60,c256,c512,c768 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=0 app=ch.srgssr.playsuisse.tv
```

**After the crash**
```
11-30 11:25:29.851  9134  9134 I FirebaseCrashlytics: Initializing Firebase Crashlytics 18.3.2 for ch.srgssr.playsuisse.tv
11-30 11:25:29.986  9134  9134 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBJSON: true
11-30 11:25:29.986  9134  9134 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled after checking crashlytics_debug_enabled: true
11-30 11:25:29.986  9134  9134 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:25:29.988  9134  9134 I RNFBCrashlyticsInit: initialization successful
11-30 11:25:29.994  9134  9171 D libcrashlytics: Initializing libcrashlytics version 3.2.0
11-30 11:25:30.004  9134  9171 D libcrashlytics: Initializing native crash handling successful.
11-30 11:25:38.784  9134  9231 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBJSON: true
11-30 11:25:38.785  9134  9231 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled after checking crashlytics_debug_enabled: true
11-30 11:25:38.785  9134  9231 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:25:38.785  9134  9231 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled via RNFBJSON: true
11-30 11:25:38.785  9134  9231 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled final value: true
11-30 11:25:38.785  9134  9231 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled via RNFBJSON: true
11-30 11:25:38.785  9134  9231 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled final value: true
```
And still no report received...

**Comment by mikehardy** [comment]
#6749 is a PR to update the docs a bit, the link for NDK config was stale and need to upload symbols was not noted

**Comment by GautierAnd** [comment]
I've enabled NDK reporting (https://rnfirebase.io/crashlytics/android-setup#4-optional-enable-crashlytics-ndk-reporting)
And I reproduced the "CSS crash" in release variant. Unfortunately, I still don't receive report.

Here is `adb logcat | grep -i crash` logs
**Before crash**
```
11-30 11:52:09.123 12047 12047 I FirebaseCrashlytics: Initializing Firebase Crashlytics 18.3.2 for ch.srgssr.playsuisse.tv
11-30 11:52:09.243 12047 12047 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBMeta: true
11-30 11:52:09.243 12047 12047 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:52:09.243 12047 12047 I RNFBCrashlyticsInit: initialization successful
11-30 11:52:09.249 12047 12080 D libcrashlytics: Initializing libcrashlytics version 3.2.0
11-30 11:52:09.267 12047 12080 D libcrashlytics: Initializing native crash handling successful.
11-30 11:52:09.308 12047 12047 D ApkSoSource: not allowing consideration of lib/x86/libcrashlytics-common.so: deferring to libdir
11-30 11:52:09.309 12047 12047 D ApkSoSource: not allowing consideration of lib/x86/libcrashlytics-handler.so: deferring to libdir
11-30 11:52:09.309 12047 12047 D ApkSoSource: not allowing consideration of lib/x86/libcrashlytics-trampoline.so: deferring to libdir
11-30 11:52:09.309 12047 12047 D ApkSoSource: not allowing consideration of lib/x86/libcrashlytics.so: deferring to libdir
11-30 11:52:10.110 12047 12047 E chromium: [ERROR:filesystem_posix.cc(89)] stat /data/user/0/ch.srgssr.playsuisse.tv/cache/WebView/Crashpad: No such file or directory (2)
11-30 11:52:10.110 12047 12047 E chromium: [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/ch.srgssr.playsuisse.tv/cache/WebView/Crashpad: No such file or directory (2)
11-30 11:52:10.952 12047 12138 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBMeta: true
11-30 11:52:10.952 12047 12138 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:52:10.953 12047 12138 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled via RNFBMeta: true
11-30 11:52:10.953 12047 12138 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled final value: true
11-30 11:52:10.956 12047 12138 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled via RNFBMeta: true
11-30 11:52:10.956 12047 12138 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled final value: true
11-30 11:53:33.444 13185 13185 D AndroidRuntime: Calling main entry org.chromium.components.crash.browser.CrashpadMain
11-30 11:53:33.890 13227 13227 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
11-30 11:53:33.891  1745  1745 I /system/bin/tombstoned: received crash request for pid 12139
11-30 11:53:33.892 13227 13227 I crash_dump32: performing dump of process 12047 (target tid = 12139)
```

**After crash**
```
11-30 11:56:08.685 13299 13299 I FirebaseCrashlytics: Initializing Firebase Crashlytics 18.3.2 for ch.srgssr.playsuisse.tv
11-30 11:56:08.743 13299 13331 D libcrashlytics: Initializing libcrashlytics version 3.2.0
11-30 11:56:08.749 13299 13299 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBMeta: true
11-30 11:56:08.749 13299 13299 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:56:08.756 13299 13299 I RNFBCrashlyticsInit: initialization successful
11-30 11:56:08.760 13299 13331 D libcrashlytics: Initializing native crash handling successful.
11-30 11:56:10.750 13299 13373 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled via RNFBMeta: true
11-30 11:56:10.750 13299 13373 D RNFBCrashlyticsInit: isCrashlyticsCollectionEnabled final value: true
11-30 11:56:10.751 13299 13373 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled via RNFBMeta: true
11-30 11:56:10.751 13299 13373 D RNFBCrashlyticsInit: isErrorGenerationOnJSCrashEnabled final value: true
11-30 11:56:10.753 13299 13373 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled via RNFBMeta: true
11-30 11:56:10.753 13299 13373 D RNFBCrashlyticsInit: isCrashlyticsJavascriptExceptionHandlerChainingEnabled final value: true
```
