### ISSUE TITLE
[🐛][🔥] [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key

### ISSUE THREAD

**Issue by tomwanzek** [invertase/react-native-firebase#6830]
## Issue

Describe your issue here

As of this morning (EDT), when running our app in the iOS Simulator, we are seeing this Firebase Messaging Error message:

> NativeFirebaseError: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key

**We have made no Firebase or React Native related changes to our dependencies or code base over night.**

The only change was locally running `pod install` for a patch version upgrade of a completely unrelated library (react-native-rate) on a working branch. However, even go back to the main branch without the lib upgrade, cleaning, running `yarn` and `pod install` creates the new issue on the `main` branch as well.

The error is thrown on the `messaging().getToken()` invocation.

The issue does not  replicate on Android it seems.

It is also not **_currently_** affecting our deployed environments STAGING and PROD.
However, those environments, did not yet see a build-deploy cycle today. (Last Staging CI Deployment run was 2 days ago).

So if this error is due to some deep iOS lib dependency of RN Firebase, while our `Podfile.lock` does not have any tracked changes related to RN Firebase, we are worried that the issue propagates with the next Deployment runs.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

Relevant snippet from `Podfile.lock`:

```
  - Firebase/AnalyticsWithoutAdIdSupport (8.9.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 8.9.1)
  - Firebase/CoreOnly (8.9.1):
    - FirebaseCore (= 8.9.1)
  - Firebase/Messaging (8.9.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 8.9.0)
  - FirebaseAnalytics/WithoutAdIdSupport (8.9.1):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
 ```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 21.67 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1673461052290-0.6051340710415349/node
    Yarn: 1.22.17 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1673461052290-0.6051340710415349/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `13.0.1`

We are currently exploring the upgrade path, given the breaking change with `use_frameworks!` introduces in RN Firebase 15.x

- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.6.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by livnunes** [comment]
In my case there was no changes at all, no pod install, nothing, some users that have the application from the App Store just messaged us mentioning they could not use the app, I then tried on the iPhone I had with me using iOS 12 and everything worked fine, so then I tried on the Simulator with iOS 16.2 and to my surprise the app was stuck on messaging().getToken() like you mentioned. Though this is a very strange case, I thought this was specific to the version 16.2. But one of my colleagues with an iPhone X on iOS 16.2, tried the app and told me nothing was wrong on his end.

**Comment by Stackerr** [comment]
same bug,

**Comment by tomwanzek** [comment]
Sorry, just wondering, if this ticket can get some triage priority?

As mentioned and confirmed by several reports, this issue seems to have started without any changes to the affected apps. So there is nothing to roll-back/undo in order to avoid it.

Based on at least one report, it seems to have started to affect users in PROD, i.e. 

> some users that have the application from the App Store just messaged us mentioning they could not use the app

**Comment by SwikarBhattarai** [comment]
same issue, need to fix this asap.

**Comment by sonorus-eric** [comment]
same issue, need to fix this asap. +1

**Comment by FredrikLastow** [comment]
Same issue here too! Would love a fix on this asap.

**Comment by tomwanzek** [comment]
While not directly related, it seems contextually interesting that we have started seeing some other previously non-existent behaviors with the Firebase Messaging SDK/React Native Firebase Messaging.

We were doing some regression testing for an upgrade of our RN Instabug integration in the App, and encountered another error on iOS, which we had never seen "surfaced" to our error reporting:

* `[messaging/unknown] The Internet connection appears to be offline.` This message was logged as part of a scenario were we deliberately took down the network (router offline for Wifi). Historically, I suspect, this might have been handled "silently" by the Messaging SDK?

Again, just for context if that helps narrow down how the `messaging.getToken()` issue made it into a codebase that had not updated Firebase dependencies when the error started to occur.

**Comment by jfbourne** [comment]
+1  Aso randomly start seeing this  issue.

**Comment by cflorez10** [comment]
+1 Aso randomly started seeing this issue.

**Comment by lopei** [comment]
Also reproduced in the native iOS Firebase SDK, iOS 16.1

**Comment by AvasarInc** [comment]
+1 Aso randomly started seeing this issue.

**Comment by hieuminh1810** [comment]
+1 same

**Comment by jhedenius** [comment]
+1 We are experiencing the same

**Comment by novalain** [comment]
+1 Happening in the Unity SDK in our prod app

**Comment by iamcxa** [comment]
+1 same problem here,  rn 0.70.5 + react-native-firebase 16.5.0

**Comment by qsdamar** [comment]
+1 same issue, RN 0.65.3 + react-native-firebase 14.9.0, happens only on iOS simulator in debug mode. Debug mode for Android works fine. Production versions work fine on both iOS and Android.

**Comment by balgamat** [comment]
Happens to us as well, when trying to subscribe/unsubscribe from topics: react-native-firebase 16.4.3, react-native 0.69.3, firebase@9.15.0

**Comment by KrisLau** [comment]
Error logging is new but I think its just telling you that you can't test the fcm on iOS simulator as indicated here: https://rnfirebase.io/messaging/usage#receiving-messages

> iOS simulators however do not handle cloud messages

**Comment by darpsoft** [comment]
+1 We are experiencing the same

**Comment by tyartyartyar** [comment]
+1, I am experiencing the same

**Comment by Choyeongdeok** [comment]
+1
got a NativeFirebaseError: [messaging/unknown] Invalid fetch response, expected 'token' or 'Error' key

**Comment by raulnoz** [comment]
> Error logging is new but I think its just telling you that you can't test the fcm on iOS simulator as indicated in the docs: https://rnfirebase.io/messaging/usage#receiving-messages
> 
> > iOS simulators however do not handle cloud messages
> 
> If you run the app on a physical iPhone, the error message does not appear

In my case it appears on physical iPhone too.

**Comment by madmeatballs** [comment]
+1, also experiencing this issue in our project on our iOS simulator. On Android Sim it works fine.

**Comment by shinwenli** [comment]
I had the same problem with "cordova-plugin-firebasex".
At that time, as a workaround, I was able to start the system by executing getToken processing again using "try{}catch{}", so I will share it.
An error occurred during processing, but the token itself was correctly acquired.

**Comment by sajin1010** [comment]
+1 , got issue in ios simulator , no issues in android emulator.
 
 Possible Unhandled Promise Rejection (id: 5):
Error: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key
NativeFirebaseError: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key

- @react-native-firebase/messaging": "^15.3.0
- react-native": "0.69.1

**Comment by livnunes** [comment]
> Error logging is new but I think its just telling you that you can't test the fcm on iOS simulator as indicated in the docs: https://rnfirebase.io/messaging/usage#receiving-messages
> 
> > iOS simulators however do not handle cloud messages
> 
> If you run the app on a physical iPhone, the error message does not appear

What version of iOS did you run on your device and on the simulator? This error is appearing on physical devices as well, depending on their versions, 16.2 being one of them.

**Comment by maddeha** [comment]
+1 same

**Comment by ale-mazz** [comment]
+1

**Comment by christianrank** [comment]
please stop spamming everyone by posting `+1`, thank you!

**Comment by Tahir-7cTech** [comment]
facing same issue in my Flutter app. FCM just stopped working with the following error

```bash
FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSLocalizedFailureReason = "Invalid fetch response, expected 'token' or 'Error' key";
}
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:518:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:224:11)
<asynchronous suspension>
#4      _MyAppState.requestAndRegisterNotification (package:myapp/main.dart:174:23)
````

**Comment by faizanbutt** [comment]
Looks like the issue is only on the simulator and (or emulator).
I was struggling with this issue on simulator since this morning and when tried on real iPhone and android, it's working fine on both the devices.

**Comment by jobayer977** [comment]
Facing Same issues

**Comment by incom-app-ru** [comment]
I have the same problem. I use Flipper for blogs.
It shows two messages:

First this:
10.3.0 - [FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '1153--------'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

And then this:
Possible Unhandled Promise Rejection (id: 0):
Error: [messaging/unknown] The operation could not be completed. Invalid fetch response, expected 'token' or 'Error' key

**Comment by starpl** [comment]
Having same problem, both on device and simulator

I wonder if it's because Google changed their API? The type of response, in particular
Although I think I saw response which was something like "token=...." and everything worked
But it does not work with an "Error" in the response (can't find a key), although it should, based on
```
Error: [messaging/unknown] The operation could not be completed. Invalid fetch response, expected 'token' or 'Error' key
```

**Comment by tomwanzek** [comment]
Just to **recap the status to date based on what I see in the various responses**:

1) The issue started occurring suddenly on January 11th for us, January 10th worked fine and we had made no changes to the Firebase related dependencies and code
2) While a fair share of reports were first notice on simulators (including ours)
    a) There are at least some reports of the issue occurring in deployed environments on physical devices
    b) even on Simulator this error was not thrown before and is a breaking change


For robustness, we actually ended up deploying a code change to STAGING and PROD, to allow the app to proceed with the app initialization even if the FCM getToken fails, while still reporting a potential error to our Instabug instance for visibility.

**Comment by KrisLau** [comment]
@mikehardy Any idea as to what might be causing the appearance of this error?

**Comment by miteshdb** [comment]
Everyone is experiencing the same problem, and there is no change in code, need to get to the bottom of it as asap, Help would be appreciated

**Comment by KrisLau** [comment]
For anyone experiencing this for now, just add a try catch so that the error doesn't crash the app/stop your processes . 

> What version of iOS did you run on your device and on the simulator? This error is appearing on physical devices as well, depending on their versions, 16.2 being one of them.

@livnunes I use iOS 13.4. I don't have any other physical devices to test on unfortunately so I cannot test other iOS versions.

**Comment by rmanguinho** [comment]
That was my concern when moved from native to Flutter. This kind of error and the lack of support is just so bad

**Comment by raulnoz** [comment]
> Could be related to the recent change of the native iOS SDK?
> 
> > On app startup, an APNs Token must be provided to FCM SDK before retrieving an FCM Token, otherwise an error will be returned as part of the completion.
> 
> https://firebase.google.com/support/release-notes/ios#version_1040_-_january_17_2023

It's exactly that

https://github.com/firebase/firebase-ios-sdk/issues/10679

**Comment by cuechi** [comment]
same problem here guys, please fix it asap.

**Comment by raulnoz** [comment]
Asap = when Google want

**Comment by mikehardy** [comment]
Hey there, just a friendly reminder - let's keep things collaborative and on-topic, yes?

It appears to. be a firebase-ios-sdk issue and they are aware of it: https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1387056826

I suggest folks follow along on that issue, I'm not sure we will be able to resolve it here at this level

**Comment by sayyidisal** [comment]
Well, I found this issue yesterday.
And today, I can get the token from fcm.
What I do to fix this problem is change my code using try catch to get token from fcm.

Before :
`const fcmToken = await messaging().getToken()

    if (fcmToken) {
      console.log(fcmToken)
    }`

After : 
`try {
      const fcmToken = await messaging().getToken()
      if (fcmToken) {
        console.log('Your Token : ', fcmToken)
      }
    } catch (error) {
      console.log(error)
    }`

Hopefully this is can help someone who faced same problem like me.

**Comment by sajin1010** [comment]
> +1 , got issue in ios simulator , no issues in android emulator.
> 
> Possible Unhandled Promise Rejection (id: 5): Error: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key NativeFirebaseError: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key
> 
> * @react-native-firebase/messaging": "^15.3.0
> * react-native": "0.69.1

it is working fine now ios simulator,  didn't change anything, seems it was an issue with google server.

**Comment by HossamAbdelnasser0110** [comment]
I encountered the issue yesterday, but today everything works as expected without changing anything

**Comment by mnccouk** [comment]
Looks like some of the issues on here may be related to a server FCM change - see https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1387681398. It was rolled back last night, for me this fixed the issue.

**Comment by Tahir-7cTech** [comment]
Thanks issue is fixed

**Comment by mikehardy** [comment]
Thanks everyone for the patience - this is resolved - temporarily - by firebase team rolling back a server change

However, and this is important, there is some necessary change required for us to adopt firebase-ios-sdk 10.4.0, as **our e2e test harness here does not pass token-related messaging tests with 10.4.0**

That implies that if you are among the small number of react-native-firebase users that use Podfile overrides to specify the firebase-ios-sdk version (always possible as a "just in case" capability) it is not safe to use 10.4.0 yet. So we're not finished here.

I'm going to leave this open pending guidance from firebase team on that change

**Comment by mikehardy** [comment]
## Current status

In collaboration with the firebase-ios-sdk team, I/we think these things:

----
After review and some investigation from the firebase-ios-sdk crew, we have some news on the new “No FCM token if you do not have an APNS token” behavior change in firebase-ios-sdk 10.4.0. 

1) simulator can get an APNS token, but only on Apple Silicon with macOS 13+ and iOS 16+ it seems, which means tests are unavoidably broken on current github x86-64 actions runners. 

2) Firebase messaging will let you set a fabricated / dummy APNS token, so you can exercise FCM token APIs in Simulator on non-APNS-receiving environments, if you want. They will store that thing in their cloud backend though so if having it be persistent is bad, make sure to delete the token(s) after testing.
----

## Current plans

To move this forward, will likely be a few days though unless someone listening in here wants to override their SDK version to 10.4.0 and try the following:

----

Next steps: 

1) check our e2e app on a real device (if possible? last time I tried it did not work for me, I forget why) to make sure things are working with firebase-ios-sdk 10.4.0 on a real device. It should be working? But we may discover race conditions between “APNS token is requested then obtained” and “We request an FCM token (maybe before APNS token is obtained…)“. 

2) See how things work with Simulator on an M1 mac (I have one) which is nearly the same as item 1 here. and 

3) try the “make up and setAPNS in tests” style of making CI work so we can at least continue exercising FCM APIs

**Comment by mikehardy** [comment]
@santhosh-umapathi-appymango that's unexpected 🤔  - you might check to see if there is any sort of token delete or invalidation logic in your app anywhere. I'm not aware of why the APNS token would be removed from the app or the FCM subsystem unless done explicitly, but we may be about to learn something based on results of any investigation you perform...

**Comment by mikehardy** [comment]
Indeed, all of these activities are asynchronous and depend on the network, so 2 seconds likely works well as a heuristic but sometimes it may be 10ms and perhaps it never happens, perhaps better to have a retry loop on messaging().getAPNSToken() (which is local - it *depends* on the token coming in asynchronously and calling an AppDelegate callback, but `.getAPNSToken()` itself is a local call that will just return null until it comes in...)

Then you can call getAPNSToken in a somewhat tighter loop (maybe every 500ms or something?) with a more slack full timeout (maybe give up completely after 60 seconds and warn user that some functionality will be disabled?), as soon as the APNS token comes in you should be safe to call `getToken()` to get the FCM token.

What do you think?

**Comment by k2xl** [comment]
@santhosh-umapathi-appymango  This method didn't work for me... It tries 3 times and errors each time. I even tried with a setTimeout between each...

Did you do anything else to make this work?

**Comment by ademirtemur** [comment]
i think, it is your xcode version, if you use xcode 15.2 or highest xcode. you can try after upgrade the device's software version.

**Comment by VilleMiekkoja** [comment]
For me, the getAPNSToken returns the mock token nicely (on iOS simulator), but I still get the error:

[Error: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key]
