### ISSUE TITLE
[🐛] ReactActivity class cannot be cast to com.facebook.react.ReactApplication

### ISSUE THREAD

**Issue by halitsever** [invertase/react-native-firebase#6885]
## Issue

At the moment, I integrate my native application into react native, but I need to use firebase cloud messaging from within react.

When I install @react-native-firebase/messaging, it seems to work, but when I put the app in the background, the app crashes when the notification comes.

The error message:

` java.lang.RuntimeException: Unable to start service io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService with Intent { cmp=com.test.example/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: java.lang.ClassCastException: ReactActivity cannot be cast to com.facebook.react.ReactApplication
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3686)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:199)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)`

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by halitsever** [comment]
Ok now I realized that the problem is not related to @react-native-firebase/messaging.

Actually, my application does not have an Application class.

For this, I created a new class:



```import android.app.Application;
import com.facebook.react.BuildConfig;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost =
            new ReactNativeHost(this) {
                @Override
                public boolean getUseDeveloperSupport() {
                    return BuildConfig.DEBUG;
                }

                @Override
                protected List<ReactPackage> getPackages() {
                    @SuppressWarnings("UnnecessaryLocalVariable")
                    List<ReactPackage> packages = new PackageList(this).getPackages();
                    return packages;
                }

                @Override
                protected String getJSMainModuleName() {
                    return "index";
                }


            };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, false);
    }


}

```



And then I added the value android:name to the AndroidManifest file.

```<application
android:name="com.halitsever.MainApplication"
...
```

Rn its working.
