### ISSUE TITLE
Error while trying to use firebase@3.1 with RN@0.49

### ISSUE THREAD

**Issue by Gshock1** [invertase/react-native-firebase#702]
Hi,

I'm trying to import firebase to my react native application (android) but get this error:

`com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzfgn;
      at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
       at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
 at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
       at com.android.dx.command.Main.main(Main.java:106)`

I was working with this tutorial: [Link](https://rnfirebase.io/docs/v3.1.*/installation/android)
What am I doing wrong?

**Comment by gazaret** [comment]
Hi @Gshock1, error occurs when duplicating android dependencies. In my case "react-native-device-info" contain duplicate com.google.android.gms.

I solved this with (in android/app/build.gradle):
```
compile ("com.google.android.gms:play-services-base:11.6.0") {
  force = true;
}
compile(project(':react-native-device-info')){
   exclude group: 'com.google.android.gms', module: 'play-services-base'
   exclude group: 'com.google.android.gms', module: 'play-services-basement'
}
```

also read this https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f

**Comment by chrisbianca** [comment]
Closing as @gazaret 's suggestion is correct. Please re-open if this is still an issue with RNFirebase
