### ISSUE TITLE
Didn't find class "io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver"

### ISSUE THREAD

**Issue by adityalxme** [invertase/react-native-firebase#7408]
Hi Team,

We are getting below to many occurrences of below fatal exception in Firebase crashlytics 

Fatal Exception: java.lang.RuntimeException: Unable to instantiate receiver io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver: java.lang.ClassNotFoundException: Didn't find class "io.invertase.firebase.notifications.RNFirebaseNotificationsRebootReceiver" on path: DexPathList[[zip file "/data/app/~~1JlKvHeVP58SghtKEG_vfg==/com.lxme-lYyqmkdZXgMzHeGTRjCJIw==/base.apk"],nativeLibraryDirectories=[/data/app/~~1JlKvHeVP58SghtKEG_vfg==/com.lxme-lYyqmkdZXgMzHeGTRjCJIw==/lib/arm64, /data/app/~~1JlKvHeVP58SghtKEG_vfg==/com.lxme-lYyqmkdZXgMzHeGTRjCJIw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4519)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8381)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by mikehardy** [comment]
No template.
