### ISSUE TITLE
[🐛] 🔥 error: `pod install` after `yarn add @react-native-firebase/auth` 

### ISSUE THREAD

**Issue by CezarCobuz** [invertase/react-native-firebase#7428]
## Issue

Running `pod install` after `yarn add @react-native-firebase/auth` throws an error.

```
JSON::ParserError - Failed to parse JSON at file: '/Users/cezar/.cocoapods/repos/trunk/Specs/c/1/1/RecaptchaInterop/100.0.0/RecaptchaInterop.podspec.json'.

unexpected token at ''
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification.rb:752:in `from_string'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification.rb:726:in `from_file'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source.rb:188:in `specification'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/set.rb:56:in `each'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `each'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:422:in `analyze'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:162:in `install!'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/Users/cezar/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/Users/cezar/.asdf/installs/ruby/3.2.2/bin/pod:25:in `load'
/Users/cezar/.asdf/installs/ruby/3.2.2/bin/pod:25:in `<main>'

```

`@react-native-firebase/app` is set up correctly.

Running `pod install` works fine if I don't `yarn add @react-native-firebase/auth`

The issue persists after trying to [clean and reinstall cocoapods](https://stackoverflow.com/a/60849495/8597377)

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "MyCoolApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "prepare": "cd ../ && husky install mobile-app/.husky"
  },
  "dependencies": {
    "@react-native-firebase/app": "^18.6.0",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.14",
    "@tanstack/react-query": "^5.4.3",
    "d3": "^7.8.5",
    "react": "18.2.0",
    "react-intl": "^6.5.0",
    "react-native": "0.72.5",
    "react-native-gesture-handler": "^2.13.3",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-paper": "^5.10.6",
    "react-native-reanimated": "^3.5.4",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-svg": "^13.14.0",
    "react-native-vector-icons": "^10.0.0",
    "react-native-video": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tanstack/eslint-plugin-query": "^5.0.5",
    "@tsconfig/react-native": "^3.0.0",
    "@types/d3": "^7.4.2",
    "@types/react": "^18.0.24",
    "@types/react-native-vector-icons": "^6.4.15",
    "@types/react-native-video": "^5.0.17",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "husky": "^8.0.3",
    "jest": "^29.2.1",
    "lint-staged": "^15.0.2",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}

```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyCoolApp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static # for Firebase
  $RNFirebaseAsStaticFramework = true # for Firebase

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyCoolAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

It works on Android

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 122.39 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: ~/.asdf/installs/nodejs/20.9.0/bin/node
  Yarn:
    version: 1.22.18
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.1.0
    path: ~/.asdf/plugins/nodejs/shims/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /Users/cezar/.asdf/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/cezar/.asdf/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 18.6.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `auth`
- **Are you using `TypeScript`?**
  - `Y` & `4.8.4`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by CezarCobuz** [comment]
I was able to get `pod install` to work by adding the file `Specs/c/1/1/RecaptchaInterop/100.0.0/RecaptchaInterop.podspec.json` from CocoaPods [github](https://github.com/CocoaPods/Specs/commit/c8187a8504e4e4feb67e3bcf50a13da29b13bef4) into my `'/Users/cezar/.cocoapods/repos/trunk/Specs/c/1/1/RecaptchaInterop/100.0.0/RecaptchaInterop.podspec.json'` but I am confused why was the file empty in the first place

**Comment by mikehardy** [comment]
This was likely some sort of network transfer error in the cocoapod system's work, and we won't be able to fix it here / it is not actionable so I am going to close this

When I have had this happen before I have used pod commands to fix it (e.g. `pod cache clean` or  `\rm -fr ~/.cocoapods` and a fresh attempt)

Once the local corruption in the cocoapods area is fixed and the specs are downloaded correctly, pod install works again
