### ISSUE TITLE
Error Building React native App- Unable to Resolve @react-native-firebase/app in index.js file

### ISSUE THREAD

**Issue by lachu97** [invertase/react-native-firebase#7880]
Hey guys iam using RN 0.72.0 and firebase package version of 17.5.0 and while in the metro iam getting this error in android inspite of the packages been installed 
 BUNDLE  ./index.js 

error: Error: Unable to resolve module @react-native-firebase/app from /Users/lakshu17/Desktop/DigiSlidesApp/index.js: @react-native-firebase/app could not be found within the project or in these directories:
  node_modules
  /Users/lakshu17/Desktop/DigiSlidesApp/node_modules/@react-native-firebase/app
   5 | import App from './DigiSlides/App';
   6 | import { name as appName } from './app.json';
>  7 | import { initializeApp } from '@react-native-firebase/app';
     |                                ^
   8 |
   9 | initializeApp();
  10 |
    at ModuleResolver.resolveDependency (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
    at Object.resolve (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/DeltaBundler/Graph.js:472:35)
    at Graph._processModule (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/DeltaBundler/Graph.js:260:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/DeltaBundler/Graph.js:248:5)
    at async Promise.all (index 0)
    at async Graph.initialTraverseDependencies (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/DeltaBundler/Graph.js:232:5)
    at async DeltaCalculator._getChangedDependencies (/Users/lakshu17/Desktop/DigiSlidesApp/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:229:25)

**Comment by Lyokone** [comment]
Hello @lachu97, we are currently on version 20.2.0, please update and open another issue if this is still happening.
