### ISSUE TITLE
[Solved] Deprecated .signInWithCredential() causes crash on Android 7.1

### ISSUE THREAD

**Issue by DavideValdo** [invertase/react-native-firebase#860]
I was getting this stacktrace on some Android 7.1 phones (not all) using the Facebook login example code from https://rnfirebase.io/docs/v3.2.x/auth/social-auth

```
com.facebook.react.common.JavascriptException: Can't find variable: callback, stack:
<unknown>@433:543
a@401:3894
value@348:1386
value@391:3107
value@348:1386
<unknown>@347:538
value@32:1363
value@18:3582
<unknown>@18:1067
value@18:3009
value@18:1039

 at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
 at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:754)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
 at android.os.Looper.loop(Looper.java:163)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
 at java.lang.Thread.run(Thread.java:760)
```
First I thought it was AsyncStorage, instead the solution seems to be changing `.signInWithCredential(credential) `with `.signInAndRetrieveDataWithCredential(credential)`, as a warning suggested when debugging on my Android 6.1

**Comment by chrisbianca** [comment]
@DavideValdo this seems strange.  Can I see your code usage?

**Comment by Salakar** [comment]
Closing due to lack of response,
