### ISSUE TITLE
[Test Suite][Android] Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by greena13** [invertase/react-native-firebase#87]
When running any of the database tests, I get the following error inside the test application:

```
Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
on
    RNFirebaseDatabase.java:285
invoke
    Method.java:-2
invoke
    BaseJavaModule.java:319
invoke
    JavaModuleWrapper.java:158
run
    NativeRunnable.java:-2
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:148
run
    MessageQueueThreadImpl.java:196
run
    Thread.java:818
```

I am working from commit `670dfa2` and using `yarn run tests-watch-start` before starting the packager or running the test application.

I'm running the Android test application on an emulator.

This error seems to be occurring in the Android logs right before:

```
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): FirebaseDatabase setPersistenceEnabled exception
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): com.google.firebase.database.DatabaseException: Calls to setPersistenceEnabled() must be made before any other usage of FirebaseDatabase instance.
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at com.google.firebase.database.FirebaseDatabase.zziE(Unknown Source)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at com.google.firebase.database.FirebaseDatabase.setPersistenceEnabled(Unknown Source)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at io.invertase.firebase.database.RNFirebaseDatabase.enablePersistence(RNFirebaseDatabase.java:57)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at java.lang.reflect.Method.invoke(Native Method)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at android.os.Handler.handleCallback(Handler.java:739)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at android.os.Looper.loop(Looper.java:148)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
05-05 06:37:02.817: E/RNFirebaseDatabase(3837): 	at java.lang.Thread.run(Thread.java:818)
```

Followed by this one:

```
05-05 06:37:02.822: E/unknown:React(3837): Exception in native call
05-05 06:37:02.822: E/unknown:React(3837): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
05-05 06:37:02.822: E/unknown:React(3837): 	at io.invertase.firebase.database.RNFirebaseDatabase.on(RNFirebaseDatabase.java:285)
05-05 06:37:02.822: E/unknown:React(3837): 	at java.lang.reflect.Method.invoke(Native Method)
05-05 06:37:02.822: E/unknown:React(3837): 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
05-05 06:37:02.822: E/unknown:React(3837): 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
05-05 06:37:02.822: E/unknown:React(3837): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-05 06:37:02.822: E/unknown:React(3837): 	at android.os.Handler.handleCallback(Handler.java:739)
05-05 06:37:02.822: E/unknown:React(3837): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 06:37:02.822: E/unknown:React(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-05 06:37:02.822: E/unknown:React(3837): 	at android.os.Looper.loop(Looper.java:148)
05-05 06:37:02.822: E/unknown:React(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
05-05 06:37:02.822: E/unknown:React(3837): 	at java.lang.Thread.run(Thread.java:818)
05-05 06:37:02.826: W/MessageQueue(3837): Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f928cd7} sending message to a Handler on a dead thread
05-05 06:37:02.826: W/MessageQueue(3837): java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f928cd7} sending message to a Handler on a dead thread
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.enqueueMessage(Handler.java:631)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.post(Handler.java:326)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.handleCallback(Handler.java:739)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Looper.loop(Looper.java:148)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
05-05 06:37:02.826: W/MessageQueue(3837): 	at java.lang.Thread.run(Thread.java:818)
05-05 06:37:02.826: W/unknown:React(3837): Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-05 06:37:02.826: W/MessageQueue(3837): Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f928cd7} sending message to a Handler on a dead thread
05-05 06:37:02.826: W/MessageQueue(3837): java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f928cd7} sending message to a Handler on a dead thread
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.enqueueMessage(Handler.java:631)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.post(Handler.java:326)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.handleCallback(Handler.java:739)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-05 06:37:02.826: W/MessageQueue(3837): 	at android.os.Looper.loop(Looper.java:148)
05-05 06:37:02.826: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
05-05 06:37:02.826: W/MessageQueue(3837): 	at java.lang.Thread.run(Thread.java:818)
05-05 06:37:02.827: W/unknown:React(3837): Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
05-05 06:37:02.828: W/MessageQueue(3837): Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f928cd7} sending message to a Handler on a dead thread
05-05 06:37:02.828: W/MessageQueue(3837): java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {f928cd7} sending message to a Handler on a dead thread
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.Handler.enqueueMessage(Handler.java:631)
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.Handler.post(Handler.java:326)
05-05 06:37:02.828: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
05-05 06:37:02.828: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.Handler.handleCallback(Handler.java:739)
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 06:37:02.828: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-05 06:37:02.828: W/MessageQueue(3837): 	at android.os.Looper.loop(Looper.java:148)
05-05 06:37:02.828: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
05-05 06:37:02.828: W/MessageQueue(3837): 	at java.lang.Thread.run(Thread.java:818)
05-05 06:37:02.866: W/unknown:React(3837): Tried to enqueue runnable on already finished thread: 'js... dropping Runnable.
05-05 06:37:02.866: W/MessageQueue(3837): Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {d99a9c4} sending message to a Handler on a dead thread
05-05 06:37:02.866: W/MessageQueue(3837): java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {d99a9c4} sending message to a Handler on a dead thread
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.Handler.enqueueMessage(Handler.java:631)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.Handler.post(Handler.java:326)
05-05 06:37:02.866: W/MessageQueue(3837): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
05-05 06:37:02.866: W/MessageQueue(3837): 	at com.facebook.react.bridge.ReactContext.runOnJSQueueThread(ReactContext.java:298)
05-05 06:37:02.866: W/MessageQueue(3837): 	at com.facebook.react.uimanager.events.EventDispatcher$ScheduleDispatchFrameCallback.doFrame(EventDispatcher.java:278)
05-05 06:37:02.866: W/MessageQueue(3837): 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.view.Choreographer.doFrame(Choreographer.java:603)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.Handler.handleCallback(Handler.java:739)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.os.Looper.loop(Looper.java:148)
05-05 06:37:02.866: W/MessageQueue(3837): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
05-05 06:37:02.866: W/MessageQueue(3837): 	at java.lang.reflect.Method.invoke(Native Method)
05-05 06:37:02.866: W/MessageQueue(3837): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
05-05 06:37:02.866: W/MessageQueue(3837): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by greena13** [comment]
This ended up being the result of some seemingly harmless unstaged changes (Renaming the first  parameter of `Reference.on()` from `eventName` to `eventType` in `lib/modules/database/reference.js`).

The parameter name must have some significance beyond what I am seeing.
