### ISSUE TITLE
Android crashing with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by wbattel4607** [invertase/react-native-firebase#872]
### Issue

I haven't gotten this before but in recent versions of RNFirebase I'm running into this. I'm having troubling pinpointing the exact trigger. Any ideas?

```
Fatal Exception: java.lang.NoSuchMethodError: No virtual method getMetadata()Lcom/google/firebase/auth/FirebaseUserMetadata; in class Lcom/google/firebase/auth/FirebaseUser; or its super classes (declaration of 'com.google.firebase.auth.FirebaseUser' appears in /data/app/myapp-1/base.apk)
       at io.invertase.firebase.auth.RNFirebaseAuth.firebaseUserToMap(RNFirebaseAuth.java:1564)
       at io.invertase.firebase.auth.RNFirebaseAuth.access$000(RNFirebaseAuth.java:59)
       at io.invertase.firebase.auth.RNFirebaseAuth$2.onIdTokenChanged(RNFirebaseAuth.java:149)
       at com.google.firebase.auth.zzj.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS High Sierra

3. Build Tools: Android 7.1.1

4. React Native version: 0.53.3

5. RNFirebase Version: 3.3.1

6. Firebase Module: Auth

**Comment by wbattel4607** [comment]
Duplicate of #823, closing.
