### ISSUE TITLE
Conflict with https://github.com/tolu360/react-native-google-places

### ISSUE THREAD

**Issue by fidanoskimkd** [invertase/react-native-firebase#889]
The app crashes with error: 
Anyone experiencing the same? Any ideas on how to resolve this ?
```
FATAL EXCEPTION: Thread-3
    Process: com.reactnative, PID: 14489
    java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzr, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source:113)
 at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.buildGoogleApiClient(RNGooglePlacesModule.java:76)
at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesModule.<init>(RNGooglePlacesModule.java:59)
at com.arttitude360.reactnative.rngoogleplaces.RNGooglePlacesPackage.createNativeModules(RNGooglePlacesPackage.java:29)
 at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
 at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1191)
  at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1161)
  at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1094)
 at com.facebook.react.ReactInstanceManager.access$800(ReactInstanceManager.java:112)
 at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:922)
at java.lang.Thread.run(Thread.java:764)```

**Comment by chrisbianca** [comment]
@fidanoskimkd the react-native-google-places library is using v10.2.4 of google play services. You should speak to them about upgrading to a later version (we're currently on 11.8.0).

**Comment by fidanoskimkd** [comment]
@chrisbianca Do you have any working version that uses the v.10.2.4 of google play services that I could downgrade to?

**Comment by chrisbianca** [comment]
@fidanoskimkd You'd have to go back to our v1.x stream, but you'd lose out on lots and lots of functionality and bug fixes.  We no longer support this version.

See: https://github.com/invertase/react-native-firebase#supported-firebase-features and: https://github.com/invertase/react-native-firebase#supported-versions---react-native--firebase

**Comment by fidanoskimkd** [comment]
@chrisbianca thank you very much for your assistance

**Comment by DimitrisTzimikas** [comment]
@fidanoskimkd do you find how to fix this?
