### ISSUE TITLE
Unable to use react native firebsae with test frameworks

### ISSUE THREAD

**Issue by nodesman** [invertase/react-native-firebase#901]
### Issue

I am attempting to use react-native-firebase in a project that will have Jest/Mocha based unit tests. When running unit tests against files that include react-native-firebase, I get the following error:

```
/Users/raj/Documents/projects/wind/mobile/node_modules/react-native-firebase/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { import Firebase from './modules/core/firebase';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions..js (/Users/raj/Documents/projects/wind/mobile/test/compiler.js:12:49)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raj/Documents/projects/wind/mobile/src/App.js:9:26)
    at Module._compile (module.js:624:30)
    at Object.require.extensions..js (/Users/raj/Documents/projects/wind/mobile/test/compiler.js:19:17)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raj/Documents/projects/wind/mobile/test/App.test.js:2:10)
    at Module._compile (module.js:624:30)
    at Object.require.extensions..js (/Users/raj/Documents/projects/wind/mobile/test/compiler.js:19:17)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at /Users/raj/.nvm/versions/node/v8.7.0/lib/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/raj/.nvm/versions/node/v8.7.0/lib/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/raj/.nvm/versions/node/v8.7.0/lib/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/Users/raj/.nvm/versions/node/v8.7.0/lib/node_modules/mocha/bin/_mocha:582:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
My research indicates that these test tools expect a CommonJs based module export from all included libraries. Could you please make all exports available in CommonJs format also?

**Comment by Salakar** [comment]
@nodesman this is a React Native library - it's not going to work anywhere but in React Native unless you write your own debugging bridge for node. 

For testing React Native apps I'd recommend you use https://github.com/wix/detox - a starter application with detox tests pre-setup can be find here: https://github.com/ueno-llc/react-native-starter for reference
