### ISSUE TITLE
No virtual method getDocument()

### ISSUE THREAD

**Issue by ntomallen** [invertase/react-native-firebase#913]
Hoping this will help someone else.

My Android app was crashing today after updating to `4.0.0rc2`, so by debugging in Android I came across this error:

```
03-26 18:22:49.356 4083-4083/com.name E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.name, PID: 4083
java.lang.NoSuchMethodError: No virtual method getDocument()Lcom/google/firebase/firestore/QueryDocumentSnapshot; in class Lcom/google/firebase/firestore/DocumentChange; or its super classes (declaration of 'com.google.firebase.firestore.DocumentChange' appears in /data/app/com.name-2/base.apk:classes2.dex)
    at io.invertase.firebase.firestore.FirestoreSerialize.documentChangeToWritableMap(FirestoreSerialize.java:129)
    at io.invertase.firebase.firestore.FirestoreSerialize.documentChangesToWritableArray(FirestoreSerialize.java:103)
    at io.invertase.firebase.firestore.FirestoreSerialize.snapshotToWritableMap(FirestoreSerialize.java:73)
    at io.invertase.firebase.firestore.RNFirebaseFirestoreCollectionReference$1.onComplete(RNFirebaseFirestoreCollectionReference.java:62)
    at com.google.android.gms.tasks.zzf.run(Unknown Source)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6165)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

This happened as I was trying to get some data from firestore. The method had been working fine before the upgrade.

What fixed it was upgrading the versions of the Firebase Gradle packages to `12.0.0`. I also upgraded  `play-services-*` packages as well. I was previously on version `11.8.0` for all of them. 

Is this newer version (v12) a requirement for 4.0? If so, it'd probably be good to document it in the release notes and upgrade guide!

**Comment by Salakar** [comment]
@ntomallen yep you're correct, v4 requires a minimum of v12: https://rnfirebase.io/docs/v4.0.x/getting-started#Supported-versions---React-Native-/-Firebase

We'll make sure to add this to the upgrade guide for the full release of v4, thanks for flagging.

**Comment by bemazo** [comment]
I have the same but with Version: 3.2.5 and Play Services 12.0.0

`AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getDocument()`

**Comment by bemazo** [comment]
@Salakar I got the same by Version 3.2.5 with playservices 12.0.0

`AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getDocument()`
it throws when I made .`onSnapshot` on a collection
