### ISSUE TITLE
Got an error Must start Twitter Kit with Fabric.with() first after include react-native-firebase

### ISSUE THREAD

**Issue by isnifer** [invertase/react-native-firebase#940]
### Issue
When I start to login in my app via `tipsi-twitter` module, [this line](https://github.com/tipsi/tipsi-twitter/blob/master/android/src/main/java/com/gettipsi/reactnativetwittersdk/TPSTwitterModule.java#L113) throws an exception.
Before `react-native-firebase` it works fine.
I don't know to do. Any ideas?

```
Caused by: java.lang.IllegalStateException: Must start Twitter Kit with Fabric.with() first
  at com.twitter.sdk.android.core.TwitterCore.checkInitialized(TwitterCore.java:160)
  at com.twitter.sdk.android.core.TwitterCore.getInstance(TwitterCore.java:76)
  at com.twitter.sdk.android.core.identity.TwitterAuthClient.<init>(TwitterAuthClient.java:71)
  at com.gettipsi.reactnativetwittersdk.TPSTwitterModule.getTwitterAuthClient(TPSTwitterModule.java:119)
  at com.gettipsi.reactnativetwittersdk.TPSTwitterModule.access$100(TPSTwitterModule.java:33)
  at com.gettipsi.reactnativetwittersdk.TPSTwitterModule$1.onActivityResult(TPSTwitterModule.java:45)
  at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:255)
  at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:730)
  at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:126)
  at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
  at com.tipsi.retail.MainActivity.onActivityResult(MainActivity.java:20)
  at android.app.Activity.dispatchActivityResult(Activity.java:6192)
  at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
```

### Environment

1. Application Target Platform: **Android**
2. Development Operating System: **macOS Sierra**
3. Build Tools: **25.0.1**
4. React Native version: **0.52.3**
5. RNFirebase Version: **3.3.1**
6. Firebase Module: **Crashlytics**

**Comment by isnifer** [comment]
Updated to TwitterKit 3 and bug has gone
