### ISSUE TITLE
Key people expected String[] but value was a java.util.ArrayList.  The default value <null> was returned.

### ISSUE THREAD

**Issue by judemanutd** [invertase/react-native-firebase#949]
### Issue

I get the following error 

```
Key people expected String[] but value was a java.util.ArrayList.  The default value <null> was returned.
Attempt to cast generated internal exception:
                                                   java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String[]
                                                       at android.os.BaseBundle.getStringArray(BaseBundle.java:1346)
                                                       at io.invertase.firebase.notifications.RNFirebaseNotificationManager.displayNotification(RNFirebaseNotificationManager.java:344)
                                                       at io.invertase.firebase.notifications.RNFirebaseNotificationManager.displayNotification(RNFirebaseNotificationManager.java:134)
                                                       at io.invertase.firebase.notifications.RNFirebaseNotifications.displayNotification(RNFirebaseNotifications.java:76)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                       at java.lang.Thread.run(Thread.java:761)
```

This is the code i have been using to create a notification

```
function createNotification(alert) {

    const notification = new firebase.notifications.Notification()
        .setNotificationId(JSON.stringify(alert['id']))
        .setTitle(alert['title'])
        .setContentInfo((alert['description']));

    if (Platform.OS === 'ios') {

    } else {

        const channel = new firebase.notifications.Android.Channel('breaking_news', 'Breaking News', firebase.notifications.Android.Importance.Max)
            .setDescription('Breaking News channel');

        firebase.notifications().android.createChannel(channel);

        notification
            .android.setSmallIcon('ic_launcher_notification_icon')
            .android.setAutoCancel(true)
            .android.setChannelId('breaking_news')
            .android.setSmallIcon('ic_launcher');
    }
    firebase.notifications().displayNotification(notification)
}
```

### Environment : Android

1. Application Target Platform:Windows 10

2. Development Operating System: Android Studio SDK version 27.1.1

3. Build Tools: 27.0.3

4. React Native version: 0.54.3

5. RNFirebase Version: 4.0.0

6. Firebase Module: Firebase Cloud Messaging, Firebase Notifications

**Comment by chrisbianca** [comment]
@judemanutd thanks for the report, we'll investigate.
